### ISSUE TITLE
[PROD] API list of endpoints is mismatched

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#1004]
## Issue
Hi, I know this happened once before and I think @GregoryHorvath fixed it, not sure why it's gone wonky again but hopefully an easy change.

If I go to https://goadmin.ifrc.org/api/v2/ and get the list of endpoints there, the one listed against **event** is actually **personnel_by_event** rather than event.  So unless one already knows to use event then one could go to the wrong place!

![image](https://user-images.githubusercontent.com/33625192/107598370-66bad280-6c82-11eb-943c-d8a23254248a.png)

## Expected behaviour
Each endpoint labelled correctly

## Impact
It's confusing for people first learning how to use the API - but if they already know which endpoint to use then both event and personnel_by_event seem to be fine.

(I'm only noticing this as I've had more API support queries come my way ;) )

Thanks and hello!

**Comment by GregoryHorvath** [comment]
@nanometrenat Deployed the possible fix to staging: http://dsgocdnapi.azureedge.net/api/v2 please check if you'll have the time.

**Comment by nanometrenat** [comment]
Wow that was quick!  Thanks a lot - yes all v2 name to v2 URL matches are happy in staging now.

If easy to make them come out in alphabetical order that would make things easier for the user but if not easy don't worry - at least now everything that's there is correct :)

THANKS and sending hellos

**Comment by GregoryHorvath** [comment]
@nanometrenat The alphabetical sorting is deployed to staging.
