### ISSUE TITLE
Track usage of the go-api

### ISSUE THREAD

**Issue by JonathanGarro** [IFRCGo/go-api#1026]
# Track usage of the go-api
My assumption is that **currently we do not track any usage**. If we already do then parts of the proposed tasks can be considered to be in-progress. I've split the effort into the following packages such that they can be picked up one after the other. However for the sake of efficiency I recommend we decide beforehand our goal tier.

## The tiers of commitment are,

1. **Basic**

We use a 3rd party service such as Microsoft Application Insights or Google Analytics. This is sufficient to feel the pulse on usage of start up apps.

### Features
1. Count number of times a certain endpoint is called.
2. Parameters with which these endpoints are called.
3. Count the number of errors or failures.
4. These metrics will be available in the dashboard of the 3rd party service. We would have to design the charts we consider important.

![Screen Shot 2021-03-03 at 11 21 21 AM](https://user-images.githubusercontent.com/8890661/109838588-4d1f0200-7c14-11eb-87b6-59165338be62.png)

A example Microsoft Application Insights dashboard using metrics gathered from a front end app.

### 40 hours of effort if we already know which metrics are important.

2. **Light**

We build an in-house analytics service. This gives us full control of the data but *with great power comes great responsibility*. Responsibilities include building, running and maintaining a separate analytics server and database independent of Go.

### Features

1. Includes all the [**Basic** tier features]().
2. 3rd party services don't use all the collected data but an approximation to be able to scale. If we control the data, we can use actual numbers instead.
3. We can build a dashboard on the go-frontend itself instead of navigating to a 3rd party website. *There are [ways to embed 3rd party charts](https://developers.google.com/analytics/devguides/reporting/embed/v1/) but I don't recommend that approach.*
 
![Screen Shot 2021-03-03 at 11 22 30 AM](https://user-images.githubusercontent.com/8890661/109838643-57d99700-7c14-11eb-9d5a-493943021f9a.png)

An example of a custom dashboard. [Source](https://demo.baremetrics.com/)

### 240 hours of effort + [Basic tier effort]().

3. **Expert**

We build analytics as a feature to our end users. We provide users access to the API via OAuth tokens generated using the Go interface. Each user can generate multiple tokens which get tracked separately. Each token comes with a dashboard showing how the API is being used through that token.

### Features

1. Includes all the [**Basic** tier features]().
2. Includes the [Light tier features](). The global dashboard is optional but does not really save significant effort — ~20 hours.
3. API access control page where users manage their OAuth tokens. Similar to the [OAuth system in Zoho](https://www.zoho.com/people/api/oauth-steps.html).
4. Dashboard per token for each user. [Similar to the features described here.](https://help.gumroad.com/article/74-the-analytics-dashboard) The dashboard would look similar to [the one in the Light tier]().

### 240 hours of effort + [Light tier effort]() + [Basic tier effort]().

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-api/issues/831 (which can probably be closed as the above ticket is far more comprehensive!)

**Comment by gulfaraz** [comment]
@tovari you mentioned in our chat that we're going ahead with the first option.
We need to choose an analytics service like Google Analytics or MS Application Insights.

In the NLRC, we use MS Application Insights because we already use Azure for other services.
@batpad  Do you know if we already have a preference on this?

After we make this decision, may I get access to the service we choose?

**Comment by batpad** [comment]
> @batpad Do you know if we already have a preference on this?

MS Application Insights sounds great.

> After we make this decision, may I get access to the service we choose?

@tovari @ThomasRaffort would you be able to help @gulfaraz with getting access to the resources on Azure he would need to set this up?

**Comment by gulfaraz** [comment]
@batpad Thank you for the confirmation.

The Azure resource required is [Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-new-resource). [Here are the docs for reference](https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview).
Please share the **Instrumentation Key** and **Connection String** which should be visible in the resource overview.

<img width="138" alt="Screenshot 2021-04-01 at 14 58 57" src="https://user-images.githubusercontent.com/3880591/113297347-ccc6ec00-92fa-11eb-8375-b135c767a4c8.png">

I also need access to the Azure portal to configure the dashboard with graphs etc to represent the insights gathered.

**Comment by ThomasRaffort** [comment]
@gulfaraz Let me help with that and connect you to the right DIT Infra folks. I believe there will be some additional cost setting up this resource but shouldn't be an issue. @tovari @batpad

**Comment by gulfaraz** [comment]
@szabozoltan69 created the requested Azure resource. Thank you.

The resource allows logging of analytics events. To visualize the logged events, I should configure a dashboard with charts and graphs. For this, I require access to the Azure portal with permissions to the Application Insights resource.

Would it be possible to grant access?

**Comment by gulfaraz** [comment]
```
InstrumentationKey=fa128365-fb09-4568-b944-b05e38b6b94c
IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/
```

**Comment by gulfaraz** [comment]
```
InstrumentationKey=fa128365-fb09-4568-b944-b05e38b6b94c
IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/
```

**Comment by gulfaraz** [comment]
PR #1057 sends incoming HTTP requests to Azure

I will create the analytics report dashboard after I get access to Azure

@tovari @szabozoltan69 @ThomasRaffort

**Comment by szabozoltan69** [comment]
Great. Azure access is not my responsibility.

**Comment by ThomasRaffort** [comment]
@gulfaraz I have requested for your Azure access to be expedited. Hopefully tomorrow. If not it should be done by 27 morning. Thanks

**Comment by gulfaraz** [comment]
@ThomasRaffort thank you

**Comment by ThomasRaffort** [comment]
@gulfaraz you should have access now. Let me know if it doesn't work. Thanks

**Comment by gulfaraz** [comment]
@ThomasRaffort I have requested access to Azure. Thank you!

**Comment by gulfaraz** [comment]
Azure resource is [here](https://portal.azure.com/#@ifrcorg.onmicrosoft.com/resource/subscriptions/39308fb0-9929-4b29-aafa-b3c78a8b0658/resourceGroups/IFRCGO-Trial1/providers/microsoft.insights/components/ifrcpgo001ai/overview) - which I can access :white_check_mark:

API requests are being logged properly - which I can see [here](https://portal.azure.com/#@ifrcorg.onmicrosoft.com/resource/subscriptions/39308fb0-9929-4b29-aafa-b3c78a8b0658/resourceGroups/IFRCGO-Trial1/providers/microsoft.insights/components/ifrcpgo001ai/performance) :white_check_mark:

<img width="365" alt="Screenshot 2021-04-29 at 12 55 20" src="https://user-images.githubusercontent.com/3880591/116541172-6c23d280-a8eb-11eb-96b6-745d8eabe0c2.png">

However, when I run [the query that generates the above graph](https://portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F39308fb0-9929-4b29-aafa-b3c78a8b0658%2FresourceGroups%2FIFRCGO-Trial1%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fifrcpgo001ai/source/AIExtension.CuratedPerformance/query/%2F%2F%20count%20of%20requests%20by%20name%0Alet%20start%3Ddatetime(%222021-04-29T09%3A56%3A00.000Z%22)%3B%0Alet%20end%3Ddatetime(%222021-04-29T10%3A56%3A00.000Z%22)%3B%0Alet%20timeGrain%3D1m%3B%0Alet%20dataset%3Drequests%0A%2F%2F%20additional%20filters%20can%20be%20applied%20here%0A%7C%20where%20timestamp%20%3E%20start%20and%20timestamp%20%3C%20end%0A%7C%20where%20client_Type%20!%3D%20%22Browser%22%0A%3B%2F%2F%20count%20all%20requests%0Adataset%0A%7C%20summarize%20count_%3Dsum(itemCount)%20by%20bin(timestamp%2C%20timeGrain)%0A%7C%20extend%20request%3D'Overall'%0A%2F%2F%20render%20result%20in%20a%20chart%0A%7C%20render%20timechart/prettify/1), I receive this text **No results found from the specified time range**. This does not make sense as the graph shows that there are logged requests. :x:

My inference is that my permissions do not grant access to the raw logs. This can be verified by running the same query with either different permissions or accounts.

If possible, could @szabozoltan69 please open [this link](https://portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F39308fb0-9929-4b29-aafa-b3c78a8b0658%2FresourceGroups%2FIFRCGO-Trial1%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fifrcpgo001ai/source/AIExtension.CuratedPerformance/query/%2F%2F%20count%20of%20requests%20by%20name%0Alet%20start%3Ddatetime(%222021-04-29T09%3A56%3A00.000Z%22)%3B%0Alet%20end%3Ddatetime(%222021-04-29T10%3A56%3A00.000Z%22)%3B%0Alet%20timeGrain%3D1m%3B%0Alet%20dataset%3Drequests%0A%2F%2F%20additional%20filters%20can%20be%20applied%20here%0A%7C%20where%20timestamp%20%3E%20start%20and%20timestamp%20%3C%20end%0A%7C%20where%20client_Type%20!%3D%20%22Browser%22%0A%3B%2F%2F%20count%20all%20requests%0Adataset%0A%7C%20summarize%20count_%3Dsum(itemCount)%20by%20bin(timestamp%2C%20timeGrain)%0A%7C%20extend%20request%3D'Overall'%0A%2F%2F%20render%20result%20in%20a%20chart%0A%7C%20render%20timechart/prettify/1) to check if you get a chart with a table of results?

@tovari @ThomasRaffort @batpad

**Comment by szabozoltan69** [comment]
I can see only this on the above link:
![kép](https://user-images.githubusercontent.com/6050643/116543977-d8ec9c00-a8ee-11eb-8bb3-bc7b6af7d8ed.png)

**Comment by gulfaraz** [comment]
@szabozoltan69 the link should have populated the query in the "Type your query here..." section

But at least it loads the right page, please type `requests` in the query area and click the blue "Run" button.
For clarity, the `requests` statement is equivalent to `SELECT * from requests` in SQL

The results should show up at the bottom if you have access.

**Comment by szabozoltan69** [comment]
![kép](https://user-images.githubusercontent.com/6050643/116555593-dee97980-a8fc-11eb-8b52-8b695995da9e.png)

**Comment by gulfaraz** [comment]
@szabozoltan69 the query to use is `requests`

**Comment by szabozoltan69** [comment]
I wrote it. requests

**Comment by szabozoltan69** [comment]
![kép](https://user-images.githubusercontent.com/6050643/116559889-28d45e80-a901-11eb-8029-da0ed9ea69a3.png)

**Comment by gulfaraz** [comment]
@szabozoltan69 Thank you for that. Looks like a dead-end to me. If you're available, it may be helpful to have a call on this. But I'm not sure what's missing at this point.

**Comment by gulfaraz** [comment]
@szabozoltan69 and I discussed this issue on a call. We believe this may be a permissions issue so @szabozoltan69 is following up with Zoltan.LEVAI@ifrc.org and Peter.LUKACS@ifrc.org via email.

**Comment by gulfaraz** [comment]
I get the expected results now. Thank you @ThomasRaffort for quickly resolving the access issue.

@szabozoltan69 I've asked IT to close the ticket. Thank you for creating it.

<img width="792" alt="Screenshot 2021-04-30 at 14 32 57" src="https://user-images.githubusercontent.com/3880591/116695478-f853f980-a9c0-11eb-8dc7-bd5b189f22a6.png">

**Comment by gulfaraz** [comment]
@tovari I'm holding off on the dashboard until the decision on the platform is made. #1018

**Comment by gulfaraz** [comment]
The [decision](https://github.com/IFRCGo/go-api/issues/1018#issuecomment-845134993) is made to switch to Google Analytics instead of MS Application Insights.

I intend to use [the django-google-analytics library](https://github.com/praekeltfoundation/django-google-analytics#2-middleware--celery) for the go-api.

**Comment by gulfaraz** [comment]
There are no off-the-shelf libraries that support Google Analytics. So the decision is to continue using Application Insights for go-api and Google Analytics for go-frontend. Discussion is in https://github.com/IFRCGo/go-api/issues/1018.

**Comment by batpad** [comment]
@gulfaraz since we using Azure Insights, I'm guessing there is nothing remaining to be done here?

Would you be able to quickly outline how we test that this works, and then we can close this?

**Comment by gulfaraz** [comment]
> I'm guessing there is nothing remaining to be done here?

yes

> Would you be able to quickly outline how we test that this works, and then we can close this?

[This dashboard has graphs to show API usage and response codes.](https://portal.azure.com/#@ifrcorg.onmicrosoft.com/dashboard/arm/subscriptions/39308fb0-9929-4b29-aafa-b3c78a8b0658/resourcegroups/ifrcgo-trial1/providers/microsoft.portal/dashboards/c8955f9b-8ea5-46c1-a292-1ad620aee9bf-dashboard) In the dashboard, you should be able to see graphs based on the production data.

**Comment by tovari** [comment]
@jhenshall, do you have access to the dashboard?

**Comment by tovari** [comment]
Hey @gulfaraz, would you mind to explain what can we see on the dashboard? Thanks!

![image](https://user-images.githubusercontent.com/68283148/121888289-19c23800-cd18-11eb-8ca4-fa13814374e8.png)

**Comment by gulfaraz** [comment]
@tovari all those charts existing when I was given access to the dashboard. I believe they're related to the health of the AppInsights resource and not the go-api. The graphs below the screenshot are the ones I created, which I hope are intuitive.

**Comment by szabozoltan69** [comment]
These are the below charts:
![kép](https://user-images.githubusercontent.com/6050643/122244049-de18a100-cec4-11eb-8b6f-00e9e5a31005.png)
![kép](https://user-images.githubusercontent.com/6050643/122244110-e5d84580-cec4-11eb-9f15-1bcbdb201bf2.png)

**Comment by tovari** [comment]
@gulfaraz, thanks! Does this mean that there were more than 400k requests (with code 200) in the past 30 days? Does it count only the external requests, or also the the requests from the frontend? If both, is it possible to separate them in the charts?

**Comment by gulfaraz** [comment]
@tovari

> Does this mean that there were more than 400k requests (with code 200) in the past 30 days?

yes

> Does it count only the external requests, or also the the requests from the frontend?

both

> If both, is it possible to separate them in the charts?

we would have to add a custom parameter on requests made from the frontend to separate them

**Comment by nanometrenat** [comment]
@ypyelab this is one of the tickets re API logging.  See also 
https://github.com/IFRCGo/go-api/issues/572#issuecomment-590194587
and
https://github.com/IFRCGo/go-api/issues/831
