### ISSUE TITLE
3W email notifications 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1061]
Recently, auto-update feature of the 3W project status have been implemented: project status turns to 'Ongoing' when actual date is equal to the start date, and turns to 'Completed' when actual date passes End date. 
We need to inform project creator user by an automated email notification a few days before the End date that the project status will be changed automatically in X days and if this is not correct, the end date should be modified.

**Comment by thenav56** [comment]
Hi @tovari, What value should we use for X? Also, Do we need to send an email when the status is changed automatically?

**Comment by thenav56** [comment]
Also, is there any mockup or design for the email template?

**Comment by tovari** [comment]
@thenav56, can we use the same email template we use for the other email notifications? Open in GO would link to the project page.
As we can not subscribe to 3w projects at the moment, please remove the "You are receiving this update based on your selected preferences.
Update your preferences" disclaimer.

The text on the top of the mail could be:
"XXX project end date is in 5 days. Please note that the project status will automatically change to 'Completed', when the end date passes. You can update the end date to further keep the project in 'Ongoing' status."

I feel, we should have a subscription option to projects as well, but it will be requested in another ticket.

**Comment by thenav56** [comment]
@tovari The feature is sent to the staging. Can you check and let me know if you have any feedback/issues.

**Comment by tovari** [comment]
@thenav56, thanks. Emails are being sent as expected. It would be great though to use the email template (or create a similar of the other type of notifications (see a sample below). Open in GO link could open the project view in GO. 

![image](https://user-images.githubusercontent.com/68283148/123609059-9f0d1880-d7ff-11eb-8c36-a5c7da0b8c8d.png)

**Comment by tovari** [comment]
@vdeak, would you mind to check, if 3W project notification email was sent today (14.07) about the Mozambique - Tropical CYclone project (aid:14956) to the creator?
If yes, then I will close this ticket.
