### ISSUE TITLE
[PROD] Country information missing from districts API

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-api#1072]
## Issue
With the latest changes to remove the country information from the districts table, there is now no country information when accessing the districts API.

## Expected behaviour
District API has fields for:

- Country name
- ISO2
- ISO3

## Impact
High - anyone using the districts API could be affected.

**Comment by szabozoltan69** [comment]
CountryId is in the District, so can be linked to country.
(Nevertheless the information should be shown, it's true, on districts API endpoints also.)

**Comment by geohacker** [comment]
That's right, we can join the country table using https://docs.djangoproject.com/en/1.8/ref/models/querysets/#select-related. I'm having trouble setting up the API locally but will sort that out with @batpad when he is online tomorrow.

**Comment by vdeak** [comment]
![image](https://user-images.githubusercontent.com/81553689/118605445-95cb6d80-b7b6-11eb-9da8-954af7482675.png)
Added country_name and country_iso, pls. confirm if it is fine.

**Comment by tovari** [comment]
Thanks @vdeak! country_iso should be rather called country_iso3.

**Comment by jhenshall** [comment]
This would be a good opportunity to have _both_ ISO2 and ISO3 in the district API. So should be:

- `country_iso` = ISO2 (e.g. `AD`)
- `country_iso3` = ISO3 (e.g. `AND`)

Thanks @vdeak and good spot @tovari!

**Comment by vdeak** [comment]
Added country_iso and country_iso3

![image](https://user-images.githubusercontent.com/81553689/119656725-4d055b80-be2b-11eb-86de-310bc3067a29.png)

**Comment by batpad** [comment]
@vdeak is this available for testing on staging?

**Comment by vdeak** [comment]
@batpad Yes, it is on Staging
