### ISSUE TITLE
Adding new ERU types

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-api#1085]
**Is your feature request related to a problem? Please describe.**
New type of ERUs have been developed, so we need to add them to the dropdown menu. Also notice that Basecamp needs to be removed as further classification per sizes has been added.
https://prddsgocdnapi.azureedge.net/en/deployments/eruowner/39/change/

**Describe the solution you'd like**
Add new types of ERUs:

- Water Supply and rehabilitation
- Household Water Treatment and safe storage
- Cholera Case management at Community level
- Safe and Dignified Burials
- Community Based Surveillance
- Base Camp – S
- Base Camp – M
- Base Camp – L

**Where does the data come from and how is it maintained?**
Manually by the Surge team

**Should there be any restrictions around viewing or updating information related to this feature**
Maintain the current behavior.

@szabozoltan69

**Comment by szabozoltan69** [comment]
Which value can be converted the recent Basecamp values?

**Comment by szabozoltan69** [comment]
Change is done, deployed to staging.
https://github.com/IFRCGo/go-api/blob/develop/deployments/models.py#L18-L53

**Comment by anamariaescobar** [comment]
HI @szabozoltan69, I just checked in staging and the  dropdown in the backend looks good, but when I created a new ERU in the front end appears like "Undefined" 
![image](https://user-images.githubusercontent.com/69478743/119954610-72b37180-bf9f-11eb-95fe-d780e1c98296.png)

**Comment by szabozoltan69** [comment]
It's true that I made only backend change. So maybe some frontend change also needed? @vdeak – could you please give a check, whether there is a frontend list for ERU-s, independently from backend list?

**Comment by batpad** [comment]
Whoops, I'm sorry I missed seeing the notification here.

@szabozoltan69 as discussed in chat:

 - For now, let's just add these new types to the frontend list.
 - Let's create a ticket to remove the list on the frontend and just have it pull from the API, so we don't maintain two lists in the future.

**Comment by batpad** [comment]
> The augmentation would be:

That looks really good to me @szabozoltan69, thank you. Would you be able to go ahead with the change and make a PR on the frontend?

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-frontend/pull/1915
