### ISSUE TITLE
Historical data queries for Appeals API

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1086]
Breaking this out as a more specific issue from #1003 to cover only the changes to the Appeals API.

Make changes to Appeals DB schema to support historical queries and add Django Signals methods to make sure historical data is populated whenever an Appeal is changed.

Add time GET parameters to the Appeals end-point to enable querying data for a particular point in time.

cc @vdeak @tovari

**Comment by batpad** [comment]
@karitotp here it will be great to test that none of the existing functionality around Appeals on the frontend is broken:

 - Check that values in headers for Funding Requirements, Funding Coverage are coming correctly.
 - Appeals list tables look correct.

**Comment by karitotp** [comment]
All looks good to me, @batpad

**Comment by vdeak** [comment]
How to test the API:

http://localhost:8000/api/v2/appeal/?**date=2020-01-01**

The new parameter's name is date
