### ISSUE TITLE
The API docs (https://dsgocdnapi.azureedge.net/docs/) gives Server error

### ISSUE THREAD

**Issue by vdeak** [IFRCGo/go-api#1098]
## Issue
https://dsgocdnapi.azureedge.net/docs/ gives Server error(500)

## Steps to reproduce
Try to open api/docs on stage or locally.

Issue is in class ProjectViewset(RevisionMixin, ReadOnlyVisibilityViewsetMixin, viewsets.ModelViewSet)
...
request_format_type = **self.request**.GET.get('format', 'json')

![image](https://user-images.githubusercontent.com/81553689/121014127-ea508000-c799-11eb-8b20-62b399aeecd4.png)

## Related feature
Issue is related to "Add Custom serializer for Project"

**Comment by thenav56** [comment]
The fix is deployed to staging.
