### ISSUE TITLE
[PROD] Edits to Emergency page failing due to DATA_UPLOAD_MAX_NUMBER_FIELDS

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1127]
Seems like we are exceeding the max number of fields allowed in a POST request by default by Django when editing large emergencies, causing a failure on form submission in the Admin.

Creating this ticket to have a record of the issue. Thank you @thenav56 for the catch.

cc @tovari @anamariaescobar

**Comment by batpad** [comment]
See https://docs.djangoproject.com/en/3.2/ref/settings/#data-upload-max-number-fields

**Comment by nanometrenat** [comment]
Hi @batpad @tovari this was already on the backlog as something needing to be investigated (same thing happened last year and again the year before) - see https://github.com/IFRCGo/go-api/issues/887
