### ISSUE TITLE
[PROD] Links to emergencies at Operation lists are broken

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1129]
## Issue
*Links to an emergency in the operations (country page or in the all operations list) contains emergency title instead of the emergency id. These urls don'T exist.
Affects Staging and Prod as well*

## Steps to reproduce
*https://go.ifrc.org/appeals/all/?country=136
Click on the Operation link at any list item.*

![image](https://user-images.githubusercontent.com/68283148/124513806-e5eca680-dddb-11eb-8b78-797340069e54.png)

## Impact
Impacts all users

## Severity
Severe

## Is there a workaround?
Emergencies can be searched instead, but it is cumbersome.

**Comment by nanometrenat** [comment]
@tovari I think this is fixed?

**Comment by tovari** [comment]
Indeed, thanks for the reminder @nanometrenat!
