### ISSUE TITLE
3W Excel upload

### ISSUE THREAD

**Issue by gulfaraz** [IFRCGo/go-api#1149]
_I'm creating this feature request on behalf of @JonathanGarro who sent the details via email._

The only stable way of getting data into the 3W is currently via the front end, which makes it easy enough for a limited number of projects but gets cumbersome with large portfolios.

There is already an Excel-based solution (see steps to use it below), but there are several problems with it. One is that the admin1 field is complicated (it would require cascading dropdowns after admin0 to make sure folks use the right names), and the other is that it doesn’t currently support updating (if you already saved project data to the system, you couldn’t use the upload tool to overwrite the existing record with new data).

Bulk upload directions:
1. Log in and go to the Projects under Deployments & 3Ws on the admin page:
    a. Production: https://goadmin.ifrc.org/en/deployments/project/
    b. Staging: https://dsgocdnapi.azureedge.net/en/deployments/project/
2. Import template https://goadmin.ifrc.org/en/deployments/project/import-template/ will download the project import template csv file
3. Open the downloaded csv and fill with the project data. One line per project should be added, and all affected district needs to be listed.
4. Upload the file by clicking the 'New import' button. Select file and separator type.

**Comment by tovari** [comment]
I started to create a new Excel template with data validations (date fields), drop-down selections (also country dependant admin selection). Its a macro enabled file, so the file contains instructions, how to export it to csv.
A few things still needs to be done to further improve the usability:
- country and admin list updates to adjust them to the current db values
- handling whole countries. Currently all admins have to be selected to add an entire country (required by the import). This is cumbersome. Import function could handle a specific value instead (e.g."Countrywide") that would select all admins during the import (cc: @thenav56 ). Leaving blank the admin would not select any admin.
- maybe a one-click solution to export it to a csv. Alternatively, adjust the import function to enable to import the macro enabled file.

Adding @luisfanovich as he has also tested a bit the new template.

You can download and check the xlsm template here: https://teams.microsoft.com/_#/files/General?groupId=be22b1e3-23ec-4ddd-80cd-dc7ab032d2eb&threadId=19%3A8f526fd5b918469799d2462ff2c5e1f0%40thread.skype&ctx=channel&context=3W_import_template&rootfolder=%252Fsites%252FGOIVfordeveloperteam%252FShared%2520Documents%252FGeneral%252FTemp%252F3W_import_template

**Comment by tovari** [comment]
Xref: #1304 
Closing this ticket.
