### ISSUE TITLE
Align P-codes with External Data Sources

### ISSUE THREAD

**Issue by gulfaraz** [IFRCGo/go-api#1151]
_I'm creating this feature request on behalf of @JonathanGarro who sent the details via email._

Right now the system apparently uses ICRC p-codes which aren’t compatible with OCHA, and I’d like to explore what we can do to make 3W data more interoperable with external sites like HDX.

**Comment by JonathanGarro** [comment]
Notes from my conversation with Simon Johnson and @jhenshall on 2021-08-06:

GO currently uses ICRC p-codes which leads to interoperability issues with partners like OCHA. Johnny is already engaged with them on this issue, citing three key decision gates: 
- ICRC and IFRC need to agree on a data model
- There needs to be an owner identified (or some other governance structure) as it is currently dealt with via ICRC volunteers (e.g. there is a clunky/cumbersome process of clicking around Google maps to find branch locations to convert them to x,y coordinates - this should be data collected and shared by the NS directly, and support is likely necessary to help with this outside of any GO engagement).
- Need to have a clear argument to communicate with NS about the value of p-code data.

**Simon sees two scenarios when addressing this issue:** 

1. Best case: ICRC adopts UN P-codes for most countries (exceptions will exist in places like Palestine, and in those cases the gap will need to still be filled by ICRC). 
2. Minimum viable solution: A lookup table that merges the two datasets, defaulting to UN and falling back to ICRC. A fuzzy matching system would help with issues that arise from translating place names from different alphabets like Cyrillic or Arabic).

**Comment by jhenshall** [comment]
Thanks for capturing but there is already a ticket on the main GO backlog: https://github.com/IFRCGo/go-frontend/issues/1838 

Would suggest consolidating and keeping conversation in one place, especially at this early stage before we have a clear distinction between API work and broader GO dev. 🙂

**Comment by JonathanGarro** [comment]
Thanks @jhenshall - closing this ticket and migrating my comment there.
