### ISSUE TITLE
Upgrade to Django v3

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1152]
We are running on Django v2.2.4 - we should plan an upgrade to v3 at some point, which seems to have been stable for over a year now .

@thenav56 if you have any experience with a 2 -> 3 upgrade / any idea of how much work that might involve for `go-api`, please drop notes.

Hopefully we can prioritize this in the next months.

Thank you for the nudge @thenav56 @gulfaraz .

**Comment by thenav56** [comment]
It shouldn't involve that much on the coding side (but depends on the usages of low-level Django API), but we will need a plan for proper testing the whole site-wise.

We should also start using some package manager for python, I recommend [poetry](https://python-poetry.org/), it's fast and easy to set up. I think we should do this before the v3 upgrade.
