### ISSUE TITLE
[PROD] *URGENT* Appeals docs not pulling through to emergency page

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#1173]
## Issue
The Afghanistan MDRAF007 Revised Emergency Appeal 2 [pdf](https://adore.ifrc.org/Download.aspx?FileId=444547) has not yet pulled through to https://go.ifrc.org/emergencies/5220#reports yet even though it was published yesterday and is successfully showing on APPLE and on the IFRC public website at https://www.ifrc.org/appeals

I don't have superuser access any more, but I strongly suspect the cronjob is failing due to the ifrc.org website having recently changed - so the old ifrc.org URL GO scrapes the appeal docs from doesn't have any info any more.  xref https://github.com/IFRCGo/go-frontend/issues/2042 re the ifrc.org website upgrade.

## Steps to reproduce
Go to Emergency page/documents (link above) and check that latest appeal doc (Emergency Appeal Revision) is present.

## Related feature
According to old ticket https://github.com/IFRCGo/go-frontend/issues/968 and the code at https://github.com/IFRCGo/go-api/blob/master/api/management/commands/ingest_appeal_docs.py the cronjob looks at URL `https://www.ifrc.org/en/publications-and-reports/appeals/` to get the appeal docs (and filters from there e.g. `https://www.ifrc.org/en/publications-and-reports/appeals/?ac=MDRAF007&at=0&c=&co=&dt=1&f=&re=&t=&ti=&zo=`).  However under the new ifrc.org website this URL is broken (404).  Appeal docs are now found at base URL `https://www.ifrc.org/appeals` however I'm not sure what the filter parameters are for the new website.

Action required:

1. change base URL to match new ifrc.org website structure
2. figure out what new filter parameters are on ifrc.org appeals page (this may require asking IT/comms?) so they can be implemented on GO.

## Impact
This is a majorly public-facing appeal, need to make sure the information is correct and up-to-date.

**Comment by nanometrenat** [comment]
You will know it works when `https://adore.ifrc.org/Download.aspx?FileId=444547` pulls through to the emergency page above

**Comment by szabozoltan69** [comment]
I am on this. Will be changed the fetching URL from https://www.ifrc.org/en/publications-and-reports/appeals to https://www.ifrc.org/appeals.

**Comment by szabozoltan69** [comment]
This https://github.com/IFRCGo/go-api/pull/1175/files is a hotfix now, after patching master we should do it to develop also.

**Comment by szabozoltan69** [comment]
Fortunately the scraper job was planned in a way so in the GO-side-tables already (in 3 months) existing appeal docs are not documented again. Their end-point download links are correct. The new ones will be fixed with this patch.

**Comment by nanometrenat** [comment]
Andras is working with comms on the ifrc.org/appeals page, as on the face of it it seems to be caching some data (as changes made in APPLE aren't being reflected on ifrc.org/appeals new page, whereas it is reflected on the old ifrc.org/appeals page).  So that is another reason to go direct to the source...

**Comment by szabozoltan69** [comment]
We do have appeals source (http://go-api.ifrc.org/api/appeals), but the appeal-docs would be great to have from somewhere. But thanks for the research!

**Comment by nanometrenat** [comment]
Yep ifrc.org/appeals is where we get the appeal doc links from currently though right?  And at the moment that page has the wrong metadata about the appeal docs... as not pulling through updates from Apple...
