### ISSUE TITLE
[PROD] scrape_pdfs fails due to ifrc.org structure change

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1179]
## Issue
We have a daily run cron job: manage.py scrape_pdfs. Recently there are issues with it, which is reported by the admin interface "red ⚠". It leads to https://goadmin.ifrc.org/en/api/cronjob/96779/change . This scraper reads 4 kind of data: EPOA, OU, FR, EA. Their source leads to http://www.ifrc.org/Utils/Search/Rss.ashx... – due to the ifrc.org structure change it breaks and should be fixed. No pdf-s is read until then. See https://github.com/IFRCGo/go-api/blob/develop/api/management/commands/scrape_pdfs.py#L92-L95

## Steps to reproduce
Just visit goadmin.ifrc.org and check the red ⚠ at the top.
The log is here: https://pastebin.com/3dTDpHZt - it was OK until Sept 7.

## Expected behaviour
Like it was before Sept 7.

## Related feature
Appeals documents

## Impact
2-3 new `appeals?` Before this date there were not many pdf scraped daily.

## Severity
Appeals are crucial on this site.

## Is there a workaround?
Users can contact IM for a manual update

**Comment by szabozoltan69** [comment]
The job was written by @thenav56 – if you can find a fix, it would be great appreciated. If have no time for it now, please give some guidelines about the possible fixes.

**Comment by thenav56** [comment]
@szabozoltan69 Looks like the RSS feeds are broken now. They were used to get the pdf URLs.
Not sure whom to contact to get a usable source now. Do you have any idea?
@batpad @tovari 

https://github.com/IFRCGo/go-api/blob/56ef11af63e04ceee42610350fa12a81c53601e5/api/management/commands/scrape_pdfs.py#L91-L96

![2021-09-08-145500](https://user-images.githubusercontent.com/7059255/132481175-f39ccef5-300e-4e74-929e-473d9f9b59c8.png)

**Comment by szabozoltan69** [comment]
For some time we can use this, but the lifetime of that link shall be closed soon.
https://episerver.ifrc.org/Utils/Search/Rss.ashx?at=241&c=&co=&dt=1&f=2018&feed=appeals&re=&t=2020&ti=&zo=

**Comment by thenav56** [comment]
@szabozoltan69 Let's use that one for now.

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-api/pull/1180 solves this.

**Comment by szabozoltan69** [comment]
Deployed to both places.
