### ISSUE TITLE
Add Annual Figures to 3W Records

### ISSUE THREAD

**Issue by JonathanGarro** [IFRCGo/go-api#1189]
This feedback comes from user feedback shared as part of [this presentation](https://docs.google.com/presentation/d/1kLyn1d3Avsifd0sZGfdVrjTO7TcLhMA6dc1l_l3Tew8/edit?usp=sharing). 

Some users request ability to break data on 3W down by year. The two sections this would impact are: 

1. Budget: Take min and max year from start and end date (e.g. 2020 and 2021), generate separate lines in the budget section with those years as labels. If user submits data by year, the total budget field would become a summed calculation of all annual boxes.
2. Beneficiaries: Again, separate rows per year, still broken down by gender, and total summed if being reported by year.

**Comment by tovari** [comment]
@JonathanGarro, this should be an optional, right?

**Comment by tovari** [comment]
Mockup from Jonathan:
![annual reporting](https://user-images.githubusercontent.com/68283148/132874701-7900fe55-3ca6-475a-a3dc-ea972fcd423e.jpg)

Annual reporting on:
![annual reporting on](https://user-images.githubusercontent.com/68283148/132874723-7810e06b-965f-49a0-81be-3dc47c698ea1.jpg)

**Comment by szabozoltan69** [comment]
Could you suggest me a checkbox implementation like this, @frozenhelium ?
![image](https://user-images.githubusercontent.com/6050643/162560148-357fa2b1-21e9-426c-9659-e5fb304fdb56.png)

**Comment by szabozoltan69** [comment]
It is not clear, how to keep on backend these data. Shall we have a finite "year list"? 5? Or shall we create a new (joined) table for these extra records?

**Comment by szabozoltan69** [comment]
@JonathanGarro @tovari Do we need an annual split also for "people reached"?
(On the screenshot it can not be seen, but I suppose so.)

**Comment by szabozoltan69** [comment]
Can be tested on Staging.
E.g. https://go-stage.ifrc.org/three-w/2783
Or https://go-stage.ifrc.org/three-w/new

**Comment by szabozoltan69** [comment]
![kép](https://user-images.githubusercontent.com/6050643/188139629-f34f06a7-f58a-4601-8a01-a2cfc98c175e.png)

**Comment by szabozoltan69** [comment]
The arriving changes are in this pull request: https://github.com/IFRCGo/go-frontend/pull/2470

**Comment by szabozoltan69** [comment]
Should look like this:
![Uploading 1189_Mariam_nicing.png…]()

**Comment by szabozoltan69** [comment]
Should look like this:
![Uploading 1189_Mariam_nicing.png…]()

**Comment by szabozoltan69** [comment]
The new layout was implemented (with some limitations, e.g. recently it is not possible to set grey backbround for the entity number but not setting grey background for the label before it).
Try it e.g. on https://go-stage.ifrc.org/three-w/2783

**Comment by szabozoltan69** [comment]
Still needed to do some tailoring. e.g. no scrollbar, align numbers to right, narrower FieldOutputs.
