### ISSUE TITLE
Add Project Description Field to 3W

### ISSUE THREAD

**Issue by JonathanGarro** [IFRCGo/go-api#1190]
Requesting an optional field under the Project Name field on 3W records that would allow users to include a short narrative in plain text about the project. Propose character limit to prevent overly long entries.

**Comment by tovari** [comment]
@JonathanGarro, 500 characters limit would be sufficient? (~1800 characters is one page)

**Comment by JonathanGarro** [comment]
@tovari I just looked at what 500 would be, it might be too little. let's try 750 (the help text will need to include a message that this is just very high level info describing the activity).

**Comment by LukeCaley** [comment]
would it be a major lift to provide the option to upload a (or multiple) files related to the project?  There might be a storage issue to consider? @tovari @JonathanGarro
