### ISSUE TITLE
Access Emergency Tabs from the API

### ISSUE THREAD

**Issue by ypyelab** [IFRCGo/go-api#1204]
**Is your feature request related to a problem? Please describe.**
We don't have a way to verify from the API if there are additional tabs created for an emergency (besides the by default ones).

**Describe the solution you'd like**
Have an indication of the additional tabs created for the emergencies (in the event table)

**Describe alternatives you've considered**
Create another dataset with the emergencies that have additional tabs

**Additional context**
I'm trying to get some indicators on the National Societies engagement with GO. Some indicators of this are the i) logins per NS, ii) the number of FR and 3W projects created by NS users, and iii) the updates done to their emergency pages.
For the aspect iii), there are multiple ways in which we could capture updates. Some of it we can get from the 'summary' field of the 'event' dataset, some of it we can get from the 'situation report' dataset, but a part of it we can not get from the existent data. We can not verify from the API if there are additional tabs created for an emergency.

**Comment by szabozoltan69** [comment]
Deployed to staging and prod.

**Comment by nanometrenat** [comment]
Just to note that you could always use the method we used to use to see which emergencies had content on additional tabs - by looking a the event_snippet endpoint (which tells you which tab each snippet is on)
