### ISSUE TITLE
[PROD] Missing appeal documents

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1214]
## Issue
*Many appeal documents are not available in GO. Some of the documents are ingested, others not.*

## Steps to reproduce
*Example for not ingested document: https://adore.ifrc.org/Download.aspx?FileId=292176
There are a lot of other missing documents a well. *

## Expected behaviour
*All appeal documents should be ingested.*

## Impact
*Missing documents might be misleading for users*

## Severity
*High*

## Is there a workaround?
*Documents are available at https://www.ifrc.org/appeals*

**Comment by tovari** [comment]
Hi @szabozoltan69,
looks like we still miss documents. E.g:
MDRPK018:
https://adore.ifrc.org/Download.aspx?FileId=363702
MDRGT016:
https://adore.ifrc.org/Download.aspx?FileId=364276
MDRMY004:
https://adore.ifrc.org/Download.aspx?FileId=367994 
and many more...

**Comment by tovari** [comment]
And this is an example from the same type of document (DREF Final Report), which was successfully imported and available in GO:
MDRSO009
https://adore.ifrc.org/Download.aspx?FileId=367994

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-api/pull/1217 fixed these.

**Comment by tovari** [comment]
We are almost there, but have some missing documents. A few of them:
<html>
<body>


Philippines - Typhoon Vamco (MDRPH042) | Philippines | MDRPH042 | Cyclone | DREF Operation Final Report | 24 Sep 2021
-- | -- | -- | -- | -- | --
Colombia - Hurricane Iota (MDRCO017) | Colombia | MDRCO017 | All other disaster and emergencies | DREF Operation Final Report | 21 Sep 2021
Madagascar - Food Insecurity (MDRMG017) | Madagascar | MDRMG017 | Food Insecurity | DREF Operation Final Report | 18 Sep 2021
St Vincent & Grenadines - Dengue 2020 (MDRVC004) | Saint Vincent And The Grenadines | MDRVC004 | Epidemic | DREF Operation Final Report | 13 Sep 2021


</body>
</html>

**Comment by tovari** [comment]
It seems the structure of the data intake still not result a stable structure:
![image](https://user-images.githubusercontent.com/68283148/135922700-d3b32f41-4088-4024-be77-41b2efc2b5e8.png)

**Comment by szabozoltan69** [comment]
The misuse of "name" could be come from the previous version, where the name of the column was not checked but a fix index (4 or 5) was used. I'll check them and also the mentioned missing ones. (And I try to fix the names also.)
The "created_at" can be only date, this is the reliable source. So all the created_at-s that has some not-0:00 time 
is suspicious. This can be seen in the "name" also of these rows...

**Comment by szabozoltan69** [comment]
The documents of https://github.com/IFRCGo/go-api/issues/1214#issuecomment-933830061 is present, but their name is not appropriate. E.g. MDRCO017 has all the 3 documents, but the https://adore.ifrc.org/Download.aspx?FileId=448840 one has this name: "All other disaster and emergencies". So basically the attributes should be fixed.
