### ISSUE TITLE
Catalogue of services - Document and photo migration

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1225]
The Surge catalogue of services has been migrated to GO, except the documents and photos, which are still located on ifrcgo.org.
We need to 
- find a suitable solution to store such files, 
- move the existing content to the new location, and 
- update the links in the catalogue

Thanks!

**Comment by szabozoltan69** [comment]
A question: where should I upload these documents? To **staging** backend, to **production** backend? Depending on this the frontend should refer these documents (as link to **one** of the backends).
By my opinion the production backend usage is higher; we could relieve the production backend load if the images and documents would be kept on staging. The other aspect is the blackout time; the staging is (a bit) more often down.

**Comment by szabozoltan69** [comment]
An example of the "new possibility": instead of ifrcg.org - https://dsgofilestorage.blob.core.windows.net/api/documents/Communications1/Rapid_Response_Profile_Communications_Coordinator.pdf (staging backend)

**Comment by tovari** [comment]
Surge CoS documents and photo migration from ifrcgo.org
All documents have been copied to sharepoint. The list of external links is attached to the ticket.
Please update the document links on frontend to the new locations.

Photos can be migrated to a suitable GO server. There is no requirement to provide a functionality to update them by the Surge team.
Therefore, photos can be moved to the frontend.

[Surge_ExternalLinks.csv](https://github.com/IFRCGo/go-frontend/files/7897999/Surge_ExternalLinks.csv)
