### ISSUE TITLE
Create user groups that make sense with the field report permissions

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-api#130]
IFRC, Secretariat, and public

**Comment by szabozoltan69** [comment]
The permissions/visibilites are still erroneous somehow.

Maybe somebody (e.g. r.riakov) has permission to create "IFRC" (or "Membership") visibility document but has no permission to see it.

And also a problem that in the admin interface gives a Server Error (500) when we try to search.

**Comment by szabozoltan69** [comment]
Can be useful now: http://jrmcneal.blogspot.com/2013/04/django-listfilter-e1.html

**Comment by szabozoltan69** [comment]
Done via https://github.com/IFRCGo/go-api/issues/130
