### ISSUE TITLE
Add "status" field for Personnel Deployments

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1351]
**Is your feature request related to a problem? Please describe.**

Currently, Deployments have a field called `is_active` which is a boolean and dictates whether an item should be returned in the API or not. If an item is is_active=False, it is never returned in API results. However, there can be multiple reasons where the item is marked is_active=False, and it is useful for admin users to be able to see the reason.

The reasons can be:

 - The item is marked `hidden` on Molnix
 - The item is marked `draft` on Molnix
 - The item has been, for whatever reason, deleted from Molnix.

**Describe the solution you'd like**

The proposal would be to:

 - Add another field called `molnix_status` to the Personnel model - https://github.com/IFRCGo/go-api/blob/develop/deployments/models.py#L202 with 4 allowed values - `active`, `hidden`, `draft` or `deleted`. The default value can be `active`.
 - When ingesting data from Molnix, populate the value of this field with the correct value. This will need to be done here: https://github.com/IFRCGo/go-api/blob/develop/api/management/commands/sync_molnix.py#L187 and here: https://github.com/IFRCGo/go-api/blob/develop/api/management/commands/sync_molnix.py#L246
 - Return all Personnels including is_active=False along-with the `molnix_status` information at a new end-point accessible only to superusers.

cc @tovari @anamariaescobar @szabozoltan69

**Comment by szabozoltan69** [comment]
Deployed to staging environment, can be tested there.
![kép](https://user-images.githubusercontent.com/6050643/157692682-b21f0fa1-bb61-4a4b-8365-513245f3f67a.png)

**Comment by szabozoltan69** [comment]
In case of superuser fetch:
![kép](https://user-images.githubusercontent.com/6050643/157702225-ae96ca28-61a5-4926-842f-693540e3f7c8.png)
Otherwise:
![kép](https://user-images.githubusercontent.com/6050643/157702800-b849ebe9-8be2-4761-b512-8f73af2b2184.png)
