### ISSUE TITLE
Enhancement of Personnel Deployments API and export

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-api#1358]
**Is your feature request related to a problem? Please describe.**
Yes, the information that is being pulled to the export and the API is not useful/clear for the user.

**Describe the solution you'd like**
Clean up the export/API endpoint as per file attached.

[Structure_Personal deployments extract.xlsx](https://github.com/IFRCGo/go-api/files/8253975/Structure_Personal.deployments.extract.xlsx)

Please notice that Molnix tagged are not clustered and therefore you will need to use the categories provided in Sheet2 of the file
Also, for the legacy data (before Molnix integration) please use the mapping provided in Sheet3 to populated Molnix_role_profile and Molnix_sector.

**Where does the data come from and how is it maintained?**
Molnix system.

**Should there be any restrictions around viewing or updating information related to this feature**
Personal information (names) should only be visible when logged in. Molnix_status (why the record is not active) should only be visible for superusers

@batpad @szabozoltan69 do let us know if you think we should have a call around this @ypyelab

**Comment by szabozoltan69** [comment]
Can be checked on staging.

**Comment by szabozoltan69** [comment]
A result:
[result1358.csv](https://github.com/IFRCGo/go-api/files/8318855/result1358.csv)

**Comment by szabozoltan69** [comment]
Fixed column order and column dropping (and column naming can be arbitrary, from now on). Try it on staging:
https://dsgoproxyapp.azurewebsites.net/deployments/personnel/all

**Comment by anamariaescobar** [comment]
Thank you so much for this!

So the order and new names are as following:

1. - [ ] deployment event-deployed-to id --> event_id
2. - [ ] deployment event-deployed-to glide-->event_glide_id
3. - [ ] deployment event-deployed-to name -->event_name
4. - [ ] deployment event-deployed-to ifrc-severity-level --> event_ifrc_severity_level
5. - [ ] disaster-type --> event_disaster_type
6. - [ ] deployment event-deployed-to countries name --> event_country_name
7. - [ ] deployment event-deployed-to countries iso3 --> event_country_iso3
8. - [ ] deployment event-deployed-to countries society-name --> event_country_nationalsociety
9. - [ ] deployment event-deployed-to countries region -->event_country_regionname
10. - [ ] role --> role
11. - [ ] type --> type
12. - [ ] name --> name
13. - [ ] deployedperson-id --> GO_id
14. - [ ] country-to name --> deployed_to_name
15. - [ ] country-to iso3 --> deployed_to_iso3
16. - [ ] country-to society-name --> deployed_to_nationalsociety
17. - [ ] country-to region --> deployed_to_regionname
18.- [ ] country-from name --> deployed_from_name
19. - [ ] country-from iso3 --> deployed_from_iso3
20. - [ ] country-from society-name --> deployed_from_nationalsociety
21. - [ ] country-from region --> region_from_name
22. - [ ] start-date --> start-date
23. - [ ] end-date --> end-date
24. - [ ] ongoing --> ongoing
25. - [ ] is-active --> is_active
26. - [ ] molnix-status --> molnix_status
27. - [ ] molnix-id --> molnix_id
28. - [ ] molnix-sector --> molnix_sector
29. - [ ] molnix-role-profile -->molnix_role_profile
30. - [ ] molnix-language --> molnix_language
31. - [ ] molnix-region --> molnix_region
32. - [ ] molnix-scope --> molnix_scope
33. - [ ] molnix-modality --> molnix_modality
34. - [ ] molnix-operation --> molnix_operation
35. - [ ] inactive-status --> inactive_status

Also, are we going to be able to do the matching of the role profiles with the legacy data?

@szabozoltan69 @ypyelab

**Comment by szabozoltan69** [comment]
The changes are on staging.
https://dsgoproxyapp.azurewebsites.net/deployments/personnel/all
![kép](https://user-images.githubusercontent.com/6050643/159759401-42d6a9b9-a86a-4ba1-80fa-cab87696a474.png)

**Comment by anamariaescobar** [comment]
It's looking really good @szabozoltan69 !! Thank you for this!
