### ISSUE TITLE
Missing district polygon in POL

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1366]
There is no district polygon in POL for the following district:
id: 2380
name: Podkarpackie
code: PL016

The attached shapefile contains the missing polygon. Please add it to the database
[test.zip](https://github.com/IFRCGo/go-api/files/8303382/test.zip)

**Comment by szabozoltan69** [comment]
I tried to run it on staging, but gave some error:
IndexError: Invalid OFT field name given: ADMIN01COD.

Maybe I should adjust something (in the code or on the files)?
The full error message is this: https://pastebin.com/raw/FzVqZpyQ

@batpad ?

**Comment by batpad** [comment]
Will probably need to look at the fields in the shapefile and maybe change them as appropriate.

cc @geohacker @jhenshall

**Comment by szabozoltan69** [comment]
I could do it finally, via a
```
~/go-api/manage.py i /tmp/t/Tester_3_PASSED_area.shp  --import-all --update-geom
```
command, where i points to i.py (copy of import-admin1-data.py), where some variables were fixed:
```
       code = 'PL016' #feature.get('ADMIN01COD')
       name = 'Podkarpackie' #feature.get('ADMIN01NAM')
       country_iso2 = 'PL' #feature.get('ISO2')
       country_name = 'Poland' #feature.get('COUNTRY')
```
So now:
select * from api_districtgeoms where district_id between 2379 and 2381;
![kép](https://user-images.githubusercontent.com/6050643/159002899-ee31635d-cb66-46e9-8d5a-4323be7c85aa.png)

**Comment by szabozoltan69** [comment]
Both staging and prod.

**Comment by batpad** [comment]
We should probably also update the tileset on Mapbox. Though I'd prefer if we not do this on a Friday evening and wait for @geohacker to be back and do this on Monday.

**Comment by batpad** [comment]
@geohacker could we run through to update the mapbox tilesets with the new district added? thanks!

**Comment by geohacker** [comment]
To update the tileset we should do the following in a new VM:
1. Set the Mapbox token
2.`python manage.py update-mapbox-tilesets`

@szabozoltan69 do you want to try this on staging first and ping me if you have any questions?

**Comment by szabozoltan69** [comment]
@geohacker As I remember that job uses a resource-intensive workflow.
There is a stronger vm for it, which is set to use the production database.
(We used it a few times already. If it dies, nothing happens, because not the real staging/prod vm is used.)
Are you sure that we should begin with staging first?
