### ISSUE TITLE
GO frontend updates -  audit trail

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1386]
Currently data updates done on the admin page are tracked. History logs provide information about all changes.
On the other hand updates done on the UI (e.g. FR edit) are not tracked, logs are not available about these changes.

We need to log data updates done on the UI as well. 
First priority is field report track changes.
Second priority 3W project updates.

**Comment by szabozoltan69** [comment]
After the deployment a "./manage.py createinitialrevisions" command will be needed to run, which will needed 20-25 mins.
https://django-reversion.readthedocs.io/en/stable/commands.html#createinitialrevisions

**Comment by tovari** [comment]
Contact info changes are not tracked. Could you please add it?

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-api/blob/develop/api/models.py#L1452-L1453 – added.

**Comment by szabozoltan69** [comment]
The fieldreportcontact table has no it's own admin table on goadmin (just it is joined to fieldreport), but in the revision log it can be followed:
![kép](https://user-images.githubusercontent.com/6050643/170006340-f97ca40a-9b14-4701-921d-1a6129e117b5.png)

**Comment by szabozoltan69** [comment]
Should we create a standalone table view for the field report contacts? In that case way the reversion could be done from goadmin page.
The other option (in case of a change/delete issue) is the database usage, e.g. select * from reversion_version where content_type_id=18; This way we can search (or restore) the changed contact info.

**Comment by tovari** [comment]
FR history works well. 3W project update logging works as well, but can't compare versions on the admin page as it gives an error (500). Try this:
https://dsgocdnapi.azureedge.net/en/deployments/project/2793/history/

**Comment by szabozoltan69** [comment]
I have to add AnnualSplit to the reversion system via a
```
@reversion.register()
class AnnualSplit(models.Model):
```

**Comment by szabozoltan69** [comment]
Locally tested, the comparing works now. Will be deployed ASAP to staging.
![kép](https://user-images.githubusercontent.com/6050643/195387349-28a8417e-0b2e-4887-95a0-fb808289c893.png)

**Comment by szabozoltan69** [comment]
Nice test text though... :-)
