### ISSUE TITLE
Field Report Review

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-api#1397]
**Is your feature request related to a problem? Please describe.**

- Issue created by potential for Field Reports to be issued publicly without vetting for use of approved language and phrasing, according to IFRC humanitarian diplomacy guidelines etc
- Request from management to introduce a step to review and approve Field Reports from selected users / National Societies 

**Describe the solution you'd like**
- Backend admin interface which allows to add selected users or Field Reports associated to certain selected National Societies to require 'sign-off'
- Any FR issued by those selected users / associated to those selected NS to then send an email notification.  If easiest to send this first to IM@ifrc.org to then be forwarded to the person responsible for that region / NS / issue

**Additional context**

- This feature request relates to the inadvertent sensitive Field Report visibility issue encountered referenced [here](https://www.ifrc.org/red-cross-ukraine-your-questions-answered)

**Should there be any restrictions around viewing or updating information related to this feature**

- The users and NS selected for the additional vetting step should only be visible to GO super users

cc @mmusori @tovari

**Comment by tovari** [comment]
Proposed solution would allow users to submit FRs related to specified countries only with IFRC+NS visibility. This will allow IFRC to review the content, while the FR is not visible to other NSs or to not registered site visitors. 
FR visibility could be changed by admins on the admin page.
FR reviewers will need to subscribe to the notifications related to the specific country they review.
