### ISSUE TITLE
[PROD] /docs

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1405]
This error log was found:
```
2022-04-17 09:45:03,412 ERROR Internal Server Error: /docs/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "/usr/local/lib/python3.8/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'NoneType' object has no attribute 'get'

==> /home/ifrc/logs/access.log <==
 - - [17/Apr/2022:09:45:03 +0000] "HEAD /docs/ HTTP/1.0" 500 27 "-" "AppEngine-Google; (+http://code.google.com/appengine; appid: s~virustotalcloud)"
```
Any idea?

**Comment by szabozoltan69** [comment]
Shall we do something with /usr/local/lib/python3.8/site-packages/django/middleware/clickjacking.py? Is it important now?
Maybe @ypyelab – did you work with AppEngine recently?

**Comment by szabozoltan69** [comment]
https://docs.djangoproject.com/en/2.2/ref/clickjacking - clickjacking prevention.

**Comment by thenav56** [comment]
@szabozoltan69 there is a fix mentioned here https://www.django-rest-framework.org/coreapi/from-documenting-your-api/#installation.

**Comment by szabozoltan69** [comment]
It is not clear what kind of fix do you mean @thenav56 . What is the issue to be fixed at all?

**Comment by thenav56** [comment]
> It is not clear what kind of fix do you mean @thenav56 . What is the issue to be fixed at all?

![2022-04-22-122454](https://user-images.githubusercontent.com/7059255/164617961-81bfdeb5-7798-4a41-ac51-308f64b4ece4.png)
