### ISSUE TITLE
[PROD] Django 2.2 to 3.2

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1408]
## Issue
The situation is: https://endoflife.date/django – Django 2.2 (LTS) has reached its end of support.
We should change to 3.2.
@batpad @thenav56 let's make some experiences with this.

**Comment by szabozoltan69** [comment]
I tried this [pyproject.toml](https://pastebin.com/raw/hNmcYwjj) file, but received [this error](https://pastebin.com/76dq2gMV).

**Comment by szabozoltan69** [comment]
In https://pypi.org/project/django-enumfields there was EnumSupportSerializerMixin, but this modul is not supported in Django 3.2 (only until 3.1). How shall we implement [these](https://github.com/IFRCGo/go-api/blob/develop/api/serializers.py#L117) parts in the new world? @thenav56 @batpad

**Comment by thenav56** [comment]
For enum, we can use Django's enum (models.IntegerChoices) directly instead of django-enumfields.

**Comment by szabozoltan69** [comment]
Does Django's enum have serializer support?

**Comment by thenav56** [comment]
Django's enum provides basic choices, so it should work.

**Comment by batpad** [comment]
@szabozoltan69 great work on this. We should definitely aim to wrap this up, test and deploy in this next phase. cc @tovari
