### ISSUE TITLE
[PROD] Log noise cleanup - ALLOWED_HOSTS

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1413]
## Issue
In the docker log I see:
==> logs/logger.log <==
2022-04-21 12:39:35,856 ERROR Invalid HTTP_HOST header: '52.169.X.Y:443'. You may need to add '52.169.X.Y' to ALLOWED_HOSTS.

How should we get rid of these messages? @thenav56 ?
We have in env variables: DJANGO_ADDITIONAL_ALLOWED_HOSTS="api.go.ifrc.org,prddsgocdnapi.azureedge.net"

**Comment by thenav56** [comment]
We can update the Nginx config to only allow the domains which are in DJANGO_ADDTIONAL_ALLOWED_HOSTS using **server_name**, that way the request will not be forwarded to Django from Nginx.

**Comment by szabozoltan69** [comment]
Any ideas about what exactly to write to https://github.com/IFRCGo/go-api/blob/develop/main/nginx.conf#L29 ?

**Comment by szabozoltan69** [comment]
Still wrong.
```
2022-04-23 11:29:39,706 ERROR Invalid HTTP_HOST header: '52.169.X.Y:443'. You may need to add '52.169.X.Y' to ALLOWED_HOSTS.
```

**Comment by szabozoltan69** [comment]
We use DJANGO_ADDITIONAL_ALLOWED_HOSTS, but in the documentation there is only ALLOWED_HOSTS – https://docs.djangoproject.com/en/2.2/ref/settings
```
~/go-api# env|grep ALL
DJANGO_ADDITIONAL_ALLOWED_HOSTS=api.go.ifrc.org,prddsgocdnapi.azureedge.net
```

**Comment by thenav56** [comment]
@szabozoltan69 Can you share the active Nginx config (in production after all the sed changes) after the fix?

NOTE: T think we are using DJANGO_ADDITIONAL_ALLOWED_HOSTS for Django only.

**Comment by szabozoltan69** [comment]
Ok. (I've sent config to you)
Then maybe we should use (or convert to) ALLOWED_HOSTS also.

**Comment by szabozoltan69** [comment]
@thenav56 Thanks for the help, now this is solved fine.
