### ISSUE TITLE
Add existing appeal files

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-api#143]
There is a manifest of appeal files and where they currently exist that we need to make available to the front-end.

https://docs.google.com/spreadsheets/d/1gJ4N_PYBqtwVuJ10d8zXWxQle_i84vDx5dHNBomYWdU/edit#gid=0

@matthewhanson let's talk about this tomorrow.

**Comment by matthewhanson** [comment]
- Does this spreadsheet continually change...does it need to be ingested once or periodically?

- Do the documents need to be ingested and stored, or just the links?

- Does the meta ID correspond to a current Appeals ID?

**Comment by dereklieu** [comment]
cc @guipizzini ^
