### ISSUE TITLE
Add GZip Middleware for API responses

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1459]
We should add the gzip middleware to gzip all responses from the API.

cc @szabozoltan69 @frozenhelium @tovari

**Comment by szabozoltan69** [comment]
So mainly django.middleware.gzip.GZipMiddleware has to be added to https://github.com/IFRCGo/go-api/blob/develop/main/settings.py#L188-L200
The https://docs.djangoproject.com/en/3.2/ref/middleware/ contains some warnings and guidelines about this.
