### ISSUE TITLE
Appeal List search parameter "real_data_update"

### ISSUE THREAD

**Issue by toffehoff** [IFRCGo/go-api#1463]
When calling the /api/v2/appeal/ endpoint, one of the fields that is returned is "real_data_update". I assume this is the timestamp when the data in this record was last changed. 

If I want to get all the appeals that have been updated in the last 24 hours. I currently need to download every appeal and check if the "real_data_update" field is within the 24H or not. There is no parameter which I can use to only request appeals recently changed.
Now I need to run through hundreds and hundreds of appeals to filter out only a handful. This just takes up unnecessary resources every time I do this call. 

**Change request:**
- Add the "real_data_update" as a parameter to the /api/v2/appeal/ endpoint.

Absolute need is to be able to request "all appeals that have been update since date xxxx"
Additional (but no immediate need from my end) would be a request to ask "all appeals that have NOT been change since date xxxxx".

**Comment by szabozoltan69** [comment]
I think there is no promise for that if an appeal gets funds a few days ago, it appears at once in appeal api (and in GO api). There is a one-month liberty for the finance team to document the changes.

**Comment by szabozoltan69** [comment]
We should rethink the /api/v2/appeal/ endpoint anyway.
Recently on Prod we have [this kind of error](https://porgeto.hu/tmp/appeal.txt).

**Comment by toffehoff** [comment]
> I think there is no promise for that if an appeal gets funds a few days ago, it appears at once in appeal api (and in GO api). There is a one-month liberty for the finance team to document the changes.

Not sure if my comment was understood correct. I'm ok with the current "real_data_update" field. The issue is that I can't filter on this field in my request. Maybe I'm doing something wrong. If that is the case: can you please give me the API URL with which I can get only the appeal records which have been updated in the last 2 days. (where real_data_update >= now-2)

**Comment by szabozoltan69** [comment]
You are OK, there is (still) not such API endpoint (for date search). I am working on it.
(My comment concerned only to the fact that those change dates are not always sharp.)

**Comment by szabozoltan69** [comment]
An example: 
![kép](https://user-images.githubusercontent.com/6050643/176436684-f9362865-87aa-4a22-ad52-4f4fca950c27.png)

**Comment by szabozoltan69** [comment]
You can test the API on https://dsgocdnapi.azureedge.net/docs/#api-v2-appeal-list or directly via e.g.
https://dsgocdnapi.azureedge.net/api/v2/appeal/?appeal__real_data_update__gt=2022-03-03T00:00:00

**Comment by toffehoff** [comment]
I've done a few tests and I haven't found any issues in the dsgocdnapi environment (great!). However, in production I see there are some records in which the value for "real_data_update" is null; for example appeal code MDRCF027. I assume this is not correct.

**Comment by szabozoltan69** [comment]
Thanks for the feedback! (This change is not yet deployed to production, nevertheless the real_data_update can't be null, it's true.)
I'll investigate it.

**Comment by szabozoltan69** [comment]
I've found a comment in the code:
https://github.com/IFRCGo/go-api/blob/develop/api/management/commands/triggers_to_db.py#L46
"We update real_data_update time only if important figures has been changed". In this example appeal there were no changes yet (and the contribution amount is 0). So, my suggestion is: to use creation date (on client side), when real_data_update is null.
Historically: this appeal was closed befor the real_data_update concept was lead in.
