### ISSUE TITLE
Document access control

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1479]
Currently, uploaded pdf documents are stored on a blob storage, which is publicly accessible. We store here even those documents that should have limited visibility. In case the document url gets shared somehow, the document visibility cannot be applied anymore.
Eg, this pdf is only available for the Movement on GO, but anyone can open the link:
https://prddsgofilestorage.blob.core.windows.net/api/sitreps/5854/Multisectoral_Needs_Analysis_Report_Hungary-_June_2022.pdf

**Comment by tovari** [comment]
@batpad suggests:
[08/07 13:50] sanjaybhangar (Guest)
    
I think we'd need to use this Shared Access Signature thing for Azure Blob Storage: https://stackoverflow.com/questions/55233010/azure-blob-storage-pre-signed-url-features

    And then make the storage private, and the application would need to generate a temporary signed URL that the user can use to download the resource.
<https://teams.microsoft.com/l/message/19:2a2bceca1320427a88e7c93eb68bd352@thread.skype/1657281050681?tenantId=a2b53be5-734e-4e6c-ab0d-d184f60fd917&amp;groupId=be22b1e3-23ec-4ddd-80cd-dc7ab032d2eb&amp;parentMessageId=1657273547555&amp;teamName=GO - Public channel&amp;channelName=Developers&amp;createdTime=1657281050681>

**Comment by nanometrenat** [comment]
Xref historic issue https://github.com/IFRCGo/go-frontend/issues/926

**Comment by szabozoltan69** [comment]
Closed due to duplication.
