### ISSUE TITLE
Pakistan admin1 update

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1523]
We need to update the admin1 areas in PAK, first on staging and after a test on prod.
Existing areas should be preserved as well if possible as deprecated areas.

New areas:
[PAK.zip](https://github.com/IFRCGo/go-api/files/9596231/PAK.zip)

**Comment by tovari** [comment]
Zoltan's error:
IndexError: Invalid OFT field name given: ADMIN01COD

**Comment by geohacker** [comment]
Thanks for the ticket @tovari and for looking into this @szabozoltan69! The shapefile above is a bit different from what's accepted by the import scripts. We use the ICRC column names for the shapefile. The required ones are: `ADMIN01COD`, `'ADMIN01NAM'`, `'ISO2'`, `'COUNTRY'`. I'll update the docs with a sample of this shortly.

I fixed the shapefile and got @jhenshall's help with the admin codes — we are using the code from OCHA to be a bit consistent. 


@szabozoltan69 could you run this on staging? 
[PAK-edited-2022.zip](https://github.com/IFRCGo/go-api/files/9596521/PAK-edited-2022.zip)

There will be two steps:
1. Run `python manage.py import-admin1-data PAK-Admin1-2022.shp`
2. Then inspect the `missing-districts.txt` file
3. And if it shows 7 new districts, run `python manage.py import-admin1-data PAK-Admin1-2022.shp --import-missing missing-districts.txt`

**Comment by szabozoltan69** [comment]
Success!

```
~/go-api/manage.py import-admin1-data PAK-Admin1-2022.shp
will write missing district codes to missing-districts.txt
done!
#  cat missing-districts.txt 
code,name
PK2,Balochistan
PK7,Sindh
PK3,Gilgit-Baltistan
PK1,Azad Kashmir
PK5,Khyber Pakhtunkhwa
PK6,Punjab
PK4,Islamabad Capital Territory

# ~/go-api/manage.py  import-admin1-data PAK-Admin1-2022.shp --import-missing missing-districts.txt
will import these codes dict_keys(['PK2', 'PK7', 'PK3', 'PK1', 'PK5', 'PK6', 'PK4'])
importing Balochistan
importing Sindh
importing Gilgit-Baltistan
importing Azad Kashmir
importing Khyber Pakhtunkhwa
importing Punjab
importing Islamabad Capital Territory
done!
```

**Comment by szabozoltan69** [comment]
Now I was running 
```
manage.py import-admin1-data PAK-Admin1-2022.shp --update-geom --update-bbox --update-centroid 
```
and after that the map-tiling. (The above command did not give missing districts of course, because they got in previously.)
