### ISSUE TITLE
Create a /healthcheck endpoint

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-api#1528]
Should we add a /healthcheck endpoint and the following:

```
{
  'status': 'success',
  'version': #backend version
}
```

Makes it easier to figure out what version is deployed and then debug.
cc @batpad @szabozoltan69 @frozenhelium @thenav56

**Comment by szabozoltan69** [comment]
Done, 
/api/v2/brief  (including elasticserach health check)
![kép](https://user-images.githubusercontent.com/6050643/221200164-6401edee-75dd-44f3-b7b4-968b532631fa.png)

**Comment by szabozoltan69** [comment]
The "brief healthcheck endpoint" is deployed to Staging.
Can be checked via https://dsgocdnapi.azureedge.net/api/v2/brief
(A more detailed /healthcheck can be planned for later – if needed – even via a [dashboard](https://medium.com/@appseed.us/django-dashboards-open-source-and-free-projects-1d8e64919e6d)).)
