### ISSUE TITLE
Standardize validation errors returned by the backend

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1532]
For forms like the 3W form, we use DRF classes to handle serializing and saving data. This lets us leverage DRF's standardized error reporting, and DRF then returns validation errors in a standardized format: https://www.django-rest-framework.org/api-guide/exceptions/#validationerror

For some forms, we don't use DRF views / serializers to save the data, and there error reporting does not follow the DRF conventions. This adds a lot of work to the frontend to deal with multiple non-standard ways of representing validation errors from the backend.

We should standardize / ensure all backend validation error responses for form saving follows the DRF format for representing errors and correctly return a `400` status code.

TODO:

  - @frozenhelium to help enumerate all forms where the backend does not return errors in the standard format
  - Then, @thenav56 and @szabozoltan69 can work together to ensure they all return errors in the DRF format, ideally by converting those views to use DRF serializers.

cc @tovari @tnagorra

**Comment by szabozoltan69** [comment]
@batpad @thenav56 Should we rewrite this? https://github.com/IFRCGo/go-api/blob/develop/api/exceptions.py#L4-L8

**Comment by szabozoltan69** [comment]
Also https://github.com/IFRCGo/go-api/pull/1715 lessons learned should be canalized to this solution.
So: login, FR, account profile data changes should handle backend errors like this:
```
'errors': {
     'non_field_errors': ['Hey, we are in maintenance mode, come back a bit later – site is in read only mode']
}
```

**Comment by szabozoltan69** [comment]
Solved via web-rewrite
