### ISSUE TITLE
DREF automated emails

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-api#1538]
**Is your feature request related to a problem? Please describe.**
An user doesn't know when he/she needs to review a DREF application.

**Describe the solution you'd like**
We need an email to be trigger once a user gets added to a DREF request, the email should contain the following text: "You have been added to a DREF Application "DREF Tittle" (with an hyperlink to the application.

@szabozoltan69

**Comment by szabozoltan69** [comment]
Should be done similar to this: https://github.com/IFRCGo/go-api/blob/develop/flash_update/tasks.py#L47-L64

**Comment by szabozoltan69** [comment]
On Staging already working, can be tested.

![kép](https://user-images.githubusercontent.com/6050643/193398181-8f24b7bb-5406-47c1-8c2c-1712dd076e32.png)

**Comment by anamariaescobar** [comment]
Tested and working correctly from my side! Thanks @szabozoltan69

**Comment by szabozoltan69** [comment]
Recently every single save generates an email, which is bad.
We should record that "for that DREF already these received email, no more to them, but only the new people".
So a table with user_id + dref_id ( + sent-date) would be fine for that purpose.

**Comment by anamariaescobar** [comment]
Tested and working just as expected in staging!! Thanks @szabozoltan69
