### ISSUE TITLE
[Staging] DREF sending, celery error log

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1543]
## Issue
In case of saving a DREF we can see this in celery error log:
https://porgeto.hu/tmp/celeryErrors.txt

It seems to be that this code part fail on not having the 'request' key in self.contect array (3 times), when called the DrefSerializer (via IdentifiedNeedSerializer:)
```
    def get_image_url(self, identifiedneed):
        request = self.context['request']
```
I mean:
https://github.com/IFRCGo/go-api/blob/develop/dref/serializers.py#L194-L195
https://github.com/IFRCGo/go-api/blob/develop/dref/serializers.py#L216-L217
https://github.com/IFRCGo/go-api/blob/develop/dref/serializers.py#L238-L239

How to fix that? Maybe the celery-started task does not contain this self.context['request'] element (due to that is not an http request), opposed to the Django-driven run?

@thenav56 ? Any ideas ?

**Comment by szabozoltan69** [comment]
I'll put a condition, if 'request' in self.context.

**Comment by thenav56** [comment]
All looks good. Thanks for the quick fix.
