### ISSUE TITLE
Setup Sentry for error logging and debugging

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1569]
Previously https://github.com/IFRCGo/go-api/issues/672

As discussed in the above ticket, we should setup an instance of `Sentry` to collect logs and stack traces, and allow for an improved debugging experience.

For this we would need:

 - A new VM to host Sentry on.
    - [x] [VM specification](https://github.com/getsentry/self-hosted/tree/22.10.0#requirements):
        - 4 CPU Cores
        - 8 GB RAM
        - 30 GB Free Disk Space  ( ~ F4s_v2)
    - [x] Static IP + domain (eg: go-sentry@ifrc.org)
    - [x] Firewall
        - Open ports: 443, 80, 22
    - [x] Email SMTP credentials (For sending alerts to developers using emails)
        - with SSL support.
    - [x] Docker, Docker-compose
 - [x] Setup Sentry on new VM, document steps. (cc @szabozoltan69 @thenav56 )
     - Pull repo
     ```bash
     # Clone
     Clone sentry self-hosted repo
     gt clone https://github.com/getsentry/self-hosted.git sentry
     cd sentry

     # Switch to the latest version (https://github.com/getsentry/self-hosted/releases)
     git switch -c 23.1.0

     # Sentry install script
     ./install.sh --no-report-self-hosted-issues
     ```
     - Configure (sentry/config.yml)
         Example for email config
         ```yml
         mail.host: 'smtp.example.com'
         mail.port: 465
         mail.username: '<username-here>'
         mail.password: '<password-here>
         mail.use-tls: false
         mail.use-ssl: true
         ```
         - Use `docker-compose restart web worker cron sentry-cleanup` in the future if this is updated.
     - Configure .env.custom
         - `cp .env .env.custom`
         - Update .env.custom as required.
         - Use `docker-compose --env-file /home/azureuser/app/sentry/.env.custom up -d` in the future if this is updated.
     - Start containers
         ```bash
         docker-compose --env-file /home/azureuser/app/sentry/.env.custom up -d
         ```

 - [x] Configure django backend to send error logs to Sentry. Should we also setup the Risk Module to send logs to the same Sentry instance? Maybe even the frontend?
    - [ ] go-frontend
    - [x] go-api
    - [ ] risk-module
 - [x] Test that this works on staging, deploy

cc @tovari 

**Links to documentation**
[Sentry vs Logging](https://sentry.io/vs/logging/)
[Full Stack Monitoring](https://sentry.io/for/full-stack/)
[Self-host Sentry](https://develop.sentry.dev/self-hosted/)

**Comment by thenav56** [comment]
@batpad Sorry about the delay. I have updated the issue description.

**Comment by batpad** [comment]
@thenav56 thank you! This looks great!

Do you think it's possible to use a smaller VM? Say 2 cores with 4GB RAM?

**Comment by thenav56** [comment]
@batpad Not sure. Looking at the instance we are running, the RAM usage is always full but for cpu the spikes are only for manual updates.
![image](https://user-images.githubusercontent.com/7059255/200741249-090adaad-5dd5-47a3-a45e-2cafb73fb283.png)

**Comment by batpad** [comment]
Yea, it's likely taking all available RAM but my hunch is should be fine with less.

I also don't think 4 CPUs and 8GB RAM is too much of an ask.

@szabozoltan69 so, what I'd say is:

If it does seem like people will not be happy / not approve the larger box, then it is OK to go with 2 CPU + 4GB RAM, but it would be preferrable to just get 4CPU + 8GB RAM. The Sentry github also specifies this as system requirements, so I would highly recommend to just go with the 4CPU + 8GB RAM: https://github.com/getsentry/self-hosted#requirements

I really think GO has been quite conservative so far in the size of VMs, etc. - hopefully it's fine to get this box to hangle our logs and debugging.

**Comment by szabozoltan69** [comment]
Thanks for the info, @thenav56 and @batpad – I try to push overt the 4+8 version (F4s_v2 on Azure).

**Comment by szabozoltan69** [comment]
The infra team suggested series D instead of a series F machine.
The argument: all (strong) machines in IFRC are from series D (d2sv3 or d4sv3).
So I create a vm like this.

**Comment by szabozoltan69** [comment]
![kép](https://user-images.githubusercontent.com/6050643/213430989-7cdecdd9-37df-423e-a496-828a5010c3f1.png)

**Comment by szabozoltan69** [comment]
![kép](https://user-images.githubusercontent.com/6050643/213469257-d43d2943-190f-42e7-bfc9-ab04da342ff9.png)

**Comment by szabozoltan69** [comment]
Remained tasks:
Email sending to work, then new users invite will be working. (No other way to add users.)
_For connecting to the services we need to have to expose sentry instance using ... ports.
Sentry main container will expose to ... port, we need to setup a proxy server with HTTPS support to expose it to ... ports._

**Comment by szabozoltan69** [comment]
The first (not nice) email was delivered.
Sender should be nicer:
![kép](https://user-images.githubusercontent.com/6050643/213702086-4f680c84-a605-47fd-8f99-644f4dbf3b6f.png)

**Comment by szabozoltan69** [comment]
Thanks to @thenav56 – the changes are deployed to Staging and are fully functional.
Also the Sentry web page is nice and reachable in a "normal manner", without giving port numbers.
One task remained: all these for prod (and maybe for local) environments.

**Comment by szabozoltan69** [comment]
Maybe https://github.com/ehlo-io/ehlo could be something to consider. SMTP -> MailService API

**Comment by szabozoltan69** [comment]
Somehow this container exits:
```
sentry-self-hosted_geoipupdate_1                                /usr/bin/geoipupdate -d /s ...   Exit 1 
 ```
 due to
 ```
error loading configuration file /sentry/GeoIP.conf: error opening file: open /sentry/GeoIP.conf: no such file or directory
```

**Comment by szabozoltan69** [comment]
"Official" IFRC SMTP server usage done.
