### ISSUE TITLE
[PROD] 404 in endpoint redirect to login page.

### ISSUE THREAD

**Issue by thenav56** [IFRCGo/go-api#1594]
## Issue
*Currently there is a issue where all 404 errors are redirected to **/en/{url}** for a given **url**. This is also redirect next to the admin login page.*

## Steps to reproduce
*Goto into region endpoint with non-existing id.
`curl -isL https://goadmin.ifrc.org/api/v2/region/123123/`*

![2022-11-25-103448](https://user-images.githubusercontent.com/7059255/203903479-b8bbd9fe-885a-469d-86ee-2980ab2c9ac0.png)

## Expected behavior
*Respond with DRF standard 404 response.*

## Severity
*This affects the error handling on the front end side.*

## NOTE
Maybe this is related to https://code.djangoproject.com/ticket/17734

**Comment by szabozoltan69** [comment]
Nice catch!
Could be reproduced locally also.
The source of this redirection (to /en/... ) is not yet found.

**Comment by szabozoltan69** [comment]
If I set this variable from True to False, this bug disappears. But then it is not possible to change the language of the admin page:
https://github.com/IFRCGo/go-api/blob/develop/main/urls.py#L245

**Comment by szabozoltan69** [comment]
This way the bug is solved. So we should somehow subclass this !!! part in 
/usr/local/lib/python3.8/site-packages/django/middleware/locale.py :

 ```
from django.utils.deprecation import MiddlewareMixin


class LocaleMiddleware(MiddlewareMixin):
    """
    Parse a request and decide what translation object to install in the
    current thread context. This allows pages to be dynamically translated to
    the language the user desires (if the language is available).
    """
    response_redirect_class = HttpResponseRedirect

    def process_request(self, request):
        urlconf = getattr(request, 'urlconf', settings.ROOT_URLCONF)
        i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
        language = translation.get_language_from_request(request, check_path=i18n_patterns_used)
        language_from_path = translation.get_language_from_path(request.path_info)
        if not language_from_path and i18n_patterns_used and not prefixed_default_language:
            language = settings.LANGUAGE_CODE
        translation.activate(language)
        request.LANGUAGE_CODE = translation.get_language()

    def process_response(self, request, response):
        language = translation.get_language()
        language_from_path = translation.get_language_from_path(request.path_info)
        urlconf = getattr(request, 'urlconf', settings.ROOT_URLCONF)
        i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)

            # !!!
        if (False and response.status_code == 404 and not language_from_path and
                i18n_patterns_used and prefixed_default_language):
...
```

**Comment by szabozoltan69** [comment]
Found the solution.
In settings.py we have to define the newly defined entity, so the above part can go to the end of middlewares/middlewares.py, and in settings.py:
```
MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    #'django.middleware.locale.LocaleMiddleware',  !!!!!!!!!!!!!!!!!!!!!!!!
    'middlewares.middlewares.LocaleMiddleware',  !!!!!!!!!!!!!!!!!!!!!!!!!
...]
```

**Comment by szabozoltan69** [comment]
(Finally I did not change the not-using-/admin in the URL, @batpad )

**Comment by szabozoltan69** [comment]
Also DREF pages feel this issue.
If somebody tries to look at a DREF application without enough permission, we see this:
![image](https://github.com/IFRCGo/go-api/assets/6050643/63049ed6-ba22-4fc1-a755-6977a5c4dbdf)
But the backend uses redirects for this:
![image](https://github.com/IFRCGo/go-api/assets/6050643/d88d4a8c-c07c-4a95-bb2a-1cbbf3716996)
Let's fix this.

**Comment by szabozoltan69** [comment]
Deployed to staging (both backend and frontend).
