### ISSUE TITLE
Aggregate not grouping by year

### ISSUE THREAD

**Issue by danielfdsilva** [IFRCGo/go-api#160]
The query `http://dsgocdnapi.azureedge.net/api/v1/aggregate/?start_date=1990-01-01&model_type=appeal&unit=year` is not returning data aggregated by the specified unit.
Instead is aggregating by month.
```
{
  "aggregate": [
    {
      "count": 6,
      "timespan": "2017-02-01T00:00:00Z"
    },
    {
      "count": 9,
      "timespan": "2017-03-01T00:00:00Z"
    },
    {
      "count": 11,
      "timespan": "2017-04-01T00:00:00Z"
    },
    // ...
  ]
}
```

**Comment by dereklieu** [comment]
@danielfdsilva weird, I'm getting what looks like a proper response. [url](https://dsgocdnapi.azureedge.net/api/v1/aggregate/?start_date=1990-01-01&model_type=appeal&unit=year).

<img width="358" alt="screen shot 2018-01-11 at 7 14 24 pm" src="https://user-images.githubusercontent.com/1590802/34822988-c2fdb1e0-f703-11e7-85d6-dea8e5acc6ed.png">

**Comment by danielfdsilva** [comment]
@dereklieu just tried again. I even went incognito to ensure a clean slate. Clicked on your link
<img width="353" alt="image" src="https://user-images.githubusercontent.com/1090606/34823128-3a05f092-f6c1-11e7-8c97-a2935fa165ff.png">

**Comment by danielfdsilva** [comment]
Turns out it was a CDN cache issue. Closing
