### ISSUE TITLE
Country plans pdf api import

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1614]
Country plan public pdf documents can be accessed through an api.

https://go-api.ifrc.org/api/publicsiteappeals?AppealsTypeID=1851&Hidden=false
The api response _BaseDirectory_ and _BaseFileName_ values can be used to compose the document url.
The _Inserted_ date value (e.g. 2022-11-29T11:24:00) can be used to track if it is a new one.

It would be great to check every day the available country plan documents and update the pdfs, when a new version is available.
_Insterted_ date could be used to check the available update.

I would still keep the manual update functionality, but the daily import may update the document during the next run.

In case a new document gets imported, the country plan page should be automatically published.

**Comment by szabozoltan69** [comment]
The ingest_appeals.py uses similar structure. Could be integrated into it?

**Comment by tovari** [comment]
No need an hourly update. Once a day is more than enough :)
