### ISSUE TITLE
Admin page - Wiki - add hook points to Country plans

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1619]
Admin guide to country plans are published here:
https://go-wiki.ifrc.org/en/admin_guide/country_plans

Please add the ? help icon to the url at the admin pages at 
https://goadmin.ifrc.org/en/country_plan/
https://goadmin.ifrc.org/en/country_plan/countryplan/
https://goadmin.ifrc.org/en/country_plan/dataimport/

**Comment by szabozoltan69** [comment]
The last time a similar task was solved via https://github.com/IFRCGo/go-api/commit/8b4b49af4

**Comment by szabozoltan69** [comment]
For the subpages it is obvious where to place the question mark.
But for the root of Country Plan "app" there is no such existing example (in other "apps").
Which one would be nicer and more expressive? @tovari @LukeCaley 
![kép](https://user-images.githubusercontent.com/6050643/208694699-4c4b219a-7e45-4e4c-8408-d8e4f4f5ad64.png)

**Comment by tovari** [comment]
To keep it consistent, I would put it to the right.

**Comment by szabozoltan69** [comment]
Deployed to Staging.
