### ISSUE TITLE
API pagination issue

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1636]
There might be a generic issue on the api pagination. Using the series of limited api result queries, the api result contains multiple duplicated items. 

Affected endpoints (identified so far):
https://goadmin.ifrc.org/api/v2/event/?
https://goadmin.ifrc.org/api/v2/personnel/?

The list of duplicated items are reproduceable. The list of duplicated items are attached. In case of the _event_ endpoint, one of the duplicate pairs is on the 49th or 50th item on the page, the other one is somewhere on the following page.
In case of the _event_ endpoint, there are only 18 duplicates, however on the _personnel_ endpoint, there are over 350.
The number of queried items are correct (e.g. 1193 in case of _personnel_), but due to the duplicated items, there are missing items from the query result list. I attached the list of missing item list of the _personnel_ endpoint.
There is no issue, in case all results are queried at once, i.e. with _?limit=10000_ parameter.

[Event-api-duplicates.csv](https://github.com/IFRCGo/go-api/files/10426835/Event-api-duplicates.csv)
[Surge Deployments-duplicated_items.csv](https://github.com/IFRCGo/go-api/files/10426836/Surge.Deployments-duplicated_items.csv)
[Surge Deployments-missing_items.csv](https://github.com/IFRCGo/go-api/files/10426837/Surge.Deployments-missing_items.csv)

cc: @ypyelab, @JonathanGarro

**Comment by szabozoltan69** [comment]
I could reproduce it locally also.

**Comment by batpad** [comment]
So one recommendation / thing to check would be to make sure that all the queries have an explicit `order_by` clause -- either on the Model or when fetching the queryset.

@szabozoltan69 let me know when around and we can try a few things - am hoping it's just this that's the issue, otherwise this seems really strange :-( .

**Comment by szabozoltan69** [comment]
@batpad I am around. I think you are right, the order_by clause is not present in Django code (only at a very few locations). I'll try to put there locally and test it...

**Comment by szabozoltan69** [comment]
I have a bit of doubt about the fact that these duplications are "real duplications", not just a collections of some joined table rows which has a connection to each other (e.g. field report or event or other). Anyway, if the result shows duplications, we have to fix them.

**Comment by oliverroick** [comment]
I'm pretty confident that this has to do with the ordering. In Django, records aren't ordered by default. While there is usually some order in query sets (usually the reverse insert order in a table, newest records first), you can't rely on that order in query sets. I've encountered the same issue before and it was always the ordering that led to duplicates in query sets.

I would try what @batpad suggested or set the [`ordering` on the model](https://docs.djangoproject.com/en/4.1/ref/models/options/#ordering).

**Comment by szabozoltan69** [comment]
Yes, it is the clue, thanks for both.
A short demo. r1, r2 are results 'before putting the id to the ordering', R1, R2 are results after.
Then:
```
grep 'Belize - Partial State of Emergency - Drought - Northern, central and western regions' ??
r1:      "name": "Belize - Partial State of Emergency - Drought - Northern, central and western regions"
R1:      "name": "Belize - Partial State of Emergency - Drought - Northern, central and western regions"
r2:      "name": "Belize - Partial State of Emergency - Drought - Northern, central and western regions"
```

**Comment by szabozoltan69** [comment]
Deployed to Staging.
