### ISSUE TITLE
Changes / fixes to Local Units implementation

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1647]
Some minor things that would be good to fix / improve with the implementation for Local Units:

 - Add a `__str__` method to ensure it shows up nicely in the Admin -- maybe can be something like `local_branch_name` + `country.name` or so?
 - Allow filtering in the API. One should be able to filter by `country` ISO code and `type`. We can consider other filters, including geospatial, later.

@szabozoltan69 anything else you can think of that can be improved with the local units import? Should we open another ticket about error handling in the CSV import script?

@willemarcel do you think you'd be able to take on the filtering in the API and the `__str__` method to have a nice display name in the admin list?

**Comment by szabozoltan69** [comment]
Just one comment: the .csv file should not contain BOM character as start (otherwise the reader does not find the ISO3 column, as it is found as ¤ISO3).

**Comment by szabozoltan69** [comment]
Deployed to Staging
