### ISSUE TITLE
Add Country_iso3 parameter to district and appeal endpoints 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1672]
Please add an optional parameter to the `district` and `appeal` endpoints that allows to query on iso3 codes of countries.

**Comment by szabozoltan69** [comment]
Deployed to Staging. Test it: 
https://dsgocdnapi.azureedge.net/api/v2/appeal/?country__iso3=SYR
https://dsgocdnapi.azureedge.net/api/v2/district/?country__iso3=SYR
