### ISSUE TITLE
3W project sector and tag lists should be in the database

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1693]
3W projects related Sector and Tag lists are currently wired to the code. We should be able to edit these, so would be great to have them as editable lists on the admin page.

Similarly what we have for Emergency 3W sectors and actions:
https://goadmin.ifrc.org/en/deployments/emergencyprojectactivityaction/
https://goadmin.ifrc.org/en/deployments/emergencyprojectactivitysector/

**Comment by szabozoltan69** [comment]
Some great achevements are done (e.g. tricky migrations), but some basic things are missing.
E.g the /api/v2/project/  does not contain primary_sector_display and secondary_sector_display (only primary_sector and secondary_sector, which is not enough). I think some serializer change is missing.
Temporarily I switched off some tests (not all though).
@thenav56 @batpad some review would be highly appreciated.
