### ISSUE TITLE
3W Project notification email - wrong urls in the links

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1694]
New 3W project notification emails contains incorrect links:
[https://https//go.ifrc.org/three-w/2494/](https://https/go.ifrc.org/three-w/2494/)  See the double https// in the url.

![image](https://user-images.githubusercontent.com/68283148/222099549-c127fada-c544-46a0-aa40-61fb5ff2ab52.png)

**Comment by szabozoltan69** [comment]
Could reproduce locally.
