### ISSUE TITLE
[PROD] 3W project view - Partner NS name appears incorrectly at the project country

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1695]
The reporting NS country appears at the Country incorrectly. The provinces are correct, only the country name is wrong.

E.g. this project happens in Philippines, done by the Netherlands RC:

https://goadmin.ifrc.org/en/deployments/project/2494/change/

The country of project should be Philippines, not Netherlands:
https://go.ifrc.org/three-w/2494/
![image](https://user-images.githubusercontent.com/68283148/222103217-3f3d4003-81c0-4e0d-8697-712650fe881b.png)

**Comment by szabozoltan69** [comment]
Done. Locally:
![kép](https://user-images.githubusercontent.com/6050643/222125911-60b3b39c-03c0-4e85-ac16-081ad4f77125.png)
Will be deployed to Staging asap.

**Comment by szabozoltan69** [comment]
Deployed to Staging.
