### ISSUE TITLE
Emergencies should have glide number

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-api#170]

**Comment by dereklieu** [comment]
@guipizzini @renecnielsen does this number currently exist anywhere? What is the format for this number? (all numerals, or alpha-numeric, for example?)

**Comment by renecnielsen** [comment]
From http://glidenumber.net/glide/public/about.jsp.

> The components of a GLIDE number consist of two letters to identify the disaster type (e.g. EQ - earthquake); the year of the disaster; a six-digit, sequential disaster number; and the three-letter ISO code for country of occurrence. So, for example, the GLIDE number for West-India Earthquake in India is: EQ-2001-000033-IND.

We, as IFRC, or other humanitarian partners generate these numbers on glidenumber.net when a new disaster occurs. It is not uniformly used, but is the only viable global diaster identifier available.
