### ISSUE TITLE
[PROD] New elasticsearch requirements pollute testing

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1700]
## Issue
In api/receivers.py there is a @receiver(pre_save) part. If I leave it uncommented during test time, all the unit test entities are tried to be saved to elasticsearch index database. This spams the output of testing strongly.
Some avoidance would be necessary (to avoid the comment/uncomment phase). CircleCI of course does not comment anything, just shows the plenty of unnecessary rows, like
```
ERROR    api:receivers.py:171 Failed to index a Country, error: ('1 document(s) failed to index.', [{'create': {'_index':
```
Like this:
![kép](https://user-images.githubusercontent.com/6050643/223461718-526b9d2f-e823-418e-9f5c-d6017bbb14cf.png)

**Comment by thenav56** [comment]
This is resolved. Can you confirm @szabozoltan69 ?

**Comment by szabozoltan69** [comment]
Yes, @thenav56 – correct.
