### ISSUE TITLE
PPP dashboard integration to the 3W page

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1704]
We need to publish the PPP dashboard on GO.

it will be published on the Global 3W page under the map.
https://go.ifrc.org/three-w/

<p><iframe src="https://public.tableau.com/views/PPPdashboard_DRAFT/1_OVERVIEW?:language=en-US&amp;:display_count=n&amp;:origin=viz_share_link?:embed=yes&amp;:display_count=yes&amp;:showVizHome=no&amp;:toolbar=yes" width="1050" height="800" frameborder="0"> </iframe></p>

Title above the dashboard: _to be added_
Short description below the title: _to be added_

**Comment by szabozoltan69** [comment]
Is it ok with this layout?
![kép](https://user-images.githubusercontent.com/6050643/223978250-b876e10b-fd67-405d-85b1-2fc434bcce3d.png)

**Comment by tovari** [comment]
Thanks Zoli. Please implement rather the 'gloabl 3W Response' type title and description above the dashboard:
![image](https://user-images.githubusercontent.com/68283148/223983987-280bf616-49af-4226-8bd1-e620b65f0810.png)

Also, please adjust the dashboard width to the size of the map.

**Comment by szabozoltan69** [comment]
The dashboard size is not changeable, unfortunately. Even if we change the inner width, height value, it remains the same. So I centered it. The latest version is:

![kép](https://user-images.githubusercontent.com/6050643/224009143-bb05287b-e96f-4412-87e9-b011b609a4b4.png)

**Comment by szabozoltan69** [comment]
Deployed to Staging
