### ISSUE TITLE
Emergency projects - Additional attributes on the admin page list

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1705]
List of the 3W activities (emergency projects) shows only the title of the activity, which makes difficult to find the specific activities:
https://dsgocdnapi.azureedge.net/en/deployments/emergencyproject/

Please add the following attributes to the list:
- event name
- country
- reporting NS

**Comment by szabozoltan69** [comment]
Deployed to Staging.
![kép](https://user-images.githubusercontent.com/6050643/225019806-6bc26840-dd47-4e2e-9461-fd3f5c2f230d.png)
