### ISSUE TITLE
Add more info to appeals document list in admin

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-api#173]
> To better find the appeal one is looking for, the list should at least have Code + Name + Start Date. E.g.: Column 1: “2017-10-23”, column 2: “MDRBD018”, column 3: “Bangladesh - Population Movement”. Currently only Code is listed.

**Comment by renecnielsen** [comment]
This is a general wish in the Admin. More columns makes it much easier to find what one is looking for. I believe Django also supports column filtering out of the box?
