### ISSUE TITLE
Add sitrep upload form to emergency, aka event objects

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-api#174]

**Comment by renecnielsen** [comment]
If thatøs the easiest solution, then fine by me. But if possible, simply add it to the Emergency, not the Field Report.

**Comment by dereklieu** [comment]
cc @matthewhanson situation reports are files that should be similar to the `AppealDocument` model in `api/models`. They should have a foreign key to emergency objects.

**Comment by dereklieu** [comment]
Done #178
