### ISSUE TITLE
Appeal documents import through API

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1754]
At the moment, appeal documents are scraped from the https://www.ifrc.org/appeals?date_from=&date_to=&type%5B%5D=2&appeal_code=&text=
page. 
There is an API as well to import these documents: https://go-api.ifrc.org/api/publicsiteappeals?AppealsTypeID=

We can fetch more meta information about each documents through the api, which will allow us to display more info on the emergency page Reports tab as well as will provide data to improve the search function on documents.

cc: @batpad, @thenav56

**Comment by szabozoltan69** [comment]
Location, appeal type, orig type (as description?), date should be read.
Fields are from:
```
<PublicSiteAppeal>
<APP_OST_Code>S353ID1</APP_OST_Code>
<AppealFlag>5</AppealFlag>
<AppealNumber>M....002</AppealNumber>
<AppealOrigType>IFRC Network Plan 2023 for .....</AppealOrigType>
<AppealsDate>2023-01-01T00:00:00</AppealsDate>
<AppealsId>1304052</AppealsId>
<AppealsName>INP_2023_In... (M...002)</AppealsName>
<AppealsTypeId>1851</AppealsTypeId>
<BaseAppealNumber>M....002</BaseAppealNumber>
<BaseDirectory>https://adore.ifrc.org/...?FileId=</BaseDirectory>
<BaseFileName>60...</BaseFileName>
<Hidden>false</Hidden>
<Inserted>2022-11-29T11:24:00</Inserted>
<LocationCountryCode>ID</LocationCountryCode>
<LocationCountryName>In...</LocationCountryName>
<LocationRegionCode>S3</LocationRegionCode>
<LocationRegionName>Asia Pacific</LocationRegionName>
<Updated i:nil="true"/>
</PublicSiteAppeal>
```

**Comment by szabozoltan69** [comment]
Deployed to Staging.
Can be run manually (not in cronjob), because this job just adds plus attributes to the existing (ingested) appealdocuments.

**Comment by szabozoltan69** [comment]
Please test frontend changes on https://go-stage.ifrc.org/emergencies/4422#reports
