### ISSUE TITLE
Related object does not exist when modifying user profile

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-api#176]
<img width="690" alt="screen shot 2018-01-15 at 5 10 37 pm" src="https://user-images.githubusercontent.com/1590802/34934904-0b12e9e4-fa17-11e7-834b-5e32907e08a6.png">

@guipizzini @renecnielsen I haven't seen this before. Can you go list the steps to reproduce it, and also include what browser and operating system you're using?

**Comment by guipizzini** [comment]
@dereklieu will be easier, to take this over a quick call. Using Mac OS Sierra (10.2) with Google Chrome Version 63

**Comment by dereklieu** [comment]
@guipizzini does Tuesday January 23 morning (ET) work for you?

**Comment by guipizzini** [comment]
@dereklieu awesome. Just send me the meeting invite at the best time for you. Thanks

**Comment by guipizzini** [comment]
@dereklieu we get the same error in other parts of the site, will give details in bilateral
