### ISSUE TITLE
[Staging] Update fixtures

### ISSUE THREAD

**Issue by bewakes** [IFRCGo/go-api#1761]
## Issue
* While setting up the project for the first time, I cannot select countries in the Field Report form even after running `docker-compose run --rm loaddata`. The countries are loaded from the api but not displayed in the dropdown. Turns out that the countries require `iso3` and `is_independent` value to be set as Yes. 

## Steps to reproduce
Run the project form the scratch, following the instructions on the repo.

## Expected behaviour
Countries to be loaded in Field report form.

## Related feature
None

## Criticality/Urgency
Not critical. But saves time for new contributors.

**Comment by szabozoltan69** [comment]
Good notice!
As a quick help please write me to gmail (same username as here) and I send you a starter database dump with filled-in basics.

**Comment by szabozoltan69** [comment]
I think country.ISO3 can be null, but not blank. (At least recently there are some null-s even in Prod, but also on Staging.)
Thanks for this great work, it will be really nice to be able to start off without any extra dependency (to db-dump).

**Comment by szabozoltan69** [comment]
Please wait a bit with country fixture change, I also will change it (in order to have ISO unique).

**Comment by szabozoltan69** [comment]
Yes, it's a new constraint by me (needed for the new-style appealdoc ingesting).
Sorry for that.
I try to create a json via a dumpdata, but removing superfluous (and disputable) data.

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-api/pull/1763 creates a new country fixture json.

**Comment by bewakes** [comment]
Yes, but there is still issue with loading districts: `country with pk 229 does not exist`.

**Comment by szabozoltan69** [comment]
Merged to develop and deployed to Staging.
