### ISSUE TITLE
Migrate backend API to new deploy infrastructure

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1771]
Leading on from #1531:

We now have the new setup using Azure Pipelines to push to an AKS cluster working on staging. One can access the staging backend at https://goadmin-stage.ifrc.org

This ticket is to create a check-list and plan to move production over to the new setup.

Things we will need to do (ideally this week):

 - [x] Setup the new production cluster on Azure, add all required secrets, env vars, etc.
 - [x] Uncomment code in the azure pipeline and terraform to enable deploying to a prod cluster on pushes to `main` or so.
 - [x] Push and deploy to the new production cluster
 - [x] Load in a dump of the production database to test with (this is NOT the final dump we will use when we migrate)
 - [x] Point a test domain name to the new production cluster and test that everything works as expected
 - [x] Give the cluster a day or two in this "testing" state, monitor CronJob logs, etc.

Final push to production (ideally next week?):
 - [x] Create the to-be database. Check if terraform-prod contains master, terraform develop branch.
 - [x] Inform users a few days before of a ~2 hour maintenance window on the website.
 - [x] Put the site into "Read-Only" mode.
 - [x] Take a dump of the current production database and load it into the database for the new cluster
 - [x] Set domain name on the cluster to expect goadmin.ifrc.org (and api.go.ifrc.org) to be pointed at it
 - [x] Move DNS: point goadmin.ifrc.org (and api.go.ifrc.org) to the new cluster

@geohacker if there's relevant details of resources we need to create in Azure or anything for the new production cluster, could you please either edit this ticket or add comments?

I **think** this should roughly be it - let's talk soon to figure out setting up the new cluster and testing everything on it.

cc @geohacker @szabozoltan69 @tovari

**Comment by geohacker** [comment]
@batpad this sounds good to me. Can't think of anything that's not captured above. I think there may be small things to get through as we standup the prod stack but all should be ok.

**Comment by szabozoltan69** [comment]
Maybe also a "how to wire in Sentry" can be a task also.

**Comment by szabozoltan69** [comment]
This morning we moved the GO Backend to new infrastructure on Azure.
