### ISSUE TITLE
[PROD] Today's date is not today's in api query

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1774]
## Issue
We should investigate, how can be the below api query, given on 2023-05-03:
curl https://goadmin.ifrc.org/api/v2/personnel_by_event/6357/
...result such an SQL query on Prod, having 2023-04-30 dates as date limit:
```
select
	"api_event"."id",
	"api_event"."name",
	COUNT("deployments_personnel"."deployedperson_ptr_id") filter (
	where (("deployments_deployedperson"."end_date" at TIME zone 'UTC')::date >= '2023-04-30'::date
		and "deployments_personnel"."is_active"
		and ("deployments_deployedperson"."start_date" at TIME zone 'UTC')::date <= '2023-04-30'::date
			and "deployments_personnel"."type" = 'rr')) as "personnel_count"
from
	"api_event"
left outer join "deployments_personneldeployment" on
	("api_event"."id" = "deployments_personneldeployment"."event_deployed_to_id")
left outer join "deployments_personnel" on
	("deployments_personneldeployment"."id" = "deployments_personnel"."deployment_id")
left outer join "deployments_deployedperson" on
	("deployments_personnel"."deployedperson_ptr_id" = "deployments_deployedperson"."id")
where
	"api_event"."id" = 6357
group by
	"api_event"."id"
having
	COUNT("deployments_personnel"."deployedperson_ptr_id") filter (
	where (("deployments_deployedperson"."end_date" at TIME zone 'UTC')::date >= '2023-04-30'::date
		and "deployments_personnel"."is_active"
		and ("deployments_deployedperson"."start_date" at TIME zone 'UTC')::date <= '2023-04-30'::date
			and "deployments_personnel"."type" = 'rr')) > 0
limit 21;
```
While the code of this DeploymentsByEventViewset: https://github.com/IFRCGo/go-api/blob/develop/api/drf_views.py#L134 uses "today".

**Comment by szabozoltan69** [comment]
The method I used:
In a not too crowded time I switched on Azure SQL logging via setting log_statement to ALL, then gave a "sign" query from SQL Editor:
select 'ppppppppppppppppppppppppppppppppp1';
Then I called the API call above, then again 
select 'ppppppppppppppppppppppppppppppppp2';
Then switched logging off (by setting that variable to none).
In the log file it was easy to find the query location, and it was 100% sure that not today's date was used in the SQL select.

**Comment by szabozoltan69** [comment]
@anamariaescobar @batpad @thenav56

**Comment by szabozoltan69** [comment]
Even on 2023-05-04 the situation was the same.
But after a production stand-down and restart (docker-compose down, docker-compose up -d) the result became the awaited one: no result for 6357 event (because those deployments do not cover today).
So some kind of caching can happen in the late running Django system. :-(

**Comment by batpad** [comment]
Wow, nice catch @szabozoltan69 .

So my hunch is that the Viewset Classes get evaluated just when django starts and not per-request. I thought this only applied to models.py

I **think** the solution here would be to move the `queryset = ` into a method called `get_queryset` which sets `today` inside that method and then returns the queryset, instead of making these class properties.

@thenav56 does that sound about right?

**Comment by thenav56** [comment]
Yes, the `today` is defined on the application start which will remain the same until the application is restarted. Let's use get_queryset instead as @batpad mentioned.

**Comment by szabozoltan69** [comment]
Oh, greaaaat!!!
What secrets you know, folks... :-D

**Comment by szabozoltan69** [comment]
Local tests of this #1776 fix work fine.

**Comment by szabozoltan69** [comment]
Deployed to Staging.
