### ISSUE TITLE
[PROD] filter/search not loading in Projects in goadmin

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#1801]
## Issue
*Please describe your issue clearly and concisely. If possible, include when you first encountered the issue, who it affects, a link to a relevant page, and any other information that might be helpful in diagnosing its cause.*

When looking in the back end for projects/3Ws (https://goadmin.ifrc.org/en/deployments/project/) the "By National Society" and "By Country" filters don't load any options, so I can't filter by one country/NS on this screen.  Get "The results could not be loaded" every time I try.

Trying to filter for Sudan response.

![image](https://github.com/IFRCGo/go-api/assets/33625192/2fb55749-f064-4d29-a0c2-784998cefe77)

## Steps to reproduce
Go to https://goadmin.ifrc.org/en/deployments/project/ and click the filter dropdown

## Workaround
Only workaround is to directly query the API rather than the UI.

**Comment by k9845** [comment]
Addressed in PR https://github.com/IFRCGo/go-api/pull/1802
 Seems like there is an issue with `django-auto-complete-filter`, for now, updated with `django-admin-list-filter-dropdown`

**Comment by szabozoltan69** [comment]
Deployed to Staging, works fine – now a hotfix will be deployed to Prod.

**Comment by szabozoltan69** [comment]
Deployed to Prod.

**Comment by szabozoltan69** [comment]
Only @tovari closes the issue, please put the status (right side up) to Ready for UAT, @k9845
