### ISSUE TITLE
[PROD] TinyMCE – rich text editor, pasted images

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1804]
## Issue
Instead of Base64 format "pasted images" we should solve real image file uploads to our server.
Based on this: https://www.tiny.cloud/docs/general-configuration-guide/upload-images/
This can be also helpful: https://dev.to/zankoan/upload-local-imagevideo-in-django-tinymce-text-editor-mkn

Local images that are added through other means are also uploaded using this function, such as images added by drag and drop when using the [paste_data_images](https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_data_images) configuration property, or using the Tiny [PowerPaste plugin](https://www.tiny.cloud/docs/plugins/premium/powerpaste/).

Unfortunately:
https://www.tiny.cloud/docs/plugins/premium/powerpaste/
This plugin is only available for paid TinyMCE subscriptions. (min 37.5 USD / month)
But via this: https://gist.github.com/AshishPandagre/c6a3b0f5ff4724ed5d29b4ff347828f4 maybe we can do it either.

**Comment by szabozoltan69** [comment]
Dear @thenav56 @batpad @k9845 –
I have some progress in this topic.
My issue is: this https://gist.github.com/AshishPandagre/c6a3b0f5ff4724ed5d29b4ff347828f4#file-app_views-py - row 7, csfr_exempt seems to be not working.
For local test I can make a hack via:
cd /usr/local/lib/python3.8/site-packages/rest_framework; vi authentication.py
And putting a return to    def enforce_csrf(self, request), but for a real solution we should be able to define a better short-circuit of CSRF for this image upload function.

This way I have some images which were upload via copy-and-paste:
```
root@d166c262ed84:~/go-api/media/tinymce# ls -l
-rw-r--r--  1 root root  627 Jun 21 08:31 blobid0.png
-rw-r--r--  1 root root  561 Jun 21 08:37 blobid1.png
-rw-r--r--  1 root root  808 Jun 21 09:05 blobid2.png
-rw-r--r--  1 root root 2117 Jun 21 09:06 blobid3.png
```
Please check [the PR ](https://github.com/IFRCGo/go-api/pull/1828) if you have time.

**Comment by szabozoltan69** [comment]
@batpad @thenav56 if you have any idea about this ^ – I would highly appreciate it.

**Comment by batpad** [comment]
TinyMCE docs on handling image uploads: https://www.tiny.cloud/docs/tinymce/latest/file-image-upload/#example-using-images_upload_handler

**Comment by szabozoltan69** [comment]
The direction: let's not allow image pasting (or inserting), users should use the other "official" image upload options.
