### ISSUE TITLE
Add additional RRMS fields to surge alert and deployment tables

### ISSUE THREAD

**Issue by JonathanGarro** [IFRCGo/go-api#1814]
As referenced on the 2023-06-14 call, there are additional fields we need to add to these tables in order to meet the surge team's requirements for a visualization on the GO Platform reflecting various KPIs and common queries. Most of the data we need is already available, save for a few additions: 

1. Funding: Type = str
2. Contract_Type: Type = str
3. Location: Type = str (this will refer to the city and country where the person deploys)
4. Gender: Type = str
5. Appraisal_Received = boolean

**Comment by batpad** [comment]
1, 2, 3 should be for Alerts - 4,5 for Deployments.

Next steps: @batpad checks current API from Molnix and if these fields exist - then just need to add them to GO and make sure they are imported.

We can discuss backfill once we have code working to ingest current data.

**Comment by anamariaescobar** [comment]
looping @alicefahey into this ticket

**Comment by batpad** [comment]
@JonathanGarro I'm not seeing these fields in the API responses for either `deployments` or `open positions`. The only field of the above that I see is `contract_id` and `contract` in the response for Deployments, though I've not been able to find an example in the staging data where `contract` is not NULL.

I think next steps here:

 - If you can point out to me where in the Staging Molnix UI these things appear, I can do some inspecting and try and figure out what API endpoint they are coming from.
 - It might be useful to get on a call and explore the network requests and API together to figure out which endpoints to get this data from.
 - For `contract`, if we do want the contract information for Deployments, it would be useful to have an example with actual data to see what that looks like.

**Comment by JonathanGarro** [comment]
Hey @batpad - Sure thing. In the staging site, when you look at the Deployments tab and drill down to a single deployment, the Funding and Contract fields appear:

![Screen Shot 2023-07-24 at 09 12 06 AM](https://github.com/IFRCGo/go-api/assets/8890661/5c8bbcbc-d353-423f-b471-8fabb8d63327)

For location, its a separate object that I'm guessing is associated via a deployment ID? Here's what it looks like on the front end: 

![Screen Shot 2023-07-24 at 09 13 09 AM](https://github.com/IFRCGo/go-api/assets/8890661/d3470e3b-8277-4063-a68e-f9d33b35a231)

Ditto the Appraisals - I think that might require a bit of filtering logic as it includes a few different attachment types, so we'd need to just set a boolean to `True` if `attachment_type` (or whatever it's called) `== 'Appraisal'`

![Screen Shot 2023-07-24 at 09 14 04 AM](https://github.com/IFRCGo/go-api/assets/8890661/b44406f2-cd46-48b5-ab78-63a6e7819a5e)

**Comment by batpad** [comment]
Had a good chat with Vishnu from Molnix, and seems clear now:

> Funding: Type = str
> Contract_Type: Type = str

These will come through when we import Tag Groups, so will be covered by #1813 

> Location: Type = str (this will refer to the city and country where the person deploys)

Available in deployments api as `contact.addresses[0].city`

> Gender: Type = str

Available in deployments API as `person.sex`

> Appraisal_Received = boolean

Appraisal information is available in the `attachments` array on the Deployment API. Appraisals are attachments where `type` = `appraisal`. So if there exists an attachment where type=appraisal, `appraisal_received` would be True. Also, we should add another field called `appraisal_score` and populate it with `attachments[type=appraisal].score` . This field should be private, so not available in the public API for deployments.

**Comment by batpad** [comment]
Currently, we need to fetch two of the above values by fetching the Deployment Detail endpoint, i.e. something like `/api/api/deployments/93`, whereas the rest of the data is all available at the `deployments` LIST endpoint. These are:

`contact.addresses` - on the deployments LIST endpoint, there exists a key called `contact`, but `contact.addresses` is only available on the deployment DETAIL endpoint.

`attachments` - we need the `attachments` data to get information about the `appraisal` status (see above). `attachments` is currently only available on the deployment DETAIL endpoint, and not on the LIST endpoint.

If both these data-points were available in the deployments LIST endpoint, it would save us having to make an additional request for every deployment.

Checking with the Molnix developers if this is an acceptable change on the Molnix side, else we can just make the extra requests on our end.

**Comment by szabozoltan69** [comment]
@JonathanGarro this change is on Go Staging, please test it when appropriate.
