### ISSUE TITLE
Appeal documents additional attributes on the admin page

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1824]
Appeal documents list only shows the appeal document title at the moment, which makes difficult to search and identify documents as many have the same title:
https://goadmin.ifrc.org/en/admin/api/appealdocument/

Please add the following attributes to the listed documents:
- description
- location 
- creation date

Description and location should be searchable as well.

**Comment by szabozoltan69** [comment]
Looks like this, searchable for the entities mentioned:
![kép](https://github.com/IFRCGo/go-api/assets/6050643/1444a066-8f49-4ecf-9be4-352725526153)
