### ISSUE TITLE
[PROD] DREF Final Report Admin pages taking too long to load

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1888]
## Issue

The DREF Final Report Admin pages are taking too long to load, often timing out even after 6 minutes, which is the timeout configured on our web server.

This would be any of the reports here: https://goadmin-stage.ifrc.org/en/admin/dref/dreffinalreport/

## Steps to reproduce

On production, a few of the DREF reports reliably fail. On staging, something like this https://goadmin-stage.ifrc.org/en/admin/dref/dreffinalreport/67/change/ does not fail, but does take a long time to load.

My hunch is this could be caused by a bunch of those `<select>` drop-downs that contain a lot of entities - users, Images -- all the relationship entities - we output the entire result set here for all related entities and my hunch is this could be a problem. This is a relatively common problem with the default behaviour of the Django admin for entities with related fields that have a lot of items.

It does seem related to the amount of data on the page, but am having a hard time telling for sure what the root cause is. @szabozoltan69 is working on getting more details of the SQL executed on the page. My strong hunch is it's all the related entities and the `select`s on the page.

cc @thenav56 @udaynwa - this would be great if you all could take a look - happy to chat about it at any point.

## Expected behaviour

DREF Final Report pages on admin should load smoothly.

cc @anamariaescobar @szabozoltan69 @geohacker @tovari

**Comment by szabozoltan69** [comment]
An ending of a psql log concerning an Admin view of a Final Report (locally):
https://porgeto.hu/tmp/fr0824.txt

**Comment by thenav56** [comment]
@batpad @szabozoltan69 
Thanks for the detail ticket.
Checking the code, we have missed some Foreign fields.
We will work on this. cc: @k9845 @udaynwa

**Comment by szabozoltan69** [comment]
Now on Staging it's much faster the load of final reports, e.g. https://goadmin-stage.ifrc.org/en/admin/dref/dreffinalreport/64/change/
So I merge it to Prod.
@batpad @thenav56  @k9845

**Comment by szabozoltan69** [comment]
Now DREF Final Reports open fine in GO Prod Admin, e.g. from https://goadmin.ifrc.org/en/admin/dref/dreffinalreport/ 
(Not lightning-fast, but they do.)

**Comment by anamariaescobar** [comment]
Thank you for all the work! but is not only the Final reports, the Ops Update and Application are experiencing the same issue, check this one: https://goadmin.ifrc.org/en/admin/dref/drefoperationalupdate/92/change/, we might want to to fixes to those also.
@szabozoltan69 @batpad @thenav56 @k9845

**Comment by szabozoltan69** [comment]
Fix is deployed to prod, works fine for https://goadmin.ifrc.org/en/admin/dref/drefoperationalupdate/92/change/ also.
