### ISSUE TITLE
ERU - 2 new types to be added, update text on CoS

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1929]
1.  Please add the following 2 new ERU types to the list on Prod and Stage
![image](https://github.com/IFRCGo/go-api/assets/68283148/348c840b-d971-49a1-8881-77539707169d)

- Outpatient Department (OPD) Module
- MHPSS

2. Please rename PSS to MHPSS in the Catalogue of Services here on Stage:
https://go.ifrc.org/deployments/catalogue/health/eru-pss-module

**Comment by szabozoltan69** [comment]
Request 1 is done (Staging and Prod).

**Comment by tovari** [comment]
frontend is also fixed
