### ISSUE TITLE
Add new surge alert filters to API

### ISSUE THREAD

**Issue by JonathanGarro** [IFRCGo/go-api#1975]
We added a bunch of surge alert fields earlier this year from RRMS. I'm hoping we can make those accessible via the API for end users like myself. Per the [documentation](https://goadmin.ifrc.org/docs/#tag/api/operation/api_v2_surge_alert_list), it looks like there are several missing from what we added (as well as some that I believe were already there), including: 

- `start` (as well as `start__gt`, `__gte`, `__lt`, `__lte`)
- `molnix_status`
- `message`
- `country`
- `molnix_tags` - these have the new "groups" key that contain a bunch of keys i'd love to have access to, such as `ROLES`, `LANGUAGE`, `SECTOR`, `rotation`, etc.

**Comment by szabozoltan69** [comment]
Ok, so we should append the needed fields to the filterset, to this:
https://github.com/IFRCGo/go-api/blob/develop/notifications/drf_views.py#L23_L26

**Comment by szabozoltan69** [comment]
Is it ok if I add these?
molnix_id, molnix_status, start, message, country

**Comment by JonathanGarro** [comment]
is it possible to have it filter those molnix_tags too? or is the structure too complex?

**Comment by batpad** [comment]
FYI: Renamed the title of this ticket to "Add new surge alert **filters** to API" instead of "Add new surge alert fields to API" to make the requirement a bit clearer.

**Comment by szabozoltan69** [comment]
Also in docs:
![kép](https://github.com/IFRCGo/go-api/assets/6050643/8d82c30d-9a49-4b0d-b916-648233daec2f)

**Comment by szabozoltan69** [comment]
Deployed to Staging.
Many thanks to @thenav56 for the great cleanup!

**Comment by szabozoltan69** [comment]
https://goadmin-stage.ifrc.org/api/v2/surge_alert/?country__iso3__in=HND,HUN&molnix_tag_names=LOGS,COM,LOG-CO

**Comment by JonathanGarro** [comment]
thanks @tovari - i just tested a few and it seems to work great! huge thanks to the team, this will be extremely useful! i appreciate y'all.
