### ISSUE TITLE
Documents titles on emergency pages should not be translated

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#2043]
Currently, the automated translation service translates the title of the uploaded documents (e.g. Situation reports) on the emergency pages. This might be misleading to users, because the document itself doesn't get translated. 
To avoid this, the following emergency page sections should be not translated:
- Situation report section: any type of document `title`
- Event featured documents:` title` and `description`

**Comment by thenav56** [comment]
@tovari Can you share an example for this?
