### ISSUE TITLE
Clean Emergency page translations

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#2048]
We would like to clean the emergencies languages and provide dynamic translations for the historic data.
The attached xlsx lists those emergency IDs that needs some batch action.
Actions to be done per worksheet:
Emerg (UI- En, summ. - Fr) - copy `Summary [en]`,` Title [en]` fields content to `summary [fr]` and `Title [fr]`, then change the `Entity original language` to French. Initiate translation. - 40 items

Emerg (UI- En, summ.- Es) - copy Summary [en], Title [en] fields content to summary [es] and Title [es], then change the Entity original language to Spanish. Initiate translation. - 104 items

Emerg (UI- Es, summ.- En) -  Initiate translation. - 424 items
[Summary_emergencies-to_be_translated-v3.xlsx](https://github.com/IFRCGo/go-api/files/14332287/Summary_emergencies-to_be_translated-v3.xlsx)

**Comment by udaynwa** [comment]
Hey @szabozoltan69 . Here is a draft PR to run manual translation. Let me know if any additional information is required.
https://github.com/IFRCGo/go-api/pull/2149

**Comment by szabozoltan69** [comment]
Some clarification and usage hints would be highly appreciated.

**Comment by szabozoltan69** [comment]
Could you give some hints @thenav56 how to continue this task?

**Comment by thenav56** [comment]
Hey @szabozoltan69, I hope this helps. Here is the pseudo code we will need for this:

```python
from lang.tasks import ModelTranslator
from main.translation import TRANSLATOR_SKIP_FIELD_NAME, TRANSLATOR_ORIGINAL_LANGUAGE_FIELD_NAME

from api.models import Event

def en_to_fr():
    pks = [...]  # List of primary keys -- Or read the content from an xlsx file instead?
    events = Event.objects.filter(
        pk__in=pks,
        **{TRANSLATOR_SKIP_FIELD_NAME: False},
    )

    print('Translating EN->FR')
    for event in events:
        assert getattr(event, TRANSLATOR_ORIGINAL_LANGUAGE_FIELD_NAME) == 'en'

        # TODO: Should we read the content from an xlsx file instead?
        event.name_fr = event.name_en
        event.summary_fr = event.summary_en
        ...

        # Clear the original English fields - Auto translator will only fill empty fields
        event.name_en = ''
        event.summary_en = ''
        ...

        # Change the original language to French
        setattr(event, TRANSLATOR_ORIGINAL_LANGUAGE_FIELD_NAME, 'fr')

        # Save the new state (Use update_fields= if required)
        event.save()

        # Translate fields dynamically and save the object
        ModelTranslator().translate_model_fields(event)
        print('- Translated successfully:', event.pk)

en_to_fr()
en_to_es()
es_to_en()
```

This code will translate event fields from English to French and save the changes. Similar functions can be created for other language translations.

**Comment by szabozoltan69** [comment]
What do you think about collecting to-be-translated ID-s this way, instead of the obsolate xlsx file?
- select id from api_event where summary_en = summary_es and summary_en !=''
- select id from api_event where summary_en = summary_fr and summary_en !=''

**Comment by szabozoltan69** [comment]
I check visually the in-xlsx id-s and the newly found ones via:```
select
substring(regexp_replace(summary_en, E'<[^>]+>', '', 'gi'),0,80) as en,
substring(regexp_replace(summary_fr, E'<[^>]+>', '', 'gi'),0,80) as fr from api_event where id in 
(3143,3106,3180,3173,3166,3145,3244,5084,5670,6171,6118,6125,6138,
6135,6139,6193,6156,6144,6208,6207,6241,6250,6252,6303,6282,6293,6298,
6310,6356,6375,6380,6385,6423,6421,6440,6462,6504,6746,6734,6842)
or id in (select id from api_event where summary_en like '% dans %' or summary_en like '% et %');
```

**Comment by szabozoltan69** [comment]
Task done, some unsuccessful ones from scope 3:
```
Unsuccessful: 6671
Unsuccessful: 6589
Unsuccessful: 6559
Unsuccessful: 6455
```
– they will be fixed manually later.

**Comment by szabozoltan69** [comment]
I could use the above pseudocode fine, with a small change, allowing to continue the loop in case of error also:
```
        # Translate fields dynamically and save the object
        try:
            ModelTranslator().translate_model_fields(event)
            print('- Translated successfully:', event.pk)
        except:
            print('Unsuccessful:', event.pk)
```
