### ISSUE TITLE
[PROD] Surge alerts not pulling through to GO - ?missing country data?

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#2055]
## Issue
Today there have been two surge alerts that have been published on RRMS but haven't yet appeared on GO platform several hours later.  I am advised by @tovari that that's because they don't have valid country data.

This is what shows on GO right now:
<img width="937" alt="image" src="https://github.com/IFRCGo/go-api/assets/33625192/08732011-e706-46dc-952d-d1b8218f4452">

The alerts that are missing from GO are:

- Humanitarian Info Analyst:  https://rrms.ifrc.org/positions/show/2894 Rapid Response Global (A): IM- Humanitarian Information Analysis Officer, Droughts, Colombia. | Associated positions:  Humanitarian Info Analysis Officer, Droughts, Colombia

- NS Capacity Strengthening:  https://rrms.ifrc.org/positions/show/2895 Rapid Response Global (A): NS Response Capacity Strengthening Coordinator, Middle East Crisis, MENA | Associated positions:  NS Response Capacity Strengthening Coordinator, Middle East Crisis, MENA

DT needs to figure out the plan with @anamariaescobar and @szabozoltan69 re what to do in the scenario where incoming data from RRMS is incomplete.

**Comment by nanometrenat** [comment]
FYI the SIMS Slack availability channel pulls from the GO API - so currently the HIA alert isn't showing in SIMS Slack either.  Tagging @JonathanGarro for info re the HIA one as it's not pulled through to GO for the above reason.  The Health IM one *IS* on GO so not sure why that one's not pulling to Slack - presumably a different reason.  CHEERS.

**Comment by szabozoltan69** [comment]
In https://goadmin.ifrc.org/en/admin/api/cronjob/281430/ I see that:
Position id 2894 does not have a valid Country
Position id 2895 does not have a valid Country
– that is the reason that they do not arrive to GO.

**Comment by nanometrenat** [comment]
Hi @tovari wondering why this is closed?  Was a change made to sort this?  I still can't see a surge person against the Colombia operation

**Comment by tovari** [comment]
Surge team added the missing tags to all the reported alerts, so those were resolved. We cannot do much on this on GO side at the moment, just report the missing data attributes to the Surge team. 
We need to find out a solution with Surge team to better monitor, detect and resolve these issues.
