### ISSUE TITLE
NS Overview > Context and Structure: Email ID in NS Local Units map should not be URLs

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-api#2080]
## Task description
- The email IDs in the NS Local Units map section are currently URLs. It should be directed to emails
- Also, please check how the emails are separated and handled when there are more than one email IDs

### Link 
- https://go-stage.ifrc.org/countries/18/ns-overview/context-and-structure

**Comment by samshara** [comment]
@k9845 Let's split the email addresses by the `,` or `;` separator if they are present in the email strings
