### ISSUE TITLE
[PROD] Surge Alert and deployment email notifications

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#2171]
GO doesn't send out new Surge Alert and Deployment notification emails for a while:
https://goadmin.ifrc.org/en/admin/notifications/notificationguid/?o=-2&q=surge+alert
https://goadmin.ifrc.org/en/admin/notifications/notificationguid/?q=deployment&o=-2

**Comment by szabozoltan69** [comment]
As a beginning I made a statistics about the subscribed [content types](https://github.com/IFRCGo/go-api/blob/develop/notifications/models.py#L117-L128).
```
     3 |   855
     4 |  1936
     5 |  2241
     6 |  8275
     7 |    95
     8 |  2818
     9 |   594
    10 |   178
    11 |   518
    12 |   687
    13 |   638
    14 |   427
```

**Comment by szabozoltan69** [comment]
It turned out that with a 2023-09-06 commit we disabled temporarily SURGE_ALERT and SURGE_DEPLOYMENT notifications, due to historical data upload:
https://github.com/IFRCGo/go-api/commit/2622a3bcc7defbb8ca52338762d1cf0cf9bc7e66
