### ISSUE TITLE
[PROD] PER typo "exits" should be "exists"

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#2178]
## Issue
Across the PER module, the wording "exits could be strengthened" shows in a number of places - but it should be "exists" not "exits".

<img width="468" alt="image" src="https://github.com/IFRCGo/go-api/assets/33625192/60daa71d-cbec-41e5-9250-8b49a3007f37">

I am not sure if changing this in [the code](https://github.com/search?q=exits+repo%3AIFRCGo%2Fgo-api+&type=code) is sufficient or if there are also changes that would need to be made under the hood in the database etc to ensure that everything stays aligned?

## Steps to reproduce
Example page in staging:  https://go-stage.ifrc.org/countries/19/ns-overview/per/160

## Expected behaviour
Typo should be fixed

## Impact
Cosmetic issue only - not affecting actual functionality

**Comment by szabozoltan69** [comment]
Changed on Admin on [Staging](https://goadmin-stage.ifrc.org/en/admin/per/percomponentrating/5/change/) and [Prod](https://goadmin.ifrc.org/en/admin/per/percomponentrating/5/change/), but will be delivered via migration also.
