### ISSUE TITLE
Lock during db sync

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-api#22]
Initial sync can take a bit of time and we don't want to start another sync before the first has finished.

**Comment by dereklieu** [comment]
@matthewhanson Update syncs seem pretty fast. Not sure this is necessary for this phase. Do you agree? At minimum I think it should be pushed to a later task than sprint 2.

**Comment by matthewhanson** [comment]
Yeah, not needed right now @dereklieu
