### ISSUE TITLE
Pretty url for the Monty api

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#2215]
We need a pretty url for the Monty API.
currently it is:
http://montandon.westeurope.cloudapp.azure.com:8000/
docs:
http://montandon.westeurope.cloudapp.azure.com:8000/__docs__/

The proposed new url:
monty-api.ifrc.org

We also need to redirect the legacy url calls to the new url.

cc: @hamishwp, @justinginnetti

**Comment by szabozoltan69** [comment]
The CNAME record is created by IT team.
The port is not redirected (should be done on the VM we use).
Recently http://monty-api.ifrc.org:8000/ can be used (appending the needed strings).
