### ISSUE TITLE
Migrate CircleCI tests to Github Actions

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-api#2243]
## TODO 
- [ ] Ensure the tests passes before each deployment https://github.com/IFRCGo/go-api/blob/develop/.github/workflows/build-publish-docker-helm.yaml

@szabozoltan69 @batpad @tovari

**Comment by thenav56** [comment]
Let's use https://github.com/IFRCGo/go-api/issues/2249 to track
