### ISSUE TITLE
Migrate Tests to GitHub Actions and Ensure CI/CD Integration

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-api#2249]
Tasks
- [x] Migrate Tests to GitHub Actions from CircleCI 
- [x] Remove CircleCI dependencies
- [x] Enforce Test Completion Before Building and Pushing Docker Images and Helm Charts https://github.com/IFRCGo/go-api/blob/develop/.github/workflows/build-publish-docker-helm.yaml

**Comment by thenav56** [comment]
This is done
