### ISSUE TITLE
User Profiles

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-api#225]
When going in the Django Framework to the "User Profiles" there is no search functionality.

This means that if a user was registered long time ago, you cannot filter or search for the user which makes it really not user friendly to update the profile.

Image below as a reference:

<img width="1236" alt="screen shot 2018-03-15 at 21 31 38" src="https://user-images.githubusercontent.com/23258092/37484094-99f948ec-2898-11e8-901a-4f0d73e47eaf.png">

For the future, it would be great to have on the frontend under the account page of the user the possibility for the user itself to update his profile.

**Comment by dereklieu** [comment]
Profiles have search functionality.
