### ISSUE TITLE
Scrape ICRC Website for Presence information

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-api#2287]
We need to scrape the ICRC website to retrieve key information about their operations. The goal is to extract details on:  

1. **Countries with ICRC Presence**  
2. **Countries with Key ICRC Operations**  

**URL:** 
[https://www.icrc.org/en/where-we-work](https://www.icrc.org/en/where-we-work)  

**Acceptance Criteria:** 
- Extract and list countries where the ICRC has a presence.  
- Identify and list countries where the ICRC has key operations.  

**Tasks:** 
- Adjust the scraper logic to fetch the required information from the provided URL and update the API

**Comment by tovari** [comment]
I few country pages don't show ICRC presence:

Indonesia, South Sudan, USA, Moldova, Russia and Iran

I assume it might come from the different country names on GO and icrc.org

**Comment by samshara** [comment]
@susilnem , we need to separate these into individual countries: Indonesia and Timor-Leste (https://www.icrc.org/en/where-we-work/indonesia-and-timor-leste).  

For GCC countries (https://www.icrc.org/en/where-we-work/gulf-cooperation-council-gcc-countries), 
@tovari , should we break them down into individual countries as well?  

Additionally, how should we handle the `ICRC delegation to the African Union` (https://www.icrc.org/en/where-we-work/icrc-delegation-african-union

cc @udaynwa
