### ISSUE TITLE
Redirect obsolete link

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#2304]
Please redirect
https://ifrcgo.org/how-to-use-the-go-api/
page to Wiki:
https://go-wiki.ifrc.org/en/go-api/api-overview

**Comment by szabozoltan69** [comment]
To redirect https://ifrcgo.org/how-to-use-the-go-api I need access to a https://github.com/IFRCGo/... repo (which I can't see at the moment).

**Comment by szabozoltan69** [comment]
Done via https://github.com/IFRCGo/how-to-use-the-go-api/commit/cde374fc10ce7f5495122185aaf4e4dfc7cddb4d
