### ISSUE TITLE
Include linter

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-api#262]
Project should have a linter

**Comment by dereklieu** [comment]
https://jeffknupp.com/blog/2016/12/09/how-python-linters-will-save-your-large-python-project/
https://www.pylint.org/

**Comment by szabozoltan69** [comment]
Using the pylint (and pylint_django) was useful, I've found something to correct. But the inclusion of the whole linter package-set will be more work, to do it without 3rd party code change. I shall work on it...

**Comment by szabozoltan69** [comment]
Fixed by https://github.com/IFRCGo/go-frontend/pull/551

**Comment by szabozoltan69** [comment]
I reopen it, because the referred fix works in frontend only; backend still needs a linter in the future.
