### ISSUE TITLE
Verbose URLs

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#357]
There are several elements in GO III Req29:
a) improvement of user friendliness of API, in other words moving from numeric to human-readable fields
b) improve the naming of URLs, in other words region/country/ ... although emergencies/fieldreports might be beyond scope
c) having some API user management system in place.

**Comment by szabozoltan69** [comment]
So, instead of:
 https://dsgocdnapi.azureedge.net/api/v2/country/5
we should be able to use
 https://dsgocdnapi.azureedge.net/api/v2/country/uruguay

**Comment by szabozoltan69** [comment]
And on frontend also, instead of:
https://dsgoproxyapp.azurewebsites.net/countries/74
we should be able to use
https://dsgoproxyapp.azurewebsites.net/countries/greece

**Comment by szabozoltan69** [comment]
Now it's done, thanks to @thenav56

**Comment by nanometrenat** [comment]
Some examples of the available URLs (various scenarios - one/multiple word country names, punctuation etc.):

- Columbia: https://go.ifrc.org/countries/colombia goes to the exact same place as https://go.ifrc.org/countries/48
- Costa Rica:  https://go.ifrc.org/countries/costa%20rica goes to the exact same place as https://go.ifrc.org/countries/51
- St. Vincent and the Grenadines:  https://go.ifrc.org/countries/St.%20Vincent%20and%20the%20Grenadines#operations goes to the exact same place as https://go.ifrc.org/countries/179
- Bahamas, The:  https://go.ifrc.org/countries/Bahamas%2C%20The goes to the exact same place as https://go.ifrc.org/countries/25

Cheat sheet for non-devs:

- Single word country names are as-is
- Spaces are replaced by `%20`
- Points (`.`) and apostrophes (`'`) stay as-is
- Côte d'Ivoire ends up as https://go.ifrc.org/countries/C%C3%B4te%20d'Ivoire

**Comment by teklal** [comment]
Interestingly for Asia Pacific region the URL is https://go.ifrc.org/regions/asiapacific i.e. it does not have the space replaced by `%20`
