### ISSUE TITLE
URL strings wired in

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#379]
Recently there are two URL-s wired in to a runserver.sh script:
https://github.com/IFRCGo/go-api/blob/master/main/runserver.sh#L12-L14

They should be in env variables instead.

**Comment by nanometrenat** [comment]
@szabozoltan69 is this still required to be actioned?  Is it part of refactoring or separate?

**Comment by szabozoltan69** [comment]
@nanometrenat It is just some nice-to-have, refactoring-like task. (Can be closed if there are too many issues open.)
