### ISSUE TITLE
User list

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#419]
Possibility to export the list of users (with their RCRC entities) as a CSV file from Django Admin interface (for superusers).

**Comment by szabozoltan69** [comment]
The "with their RCRC entities" constraint makes this task a bit difficult.
From the Django Admin interface only the existing entities (or subsets) can be exported, so recently "Users" or "Profiles" (and not the join of them).
The RCRC entites are in the Profiles, but usernames and the user's real name are in Users.

A special frontend button (in superuser's account area?) could be a better solution.

**Comment by szabozoltan69** [comment]
The solution (made by @GregoryHorvath ) is on dev environment, please test it, @guipizzini and @teklal . An email was sent with the details.

**Comment by LukeCaley** [comment]
Thanks @szabozoltan69  we can confirm that this functionality is working.  

However, we would like to add a field for the export, namely 'user groups'.  We would like to know this for each individual so that we know how to communicate with these users if we are making specific changes to modules which they are administrators for.

Thanks

**Comment by szabozoltan69** [comment]
Thanks for the feedback, the user groups will be in the export also.

**Comment by szabozoltan69** [comment]
@LukeCaley @teklal – Please test the "user group" export, now it works.

**Comment by nanometrenat** [comment]
Tested in Production and this is good to close - thank you.  I have spot-checked a handful of users in 0,1,2 or 3 user groups and all are correctly reflected on the User Group export.
NB User Group export does not include individual user permissions (but this was not in scope of the request so is correct).  Many thanks!
