### ISSUE TITLE
Data Bank: Define data model

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#434]
Data analysis scripts: https://github.com/toggle-corp/ifrc

Sample JSON for the `ifrc-api` output: https://jsonblob.com/api/jsonBlob/3d5bb4f8-9167-11e9-a889-8573ad0634c2

Some notes on the sample outputs from `ifrc-pdf`: https://gist.github.com/thenav56/e6c1217a1bb3abf7362760584e4dd3e1 and some sample JSON: https://jsonblob.com/51169968-91be-11e9-a889-13ef9f28e6c7

We need to look at this data, and see how to fit it into the IFRC-Go database, and if we need to add new tables or make schema changes to accommodate this data.

It seems like we might be able to use the `CountryKeyFigure` model to store some of the country data in the script outputs.

Also, a lot of the script outputs looks like data we already have in the database - eg. AppealDocuments and Appeals / the data generated by `ifrc-pdf`. First task here will be to lay out the data more clearly, and then see if it can work with the existing DB structure, or we need to make changes.

cc @szabozoltan69

**Comment by szabozoltan69** [comment]
I think we need new tables, which will be joined to the existing ones.
With an example we could begin the data definitions.

**Comment by thenav56** [comment]
@batpad @szabozoltan69 
We can use postgresql django [JsonField](https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/fields/#jsonfield) for storing scripts data in country/region level.

Can you guys share any initial database scheme developed/designed for databank?
Also, which data are already available in the platform and which needs to be pulled from scripts?

**Comment by batpad** [comment]
> We can use postgresql django JsonField for storing scripts data in country/region level.

Using a JSONField sounds fine to me :+1: 

> Can you guys share any initial database scheme developed/designed for databank?

We were just at the stage of understanding the JSON data and what was being scraped before we shifted priorities, so there was no work done on the schema.

> Also, which data are already available in the platform and which needs to be pulled from scripts?

cc @guipizzini to give a detailed of mapping of data points on the frontend to various data points:

 - Data being ingested by scraper
 - Data that already exists in the backend / Django admin
 - New data fields that are not ingested by the scraper, but will be entered manually by people in the Django Admin

Once we have all the documentation from @guipizzini we can do another dive into details and make sure all the data points we need are covered.

**Comment by batpad** [comment]
@thenav56 I wonder if a good approach to allow us to move ahead would be to start with just figuring out the schema and the data ingestion for the JSON data coming from the scraper. Since we probably need to ingest all of that data anyway. And then, once we have more clarity, move to both the PDF ingestion, as well as figuring out integrating other fields that are not part of the scraper data?

**Comment by thenav56** [comment]
> @thenav56 I wonder if a good approach to allow us to move ahead would be to start with just figuring out the schema and the data ingestion for the JSON data coming from the scraper. Since we probably need to ingest all of that data anyway. And then, once we have more clarity, move to both the PDF ingestion, as well as figuring out integrating other fields that are not part of the scraper data?

Sounds good.

**Comment by guipizzini** [comment]
@batpad before marking this as complete, can you confirm we have this all nicely documented?

Are we importing the scripts into the GO database?

If any of the scripts we are importing or data feeds go down, do we have a system to warn us of what is not available and why?

cc: @nanometrenat
