### ISSUE TITLE
Data Bank: Design and create API

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#435]
Related to #434 - expose the Seasonal Calendar data in the API, and allow filters, etc. as per what the frontend needs to show.

cc @szabozoltan69

**Comment by szabozoltan69** [comment]
Let's clear the details about the needed (and stored) data structures.

**Comment by guipizzini** [comment]
We need to ensure that the front end graphics and charts are matching the UX/UI requirements outlined by Yellow Umbrella, both in terms of design and functionalities.
