### ISSUE TITLE
Data Bank: Setup infrastructure to run scripts periodically

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#436]
Relates to #434 #435 .

The `data-analysis` scripts fetch data from a lot of sources and take a long time to run.

We will need to figure out:

 - Running this at some regular interval
 - Handling errors and re-trying (since it depends on many external sites, errors will be common)
 - Handling updating of data in the database when the scripts are run

We may have additional infrastructure needs, for eg. a new VM to run this on, since it is a long running task and we may not want to run it on the same VM as the other tasks.

cc @szabozoltan69

**Comment by guipizzini** [comment]
Same comment as per: https://github.com/IFRCGo/go-api/issues/434
