### ISSUE TITLE
Ability to add National Society logos

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#438]
We should store logos for national societies on the backend. This would help features like #437 and in the future could help creating a more custom feel for the website per national society.

For now, I think we should probably add a `logo` field to the `Country` model: https://github.com/IFRCGo/go-api/blob/master/api/models.py#L71 and for now, just make this editable in the Django Admin.

cc @szabozoltan69

**Comment by szabozoltan69** [comment]
Done by https://github.com/IFRCGo/go-api/pull/442
