### ISSUE TITLE
Monitor status of data ingestion scripts

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#439]
Right now, there are many scripts that run at different intervals as `cronjobs`, that query and fetch different data points to be added to the database.

Right now, if one of these scripts fails, it's a bit hard to find out about the failure, and relies on someone noticing that some data has not been updated as expected.

We should have some monitoring for these scripts and some very basic admin dashboard to show admin users the status of the data ingestion scripts.

I would propose to add a Django model like `CronJob` or so -- with something like `name`, `timestamp`, `status`, `message` - and then in the different CronJob scripts, write to this table on either success or failure with a status. We can then make a simple page to query and show when these scripts last run and what their status was.

Once we have this, we can also think of automatically triggering notifications if a script fails.

cc @szabozoltan69 @LukeCaley

**Comment by nanometrenat** [comment]
I can confirm that this is live and working, as today we got our first automated email (to IM box) notifying that a cronjob was erroneous.  Hence closing, thanks a lot!

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-functions/issues/11 for other potential monitoring we may wish to implement
