### ISSUE TITLE
Create RSS feeds for items in the database

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#440]
We should find out the use-case here a bit better before implementing this.

It seems like there is a need to subscribe to updates from the GO-API: when there are new emergencies, field reports, etc. added or updated.

Right now, this is handled mostly via e-mail notifications. However, email notifications does not scale, and also makes it a lot harder to programmatically subscribe to API updates.

To me, the cleanest way to do this seems to be to use RSS feeds - the GO API can export RSS XML for different object types in the database, and consumers can use their choice of tool to consume RSS feeds, and there are many since RSS is a common and open web standard.

While Django does have good framework support for exporting RSS feeds, it will still be some work to define exactly what information we want, and how we want to organize feeds. Documentation can be found here: https://docs.djangoproject.com/en/2.2/ref/contrib/syndication/

@LukeCaley it will be great to get some feedback if this seems like what you had in mind / how useful you think having RSS feeds for different objects would be. Of course, happy to discuss more in detail / send more links for context if that helps.

**Comment by szabozoltan69** [comment]
(By my opinion RSS feeds are suitable mainly for "geeks", "developers", and not for the normal GO users. It should be used mainly for API changes broadcasting. The content-related notifications are mostly required for technically not expert users. But let's wait Luke's feedback.)
