### ISSUE TITLE
3w: Create models structure

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#443]
For the who-what-where frontend, we need a new model structure to store this data (alongwith new frontend forms).

We can base the model structure off the form in the design: https://projects.invisionapp.com/share/P9SA110GT4S#/screens/369905382

Fields:

 - Reporting National Society (select National Society)
 - Country + Province (Foreign Key to `District`)
 - Project Name (Text)
 - Type of Programme Sector (ENUM) - choices are Multilateral, Bilateral - anything else? @guipizzini 
 - Sector of Activity (ENUM) - @guipizzini could you help with what all choices for this field will be?
 - Start Date (Date)
 - End Date (Date)
 - Budget Amount (Integer?)
 - Budget Currency - ENUM? What are valid currencies that we support? @guipizzini 
 - Project Status (ENUM) - What are the options here? @guipizzini 

@szabozoltan69 do you think it makes sense to create a new django `app` for this, like you have done with `per`? The `models.py` file in the `api/` app has gotten very big and I don't want to add more things there. I can either make it a separate app or first work on splitting up `api/models.py` into smaller files (which maybe we should do anyway).

@guipizzini let me know if the above field structure seems about right and we can go ahead and create the models in the database to hold the data.

**Comment by szabozoltan69** [comment]
@batpad Yes, it's a good idea to create a new django subdir for this, really! If there are connections to already existing tables, it's easy to connect the data.

**Comment by batpad** [comment]
Pasting @guipizzini's reponses here:

    - only CHF as a currency
    - Project Status options here: (Ongoing / Completed / Planned)
    - IFRC Sectors are here: (WASH, PGI, CEA, Migration, Health, DRR, Shelter, Preparedness)
    - Programme options are only multilateral and bilateral

@szabozoltan69 based on the above, I think we can remove the `Currencies` Enum altogether as well as the `budget_currency` field in the model (since it is always `CHF`). And we can make changes to the other `Enum` field options as per above.

**Comment by szabozoltan69** [comment]
Ok, fine! I'll make it, push it and please check it at 10:05 (13:35 Bombay).

**Comment by batpad** [comment]
I just took another look at the data structure for the current `Deployments` feature. You can see the models here: https://github.com/IFRCGo/go-api/blob/master/deployments/models.py

@guipizzini I may need some more help understanding how the current `deployments` data fits in with the new data model we have added for `Projects` - in how the data is stored, as well as displayed on thew frontend.

Also, if both these fit under the broad umbrella of `Who-What-Where`, @szabozoltan69 I wonder if we should put the models and code we put in the `w3` folder, just into the `deployments` folder. But let's not worry about that now -- if it seems like we should do that, I can make the change after everything is ready and before merging.

**Comment by batpad** [comment]
This is done!
