### ISSUE TITLE
Translations: Implement model translations for strings in the db

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#454]
https://github.com/IFRCGo/go-frontend/issues/649 outlines the general approach to translation, and a specific, potential approach for translating all static strings that are part of the UI.

For content that comes from the database, we would ideally store translations in the database.

There are a number of Django packages that aim to help with this: https://djangopackages.org/grids/g/model-translation/

I have used https://github.com/dokterbob/django-multilingual-model many years ago, but it is not unmaintained and does not support newer versions of Django. From browsing the packages and activity, I would recommend using https://github.com/deschler/django-modeltranslation . This seems like a mature project, and supports the features we would want:

 - Ability to easily mark model fields as translatable without having to edit existing models
 - Ability to auto-populate translations using an external service (more below)
 - Ability to edit translations in the Admin.

Ideally, whenever an english string is edited, or a new item added, we would auto-populate the translation fields using an external service. And then users will have the opportunity to edit the generated translations if required.

For external service to handle auto-translations, @LukeCaley recommended looking at the [DeepL Translator](https://www.deepl.com/en/translator) service. This looks great as a translation service, except that Arabic is not in their list of supported languages: https://www.deepl.com/en/translator

Therefore we would need to decide whether to:

 - Find a different translation service, perhaps just Google Translate.
 - Use a different service only for Arabic.
 - Handle Arabic translations manually

If we decide to go with this approach - i.e. adding fields in the database for different languages via the django `modeltranslations` package and then auto-populating those fields using an external API, it would be good to do a bit further research and prototyping of exactly how this would look like using the Django translation package along-with whatever external service we decide to use.

Once we are clear on the approach we want to take, I can try and break-down some of the steps involved in a bit more detail.

**Comment by nanometrenat** [comment]
Re other external translation services, as well as https://www.deepl.com/pro.html, https://aws.amazon.com/translate/ could also be considered.

**Comment by nanometrenat** [comment]
Closing as now covered by https://github.com/IFRCGo/go-frontend/issues/934
