### ISSUE TITLE
Database structures for surge deployments, country page 3W and events

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#464]
There are some changes which should be done in the near future (and was motivated by Sune).

1  Population of the deployments personnel data from [this](https://docs.google.com/spreadsheets/d/1CBvledFYc_uwlvHTvJE0SYS7_mPGU2L-zhrqbB4KNIA/edit#gid=0) sheet (currently only includes dummy data). The Google spreadsheet would be the only way to enter data, we will stop using the Django for data entry for personnel. No changes to front-end or data model.
- New data structures are created to ERU and PersonnelDeployment tables. Also a Google spreadsheet reader ([ingest_deployments](https://github.com/IFRCGo/go-api/blob/master/api/management/commands/ingest_deployments.py)) is began, but still not finalized (it just reads spreadsheet but does not create table records, because it needs some checks).

2   Optimization of the data model: since RDRT, HEOps and FACT has same characteristics, there is no need to have separate tables for each of them. So to combine all surge personnel in one table per previously proposed data model

3    Update to frontend ‘surge notifications’ table to ‘open alerts’ table. Process flow to populate this front-end table based on the same sheet. All rows with and empty name record would show as open alert. 

4     Event records, moving fields: fielderport - > event
The following field would be required to add to the event table:
Disaster start date
 Affected (already there)
 Dead
 Missing
 Displaced
 Injured
‘Alert level’ to be changed to ‘IFRC Severity level’ (DONE)
Related fields need to be populated automatically when a field report is submitted (except IFRC severity level, updated manually for now
We need to update the Django back-end so the ‘modify emergency’ has access to manually update these fields. The current function of adding custom key figures should be maintained.
We need to update the front-end so key figures are displayed again.

-  Discovered that the neeeded code part is here: https://github.com/IFRCGo/go-api/blob/master/api/drf_views.py#L501-L517

**Comment by nanometrenat** [comment]
Closing as Surge changes are on hold pending RRM integration design.  New ticket to be logged if required once those details confirmed.
