### ISSUE TITLE
29. Workflow to update Country and District (admin1) data

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#470]
There is often a need to update especially admin1 data, as admin1 names change, new admin1s are added, boundaries reshaped, etc.

This ticket aims to outline:

 - The current state of how geospatial data is managed on IFRC-Go
 - A long-term plan for how this should work
 - A short-term plan to handle immediate updates

This ticket also supersedes https://github.com/IFRCGo/go-api/issues/460

## Current State

Currently, data about Countries and Admin1 names and boundaries are stored in 3 places:

 - Tileset uploaded to Mapbox
 - The IFRC Go database (which also contains associations to other IFRC-Go database entities like Emergencies)
 - The frontend maintains a statically defined list of Country and Admin1 centroids: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/country-centroids.js and https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/district-centroids.js

This means that to make updates, we potentially need to update data in 3 places: the tileset in Mapbox, details in the database, and if centroids need to be updated, we need to update the centroid files.

Let's take a couple of examples:

#### Changing the Name of an admin1:

 - We would need to change the name in the Tileset on Mapbox (by uploading fresh data)
 - We would need to make sure you make the same corresponding change in the GO Django admin backend.

#### Adding a new Admin1:

 - We would need to add it to the tileset and upload to Mapbox
 - We would need to make sure to add the admin1 to the GO Django backend
 - We would need to update the `district-centroids.js` file with a centroid for the new admin1

#### Changing geometries of existing admin1s:

 - We would need to update the tileset on Mapbox
 - We would need to update the Centroids in the `district-centroids.js` file with new Centroids.

Of course, in the real world, things are likely to be combinations of all of the above, and we would need to ensure we keep these 3 data sources in-sync. This is not great for the long-term as political boundaries are bound to change.

## Long-Term Proposal

I would propose making the GO API database the canonical source of truth for all the Country and Admin1 data, including the geospatial / polygons data.

How this would work:

 - We would add spatial fields to `Country` and `District` in the database, store polygons, and have some workflow for users to update geometries for a Country / District (upload GeoJSON, or import from Shapefile, etc)
 - Users edit names, boundaries, etc. in the GO Django Admin.
 - Once a day / week or at some frequency, there is a backend job that exports this data from the GO database as GeoJSON, creates vector tiles and updates the tilesets on Mapbox
 -  The backend can then also automatically generate the centroid files that the frontend needs based on the data in the database.

This would consolidate our data sources and allow us to maintain a single source of truth from which all the other data is derived. This is a bit of work to do, but I think represents a sane long-term solution for geospatial data management in GO and managing updating of the Tilesets on Mapbox.

### Short-Term solution for immediate data updates

For name changes, I propose we just create a simple spreadsheet of Old Name and New Name and we can take care of updating that on the Mapbox Tileset as well as in the GO database.

If there are more complex changes including geometry changes, let's discuss, but we should be able to figure out a one-time way to perform the data updates required.

cc @ElsaRaunioIFRC @geohacker @LukeCaley

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/938

**Comment by geohacker** [comment]
Just some additional thoughts on the next steps after looking at the tickets listed in https://github.com/IFRCGo/go-frontend/issues/938.

## Store all geospatial data in the Go DB
* Countries - admin1 and admin2
* Disputed boundaries as lines
* Groups, regions, continents. For eg Europe, MENA
* All these will have iso codes, names, aliases, status (to enable disable, for instance if one wanted to update the Nepal country polygon, they can disable the previous one), links to enclaves etc.

Storing shapes in our database makes it easy for us handle all the different cases in naming, country associations, and disputed boundaries. It would be important for us to figure out the canonical source to depend on. 

## API
* /geojson -- Fetch all country and district polygons as a single geojson feature collection for visualization. This should have properties like name and centroid. 
* /countries -- list of countryies
* /districts -- list of districts
* /regions -- list of regions
* We might need few more end points. Integrating these APIs make sure no more hard-coded ids on the front-end and no mismatches between what's in the data and what's used in the style.

## Style
I recommend we stop using Mapbox Studio for styling, instead use Mapbox GL styles directly maintained within go-frontend. This makes it really easy for us keep the data and styles together and version control the styles. 

We'll be able to easily download the existing style from Mapbox GL and integrate that into go-frontend.

**Comment by nanometrenat** [comment]
Hi, just noting that there are some existing API endpoints that we will want to be sure we either use or make clear the distinction
e.g. api/v2/country (as opposed to countries above)
api/v2/region (this being Asia Pacific vs MENA as opposed to the sub-national admin levels)

Cheers and it will be great to get this sorted!  And I love that we are having a "disabled" option as versioning is something that we defo need to consider better in all future GO build.  THANKS

**Comment by nanometrenat** [comment]
Also, as mentioned verbally, if moving off Mapbox as "master" then we will need to consider how to handle a Mapbox sync off GO (which may be a manual business process?), as currently the GO Mapbox tilesets are also referred to by lots of separate vizzes (e.g. on Tableau) that are embedded as snippets on GO but not part of GO code.

**Comment by batpad** [comment]
@geohacker here is a listing of all places in the frontend code where country and "district" data is hard-coded. We will need to consolidate these and replace with API calls:

 - Country list to show in Field Report form (used also in other places): https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/field-report-constants.js#L35
 - Centroid definitions for countries: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/country-centroids.js
 - BBox definitions for countries: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/country-bounding-box.js
 - Mapping of iso2 to iso3 codes: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/country-bounding-box.js
 - District centroids: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/district-centroids.js
 - Bounding boxes for "regions": https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/region-bounding-box.js
 - Hard-coded mapping of countries to regions: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/region-constants.js

It will be useful to go through all of these and formulate a strategy to migrate the frontend code away from these hard-coded values. Am happy to break these down further into where all on the platform they are being used, if that's useful.

**Comment by nanometrenat** [comment]
Thanks team @batpad re the above some of this is also mentioned on https://github.com/IFRCGo/go-frontend/issues/940 "Remove hard-coded values and database ids from frontend code" - which also has some useful comments.

This ticket and that ticket are not the same but have a lot of commonality so might be worth distinguishing the boundaries between tickets ;)  Cheers all!

**Comment by batpad** [comment]
This tickets seems the closest to capturing the main thrust of the geospatial work in progress. I've removed from backlog and added to the project board.

@geohacker - let's also take a look at the #938 master ticket and see if some of the linked tickets there should be added to the dev queue separately.

**Comment by jhenshall** [comment]
Hey @batpad @geohacker - proposing that we move this out of 4.3 and review with the geo backlog after this release? This ticket does a great job capturing the longer term aspirations and whilst we have made some progress (e.g. moving things from frontend), there's a lot here still to do. Seems a waste to split into a new issue with so much useful information here. What do you think?

**Comment by batpad** [comment]
@jhenshall - it seems like most of everything on this list is covered, other than the vector tiles on Mapbox? We have:

 - Process to update db from shape-file
 - Spatial entities editable in the admin
 - All hard-coded geo entities moved from frontend

It would be great to be able to close this broad ticket and have the concrete remaining tasks captured in separate tickets, since most of these broad tasks are done.

@geohacker - would you be able to outline the tickets that capture the remaining work - i.e. Mapbox Vector tile export / generation and the styles work?

Would be great if we can then clarify the scope of this ticket to the shapefile import, editable admin and moving of frontend entities to be able to close. We'd still have this ticket to reference :)

But, whatever you feel is best @jhenshall @LukeCaley

**Comment by geohacker** [comment]
I'd be ok either way, but I don't see any strong reasons why we should keep this ticket open and moved to 4.4. The pending items outlined in this ticket have separate tickets, and would be better to track them individually than a single catchall ticket:

1. Mapbox export https://github.com/IFRCGo/go-frontend/issues/1474
2. Style updates https://github.com/IFRCGo/go-frontend/issues/1202

**Comment by jhenshall** [comment]
Ok great, sounds good to me! To capture here - had discussion with @geohacker about the potential of uploading shapefiles in the back end for adding new districts/countries or for more complex geometry changes than the bb and centroids (which can easily be edited). Decided best to keep to the current update process as it is infrequent and allows better change management. 

So only outstanding issue is the Mapbox stuff, which is ticketed. Thanks all!
