### ISSUE TITLE
3w Projects: Add field for Type of Operation

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#516]
Add a field to the `Project` model under `deployments` for `operation_type` or so, based on these frontend changes: https://github.com/IFRCGo/go-frontend/issues/640#issuecomment-537422134 (need a new field to capture the new `Type of Operation` field on the backend)

cc @frozenhelium @thenav56

**Comment by thenav56** [comment]
@batpad Can you help me with these.
* Is the field `operation_type` mandatory?
* Which value should be set as default for added projects?

**Comment by batpad** [comment]
> Is the field operation_type mandatory?

Yes.

> Which value should be set as default for added projects?

Either is probably fine, as there shouldn't be any data in the live system, so that should just affect testing data.

I think LONG_TERM_OPERATION is probably fine.

**Comment by thenav56** [comment]
@batpad 
Sounds good. I have made similar changes in https://github.com/IFRCGo/go-api/pull/519.
