### ISSUE TITLE
Make backend of development look different from backend of production

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#518]
I don't know how easy or difficult it would be to implement this, but would it be possible to make the backend of the development site look different from that of the production site? E.g. by adding a text to the top that states in big letters that it is the backend of the development site or by changing the colours (as with the frontend of the development site).

At the moment they look identical and there is danger that this causes some problems e.g. when users during simulation exercises think they are submitting a field report to the development site accidentally submit it to the live page.

**Comment by szabozoltan69** [comment]
Now I made a manual change in docker entity, ~/go-api/static/admin/css/base.css -> changing background: #aaa to

**Comment by thenav56** [comment]
@szabozoltan69, you can use context_processors to provide custom global variables to the Django templates.

You can do something like this.
```diff
diff --git a/api/templates/admin/base.html b/api/templates/admin/base.html
index 69c457e..4499f57 100644
--- a/api/templates/admin/base.html
+++ b/api/templates/admin/base.html
@@ -18,6 +18,8 @@
 
 <body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
   data-admin-utc-offset="{% now "Z" %}">
+    {# use PRODUCTION_URL to create logic #}
+    {{PRODUCTION_URL}}
 
 <!-- Container -->
 <div id="container">
diff --git a/main/context_processors.py b/main/context_processors.py
new file mode 100644
index 0000000..cb0af41
--- /dev/null
+++ b/main/context_processors.py
@@ -0,0 +1,8 @@
+from django.conf import settings
+
+
+def ifrc_go(request):
+    return {
+        # Provide a variable to define current environment
+        'PRODUCTION_URL': settings.PRODUCTION_URL,
+    }
diff --git a/main/settings.py b/main/settings.py
index a948ae0..64337c0 100644
--- a/main/settings.py
+++ b/main/settings.py
@@ -3,6 +3,8 @@ from datetime import datetime
 import pytz
 
 production_url = os.environ.get('API_FQDN')
+# Requires uppercase variable https://docs.djangoproject.com/en/2.1/topics/settings/#creating-your-own-settings
+PRODUCTION_URL = production_url
 localhost = 'localhost'
 BASE_URL = production_url if production_url else '%s:8000' % localhost
 
@@ -96,6 +98,7 @@ TEMPLATES = [
                 'django.template.context_processors.request',
                 'django.contrib.auth.context_processors.auth',
                 'django.contrib.messages.context_processors.messages',
+                'main.context_processors.ifrc_go',
             ],
         },
     },
```

Also for  DEEP we are doing something like this.

![grim_2019-10-05-092156](https://user-images.githubusercontent.com/7059255/66249355-9fbf6a80-e751-11e9-8e07-112c3c90cb17.png)


https://github.com/the-deep/server/blob/develop/deep/settings.py#L27
https://github.com/the-deep/server/blob/develop/deep/context_processor.py
https://github.com/the-deep/server/blob/develop/apps/templates/admin/base_site.html

Hope this helps.

**Comment by szabozoltan69** [comment]
Thanks @thenav56 – You helped a lot!

**Comment by szabozoltan69** [comment]
Done via https://github.com/IFRCGo/go-api/pull/537
