### ISSUE TITLE
Contact information disappears after submitting a field report

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#520]
When creating a field report on GO, the contact information that a user fills in does not get saved after submitting the form.

![image](https://user-images.githubusercontent.com/52411237/66301825-2150fd00-e8f8-11e9-9f04-1f1404c1ad25.png)

The contact information appears neither on the frontend when opening to edit the already submitted field report, nor when accessing the respective submitted field report through the backend.

All other information is saved as should.

We have received some concerned emails about this from our regions, so it is urgent and important to find a fix for this.

**Comment by szabozoltan69** [comment]
We are on it with Gergő...

**Comment by GregoryHorvath** [comment]
@teklal Hi Tekla. I dared to look after this (still just getting to know each other with the application). I think I have a solution backend-wise. I will upload the code in a moment, the only problem is the phone number field is not showing up yet.
Who should I notify to make the code live for you (after checking it of course)? @szabozoltan69 is pretty busy at the moment.

**Comment by szabozoltan69** [comment]
The backend side change is done (and pushed to production also).
Maybe go-frontend fix is also needed.

**Comment by nanometrenat** [comment]
@mmusori advises this is fixed
