### ISSUE TITLE
"Edit xxx" button redirects to general admin backend page instead of event/country backend page

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#521]
When clicking the "Edit event" button on the frontend it takes the user to the general admin page of the backend instead of the specific page to edit that emergency on the backend. The same happens when clicking "Edit country" on a country-specific GO page; the user is directed to the general backend instead of that country's backend page.

This is what "Edit event" or "Edit country" currently redirects to:

![image](https://user-images.githubusercontent.com/52411237/66311389-a0e9c680-e90e-11e9-849d-6f57a5707be8.png)

When it should be e.g. for country The Bahamas this:

![image](https://user-images.githubusercontent.com/52411237/66311506-ea3a1600-e90e-11e9-8d6b-6333fdb243f8.png)

**Comment by szabozoltan69** [comment]
@teklal Could you please specify this: "clicking the "Edit event" button on the frontend"
On which part of the frontend is this?

**Comment by teklal** [comment]
Sure, sorry for not including examples above.

For countries, it's on a country's GO page in the upper-right corner like this:

![image](https://user-images.githubusercontent.com/52411237/66311946-f1155880-e90f-11e9-9ce3-f85407e27376.png)

And for an emergency GO page in the respective location:

![image](https://user-images.githubusercontent.com/52411237/66311896-db079800-e90f-11e9-9f7d-e437b5660ce2.png)

**Comment by GregoryHorvath** [comment]
@teklal The fix should be deployed shortly (onto the staging environment, if I'm not mistaken).

**Comment by szabozoltan69** [comment]
This bug is fixed on staging (and will be fixed on production too, when the recent staging frontend state will be deployed to prod).
