### ISSUE TITLE
API monitoring [formerly called API user management]

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#524]
Module to monitor API connections to notify when issues occur and issue change alerts to users.

**Comment by batpad** [comment]
@szabozoltan69 can you give more details as to what exactly will be the feature here? Happy to get on a call or so to discuss in detail if that helps.

**Comment by LukeCaley** [comment]
@GregoryHorvath @szabozoltan69 it would be good to get a progress update on this ticket.  Essentially we are keen to ensure that we have a user-friendly means to monitor the increasing number of APIs we are connecting to in the GO d/b.  Related to this, we are keen to have a clear update to users linked to GO APIs when either changes have been made or there are issues with one or more of the API fields.

**Comment by GregoryHorvath** [comment]
@LukeCaley This ticket is for the one task (of mine) which got scraped from 4.1 and pushed to next year.

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-api/issues/439

**Comment by nanometrenat** [comment]
Closing in favour of #439 - new ticket to be logged re pro-active notifications in future when required.
