### ISSUE TITLE
Emergency page: Response documents added with URL not working accessible through frontend

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#535]
On emergency pages in the "Resopnse documents" section documents that have on the backend a URL linked to them, are not accessible through the frontend. Only documents that have been uploaded as a file can be downloaded through the GO frontend interface.

As an example: on the Bahamas emergency page (https://go.ifrc.org/emergencies/3751#details) , when clicking to download the "IFRC Operations Update #2", nothing happens.

![image](https://user-images.githubusercontent.com/52411237/66991101-b3f75600-f0c7-11e9-9271-d0180f2a06bb.png)

The problem is not that there is no document linked or that the URL link would not work as when checking the backend, the URL of this document indeed does work.

![image](https://user-images.githubusercontent.com/52411237/66991139-c70a2600-f0c7-11e9-9f9e-15a7659f4c13.png)

I tested this for all documents that were added through URL and the problem is the same for all of them. The links do work, when opening them through the backend, but for some reason, they cannot be opened through the frontend.

**Comment by szabozoltan69** [comment]
This should be checked also on front-end, I suppose that somehow the URL is not pulled fine (from API) and not shown.

Maybe a previous back-end change (.../admin was changed to ...) can be in the background. But on front-end side it can be fixed (if the place is found). Could you give it a chance, @GregoryHorvath ?

**Comment by GregoryHorvath** [comment]
@teklal @szabozoltan69 Sorry I forgot to mention it here but this should be working as well if this gets deployed (I believe, someone should check it before): https://github.com/IFRCGo/go-frontend/commit/0e025901cfd15b082e95b92751b6736294073597

**Comment by szabozoltan69** [comment]
Thanks to @GregoryHorvath, fixed via https://github.com/IFRCGo/go-frontend/pull/854
