### ISSUE TITLE
[PROD] Funding and people targeted information incorrect for operations with DREF and EA

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#536]
Currently for operations where initially a DREF was requested but later an Emergency appeal (EA) is launched, the funding information on the emergency page sums the "Amount requested" and "Amount funded" for these two appeals, as well as the people targeted ("Num beneficiaries" on the backend).

The way it works though is that after an EA is launched, the DREF money that was allocated to that operation, becomes a loan for that EA and is merged into that funding. So for these operations the information we need to display on the GO emergency page is the funding information of just the Emergency appeal. So the information in the Emergency Appeal is "more up-to-date" and is the one we should be pulling from.

Example: Bosnia and Herzegovina - Population Movement

The emergency page that is created from the appeal currently shows the following info:

![image](https://user-images.githubusercontent.com/52411237/66995258-fe300580-f0ce-11e9-8e74-d66c4ab744dc.png)

The funding info on the two cards is pulled from these appeals:

DREF:
![image](https://user-images.githubusercontent.com/52411237/66996493-1e60c400-f0d1-11e9-8ee4-f27639ce3ffd.png)

Emergency Appeal:
![image](https://user-images.githubusercontent.com/52411237/66996538-359fb180-f0d1-11e9-9334-babf7b20140d.png)

And these amounts are summed.

Can we change it to be so that for operations that have both a DREF (initially) and an EA, only the EA information for funding and people targeted is displayed on the frontend?

**Comment by szabozoltan69** [comment]
@teklal You've found a real error, and the solution is quite clear: MDRBA010 has a "**closed**" status and MDRBA011 is "active", so maybe only the not-closed ones should be used. Am I right? (Or can be other cases where also closed appeals needs to be shown?)

An other possibility is to ask the financial group to not send obsolete appeal data on their API.

If we decide not to show closed appeals, then on API side the api/drf_views.py should be changed, mainly the RelatedAppealSerializer.

**Comment by szabozoltan69** [comment]
With https://github.com/IFRCGo/go-api/pull/537 I included also the "status" and "start_date" into RelatedAppealSerializer, so on front-end side the not "active" appeals can be disregarded. @batpad, @GregoryHorvath – if you have time, please check the todos on front-end.

(I am not 100% sure that this approach will work – @LukeCaley, can you confirm + give a green light, that really only "active" appeals should be summarized?)

**Comment by GregoryHorvath** [comment]
@szabozoltan69 @teklal @batpad - I made the change so only the 'Active' appeals are summed on the Emergency's page (if I understood the issue correctly). It is not deployed anywhere yet so if you validate that this is the right solution it can simply be deployed any time.
The fix - https://github.com/IFRCGo/go-frontend/commit/4bf1f4673559f75e3623d9629fb8cf51c8ba845f

**Comment by szabozoltan69** [comment]
Works fine fix/emergency-appeal-sums in my local environment, it gives the right value concerning the original (Bosnia-Herzegovina Population Movement, 3218) emergency:

![3218_Bosnia_H_Population_Movement](https://user-images.githubusercontent.com/6050643/67678708-9b205780-f987-11e9-8642-17e8db30128a.png)

**Comment by GregoryHorvath** [comment]
@nanometrenat @LukeCaley Is this still an open issue? Never got feedback on the above suggested fix, but we still have the code at https://github.com/IFRCGo/go-frontend/commit/4bf1f4673559f75e3623d9629fb8cf51c8ba845f so I can go ahead and create a surge URL for it, if needed.

**Comment by GregoryHorvath** [comment]
Deployed it to: https://ifrc-go-fix-active-appeals.surge.sh/

**Comment by nanometrenat** [comment]
@mmusori is probably best placed to confirm the logic for this calculation, backed up by @guipizzini and @LukeCaley.  Noting that https://github.com/IFRCGo/go-frontend/issues/915#issuecomment-677287890 relates, and is awaiting business logic before proceeding.

**Comment by nanometrenat** [comment]
@anamariaescobar @mmusori this ticket is still open from 2020 - but I strongly suspect that any issues have been ironed out by now!

Can you please check that the figures/calculations are now correct, and close if they are?  Thanks!
