### ISSUE TITLE
Refactor PublicJson views

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#541]
There are a few views that subclass the PublicJson or PublicJsonPost views that seem like they would be better re-written as normal DRF Views, or ideally, just be part of the Viewset for that object type.

Creating a stub ticket here - let's put more examples and details of places where this pattern exists, and what it would take to fix. Keeping in mind that we would probably need to maintain backwards compatibility with the URL structure (though that can be handled with 301 redirects?)

cc @thenav56

**Comment by GregoryHorvath** [comment]
This was already resolved mostly via https://github.com/IFRCGo/go-api/pull/840
