### ISSUE TITLE
Python script to ingest emergency appeal and EPoA data into GO d/b

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-api#542]
> From "Annex - Terms of Reference (002)" document

**Comment by GregoryHorvath** [comment]
> Need a Django Admin function for Superusers to be able to run the script which converts the data from PDFs into CSVs, and need credentials for the Google API where the 2 sheets are located (epoa.csv, ou.csv) [Step 1 of this: https://developers.google.com/sheets/api/quickstart/python , right now I can only test it with my own Google Drive]

**Comment by GregoryHorvath** [comment]
@nanometrenat @thenav56 I believe this can be closed since the scrapers are done (if the Databank is implemented too).

**Comment by nanometrenat** [comment]
Gosh this is a vintage one and I don't know if it can be closed as have not been involved - @mmusori is there any action still remaining on this ticket?

And @thenav56 @GregoryHorvath @batpad can you please point me to the documentation about Databank and ingest stuff?  I can't spot it in the wiki but might not be looking in the right place.  THANKS!

**Comment by thenav56** [comment]
@nanometrenat
I think the databank ingest was related to this issue https://github.com/IFRCGo/go-api/issues/436.
The databank ingest is included in our go-api docker-compose.yml 
https://github.com/IFRCGo/go-api/blob/50e87644a6ce7994eb6b72b0cc8806f88925952d/docker-compose.yml#L44-L46

Should I include this to the Readme? Let me know and I will send a PR.

**Comment by GregoryHorvath** [comment]
I believe this can be closed. If further work is needed a new ticket should be opened.
