### ISSUE TITLE
Add grouping information to Actions model

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#545]
Right now, Actions (for Field Reports) can be added and edited in the Django Admin. However, the frontend maintains a hard-coded list of actions along with ids: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/field-report-constants.js#L456

This is very hard to maintain and depending on backend ids on the frontend is generally considered bad practice. Ideally, the frontend should be able to fetch the Actions from the backend, and the Actions should contain all the information the frontend needs to know where to render them.

Hence, we should do the following:

 - [x] Add a `type` field to the Action model (to specify Event or Early Warning)
 - [x] Add a `section` field to the Action model (to specify National Society, IFRC or Others)
 - [x] Add an API call to return all Actions alongwith their type and section information
 - [ ] Change the frontend to get the Actions from the API, and use the type and section information to show actions correctly as per the field report type and organized in sections. (will ticket this separately in the frontend repo if required).

cc @necoline @thenav56 (assigning myself, just fyi in case you have any thoughts / comments)

**Comment by batpad** [comment]
+cc @szabozoltan69 for visibility - in case you get the chance to look at this and if it generally sounds okay to you.

**Comment by batpad** [comment]
I realized that an Action can be part of multiple `Sections` - i.e. the same action should show in the National Society, as well as IFRC Section, etc.

Ideally, I'd like to store this as an `ArrayField` to hold an array of Choices values or so. So a user can select multiple values like `National Society`, `IFRC`, etc. in the admin. I can't seem to find something completely out of the box to do this in the Admin. This does seem to be a common need though, and I can find a few things online:
 
 - https://stackoverflow.com/questions/31426010/better-arrayfield-admin-widget
 - http://paulbormans.blogspot.com/2017/04/multiple-choices-from-tuple-in-django.html

@thenav56 wanted to ask if by any chance you have implemented something similar, else I'll dig into this articles and look into an implementation. Thanks!

**Comment by szabozoltan69** [comment]
Deployed to staging area.
Please tell me if everything seems to be successful, then I deploy it also to production (to not to have big distance in code...).

**Comment by batpad** [comment]
@szabozoltan69 Please hold off a bit - @thenav56 made a suggestion for changes which I will now make as a separate PR ..

**Comment by batpad** [comment]
This is done and merged.
