### ISSUE TITLE
Restrict ability to add `is_featured_region` to users with permissions for region

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#553]
Current Behaviour: Anyone with permissions to edit an Event can toggle the `is_featured_region` flag for that Event.

Desired Behaviour: Only users who have permissions for the Region that the Event belongs to should be able to toggle the `is_featured_region` flag on it.

This seems to me to be non-trivial with the current permissions architecture and Django Admin setup. Putting for visibility in case there is something straightforward I might have missed - cc @szabozoltan69 @thenav56 

I do think we should discuss the overall permission model needs, as it seems like the permissions structure has so far developed fairly ad-hoc, using the default django Users and Groups - we would need to think about things a bit differently if we wanted to have granular permissions, including restricting which fields in a model can be edited by which users.

This is doable in a slightly ad-hoc fashion by creating a separate view to toggle the `is_featured_region` status and writing custom logic to check against user permissions. However, we probably should have a larger ticket around permissions handling through the site - we probably want some way to associate users with Countries / Regions in the db and have permissions based on this. 

Also, doing a smooth integration into the Admin with granular row-level and column-level permissions is likely a bit of work / we may also want to consider breaking out a lot of the editing interfaces out of the Django Admin.

@LukeCaley it would be great to have a separate call about permissions structures in general and what the needs would be and how best to scope this out.

**Comment by nanometrenat** [comment]
Closing this ticket as will come under 'permissions review' umbrella
