### ISSUE TITLE
Audit trail improvements requirements

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#572]
Initial wording:
Ensuring   there is a clear interface for monitoring user actions and assigning user permissions.  In addition, building up a system audit trail.  Potentially including roll-back.

--------
Further details re the requirements (some of this may be being logged under the hood but not visible to the user, other things may not be being logged right now):

- [x] **Entity creation:**  Ensure that all new records created have an entry in audit history to say which user/system process created it and when.  Currently for some types of record, when I click on the 'history' button in the back office I get a message "This object doesn't have a change history. It probably wasn't added via this admin site."  As an admin user looking at the history screen I should be able to see WHEN that item was created when I look in the history, and whether it was created via (inbound or outbound) API/system process or by a front office user or a back office user.  e.g. see https://dsgocdnapi.azureedge.net/auth/user/2720/history/?_changelist_filters=q%3Dnatalie
- [x] **Entity updating:**  In the history, currently I can see what action was carried out in the back office site (e.g. 'Changed first_name', 'Changed groups.'), from Django_admin_log  I can't however see details of what it was changed FROM and TO, and I should be able to see this detail (e.g. changed user group from ‘’ to ‘Philippines Admins’)  https://dsgocdnapi.azureedge.net/auth/user/2719/history/?_changelist_filters=q%3Dnatalie  Also, if it is changed via front office or automation/API then I should be able to see what user/process made the change. 
- [x] **Entity deleting:**  When an entity is deleted I cannot see any trace of what happened or by whom.  For example, if a user is deleted (e.g. because they had set up two user accounts and only need one) I cannot see any record that that user ever existed.  In order to keep audit trail integrity we should keep a record that that userid existed and that user y deleted it on date z.

It would be great to have a single framework/widget that organised the audit trail of all entity/data types, but in the first instance I am most interested in tracking users (setup/change/deletion) and the audit trail around actions users take.  Dev, can you please take a look at which of the above items can be actioned in the short term?

Additional audit trail requirements specific to **users**
- [x] List all **logins and status** (success or failure + failure reason e.g. wrong password, username does not exist, user not yet verified, two user accounts set up with same email address).  If I am guessing correctly, Successful logins may well be able to be seen via authtoken_token (?) but I can’t see unsuccessful login attempts anywhere.
- [x] Re **registrations_pending**, on the front end (“Pending Users”) I cannot currently see which of the two admin_contact email addresses has and hasn’t validated the user – so I don’t know whether both need to be chased or just one.  Under the hood in the db it stores true/false against admin_1_validated and admin_2_validated but I can’t see where it tells me what _date_ each admin validation happened.  Also, with reference to Entity Creation point above, I cannot see on https://prddsgocdnapi.azureedge.net/registrations/pending/ what date the user registered (and therefore how long they have been waiting for validation) so would be great to pull that through also – although I realise I could manually look up the user in users screen one by one.

Additional audit trail requirements specific to **GO-provided API**
- [ ] Log all incoming calls to the GO API with full params, user (if authenticated) and response (not necessarily full body of response, but definitely success or failure message).  This will enable us to track usage of the API - which is useful even for 'GET's but particularly important for POST/PUT etc.  This last one may be possible to obtain from Firewall logs though?  Perhaps?

@szabozoltan69 @batpad Trust this all makes sense but as always please let me know if further detail is needed.  Thanks!!

**Comment by nanometrenat** [comment]
To be scoped.

**Comment by batpad** [comment]
@frozenhelium @thenav56 can we start putting down potential options for Django plugins to help with this?

I think I remember seeing https://github.com/etianen/django-reversion as a reasonable option in the past. Do you have any suggestions / anything you have worked with that you would recommend?

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/329 re saving previous states of any create, update, and delete operation.

**Comment by nanometrenat** [comment]
Updated some details in ticket description above.  Rollback not currently in scope - just traceability at this stage.

**Comment by GregoryHorvath** [comment]
@nanometrenat @batpad @thenav56 @frozenhelium

I've "plugged-in" the basic version of django-reversion (and django-reversion-compare). If we want to differ from the default functionality then it would need some manual implementations of new models and such for it. I'd say by this it basically covers these:

- [x] Entity creation
- [x] Entity updating
- [ ] Entity deleting - Deleted records can be restored but it doesn't really say at the moment who deleted them.

The branch for it: https://github.com/IFRCGo/go-api/tree/feature/audit-trail

**Comment by nanometrenat** [comment]
> > Log all incoming calls to the GO API with full params, user (if authenticated) and response (not necessarily full body of response, but definitely success or failure message). This will enable us to track usage of the API - which is useful even for 'GET's but particularly important for POST/PUT etc. This last one may be possible to obtain from Firewall logs though? Perhaps?
> 
> I believe there already is a log-file which contains this information if I'm right. So we might only need a way to periodically update some table in the DB from that meets the needs.

Hi @GregoryHorvath thanks for this - can you please tell me where the log-file sits currently?  Is it somewhere on the application server or somewhere else in the infrastructure?  If you're able to please send me an extract that would be really useful for me to figure out if it is necessary to write it to a db table or if we can deal with this some other way.  Thanks!

**Comment by GregoryHorvath** [comment]
> > > Log all incoming calls to the GO API with full params, user (if authenticated) and response (not necessarily full body of response, but definitely success or failure message). This will enable us to track usage of the API - which is useful even for 'GET's but particularly important for POST/PUT etc. This last one may be possible to obtain from Firewall logs though? Perhaps?
> > 
> > 
> > I believe there already is a log-file which contains this information if I'm right. So we might only need a way to periodically update some table in the DB from that meets the needs.
> 
> Hi @GregoryHorvath thanks for this - can you please tell me where the log-file sits currently? Is it somewhere on the application server or somewhere else in the infrastructure? If you're able to please send me an extract that would be really useful for me to figure out if it is necessary to write it to a db table or if we can deal with this some other way. Thanks!

Hi @nanometrenat!
This is the file: https://github.com/IFRCGo/go-api/blob/a80f0223215d855ec4ee6ba7f13e208b1e71ad48/main/runserver.sh#L21 .
So it sits on each of the Django servers, one on staging and one on production.

**Comment by nanometrenat** [comment]
> So it sits on each of the Django servers, one on staging and one on production.
I have just logged SRV-17793 re a particular problem I need the logs to troubleshoot!  Many thanks.

**Comment by GregoryHorvath** [comment]
@GregoryHorvath to get info about what should the logs contain on staging
@teklal to check if they appear in the logs on staging

**Comment by nanometrenat** [comment]
Hi there, just looking at this in Production and it seems the audit trails still don't show everything that happens on the front end (though it is quite good at showing back end changes).

e.g. when a field report is created there is nothing in the history to show who created it and when

Also, just now I was in the back end editing a Field Report that had been created in the front end (so had no history in the audit trail).  All I did was unselect the Emergency that it was associated with, and clicked save.  However looking at the audit trail after doing that it says "Changed description, event, other_sources and actions_others. Changed summary for actions taken "(and has the summary here).".  I hadn't actually changed the description, other_sources, actions_others or summary!  I had only changed the event.

Therefore moving back to To Do, for further investigation in future.  Thanks!

**Comment by nanometrenat** [comment]
Also, the audit trail is incorrectly reporting changes in some cases.

e.g. just now I edited FRs 12337 (created pre-release) and 12364 (created only today)

The only field I changed was "Event" - all other fields were left as-is and I hit save.

As you can see in the history, in both cases it is reporting that I changed a whole lot of fields but should only be reporting one change (obvs in the below I have xxx'd out the actual info from the audit trail:
Changed description, event, other_sources and actions_others. Changed summary for actions taken "NTLS:  xxx". Changed summary for actions taken "PNS: xxx". Changed summary for actions taken "FDRN: xxx". Changed email for field report contact "xxx: staff/DM". Changed email for field report contact "xxx". Changed email for field report contact "xxx".

https://goadmin.ifrc.org/api/fieldreport/12337/history/

**Comment by nanometrenat** [comment]
Setting the backlog tag on this ticket - what has been done is GREAT and a vast improvement.  Still a few things we will want to adjust/work on in future, but not top priority right now.

**Comment by nanometrenat** [comment]
> * [x]  Re **registrations_pending**, on the front end (“Pending Users”) I cannot currently see which of the two admin_contact email addresses has and hasn’t validated the user – so I don’t know whether both need to be chased or just one.  Under the hood in the db it stores true/false against admin_1_validated and admin_2_validated but I can’t see where it tells me what _date_ each admin validation happened.  Also, with reference to Entity Creation point above, I cannot see on https://prddsgocdnapi.azureedge.net/registrations/pending/ what date the user registered (and therefore how long they have been waiting for validation) so would be great to pull that through also – although I realise I could manually look up the user in users screen one by one.

The above was released to Prod some time ago, then this week @GregoryHorvath is adding an extra column under https://github.com/IFRCGo/go-api/pull/734 so we can see whether or not the pending user has verified their email address.

**Comment by batpad** [comment]
@nanometrenat do you think it might be possible to outline a smaller ticket here that we can put into the Backlog with remaining items, and then close this? No urgency, going to leave as is for now.

**Comment by nanometrenat** [comment]
@tovari to take a look at what is currently in place and ticket out if any further work is still required.

**Comment by nanometrenat** [comment]
@tovari @szabozoltan69 is any further work required on this one, or is it now superceded?  Is the audit trail comprehensive and functioning well these days?
Cheers

**Comment by szabozoltan69** [comment]
As I know it is comprehensive and functioning well.
