### ISSUE TITLE
Warnings in test

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#609]
If we run a "docker-compose run --rm  test" (or a ./manage.py test -k  – in the docker entity) then some project-related warnings arrive. It would be fine to find the reasons. Some API endpoint has been changed?

```
Using existing test database for alias 'default'...
System check identified no issues (0 silenced).
..................<Response status_code=200, "application/json">
....[2020-02-02 16:55:15,048] log: WARNING - Bad Request: /api/v2/project/
[2020-02-02 16:55:15,068] log: WARNING - Bad Request: /api/v2/project/
[2020-02-02 16:55:15,090] log: WARNING - Bad Request: /api/v2/project/
```

**Comment by nanometrenat** [comment]
@GregoryHorvath is this still an issue?  know there's been lots of work on 3W recently (and I think the project endpoint relates to 3W yes?  Cheers!

**Comment by GregoryHorvath** [comment]
@thenav56 I ran the above mentioned command by Zoltán, this is still happening. Can you confirm please if the test is faulty or we actually have some bad logic there?

**Comment by thenav56** [comment]
@GregoryHorvath @nanometrenat 

The warnings are for the tests where the test case sends invalid data and the server responds with Bad Request.

https://github.com/IFRCGo/go-api/blob/66655b45faa2bd0333142cecc276a4cc9a3fa750/deployments/test_views.py#L102-L117

**Comment by GregoryHorvath** [comment]
@thenav56 Thanks for the clarification, sorry I didn't have the time yesterday to check it really.

@nanometrenat I believe this is closable then, and was already a false issue.
