### ISSUE TITLE
Do not allow country_id to be null when submitting PER form

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#619]
Relates to https://github.com/IFRCGo/go-frontend/issues/973

TODO:

 - [ ] Set `country_id` as NON-NULLable in the models
 - [ ] Create migrations
 - [ ] Modify view code to return an error if country_id is not sent from the frontend

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/865 (General PER ticket)
