### ISSUE TITLE
Commits missing from PROD

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-api#623]
@batpad 
These are the main commits missing from Prod, basically everything until today from the first item in this list:
- https://github.com/IFRCGo/go-api/commit/af32579640568f24b794de46f9a0caa4de1602c7
- https://github.com/IFRCGo/go-api/commit/8e51c5589e3e9b54d8a34ff1dd35d0ba9ab254e6
- https://github.com/IFRCGo/go-api/commit/0fd20382f3f8a92adebef7c4217685213a68102f
- https://github.com/IFRCGo/go-api/commit/fed79d54115d57e733b940c78792e662c289e2a0
- https://github.com/IFRCGo/go-api/commit/8ccfdb63db2d55a704dd18349285f6e4fabbd463
- https://github.com/IFRCGo/go-api/commit/89b3df764f51326c4520414589ff2be4b607789b
- https://github.com/IFRCGo/go-api/commit/dcebff48d683ddc845c35a09c4337722ac6290f2
- https://github.com/IFRCGo/go-api/commit/04a8dc7cfe89934a8ad7fd1c3361a8d9099b7cbe
- https://github.com/IFRCGo/go-api/commit/efa1b5d926798d196d6f75a1bf9980c4fd0482d8
- https://github.com/IFRCGo/go-api/commit/3bd0ffb6ee778fd5083bb63f0cbc5bdedacd18f3
- https://github.com/IFRCGo/go-api/commit/7c1b07f1914aa93ee011e556be54329f91a5d7de
- https://github.com/IFRCGo/go-api/commit/39e1c0471e265469fd73d1deb5cf20eab11ed0cb
- https://github.com/IFRCGo/go-api/commit/3b77d6bf733918ba29f4f33722eafc8a4be4f940

The changes in a nutshell:
- SMTP error/mails missing probable fixes (the cause of mails missing is still not clear, I was suspicious of the 30 mails/minute limit of MS Exchange, but I tried with 48 emails a bunch of times and I got all of them)
- Notification email design fixes
- Appeal Documents ingestion fix (removed filter)
- Django update from 2.2.9 to 2.2.10
- API url paths fixed (they got mixed up when you checked them from `/api/v2`)
- Followed Event notifications refactored so it should use only 1 connection to send them all
- Fallback Country queryset

**Comment by batpad** [comment]
@GregoryHorvath sorry for the delay here. From my end, this looks good to deploy. :+1:

**Comment by nanometrenat** [comment]
These changes have just been deployed to Production, so closing this release ticket.  Will close the relevant underlying tickets once they've been monitored in live.  Thanks :)

**Comment by nanometrenat** [comment]
Re the email notifications handling, this is being tracked under Service Desk tickets rather than through Github:

- SRV-16958 re surge notifications (which is what led to the changes made in commits above)
- SRV-18335 re new field report notifications (logged today, post-release)

@LukeCaley refs above FYI
