### ISSUE TITLE
[PROD] notification email handling integration improvements

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#625]
## Issue
There have been recent instances where notification emails from GO have not been transmitted reliably.  This is due to the thresholds on O365 SMTP.

ITD have proposed instead integrating with an Email API Service that will handle the logic to keep email sending between the limits and also to resend failed emails if required.

More detailed API/integration specs to come from ITD, then confirmation of approach/prioritisation/timing from @LukeCaley - this ticket is just to track any potential decisions and related work to address this.

## Historic tickets

- SRV-16958 re surge notifications (which is what led to the changes made in commits in https://github.com/IFRCGo/go-api/issues/623)
- SRV-18335 re new field report notifications (logged 4 March, post-release)

@GregoryHorvath tagging you FYI

**Comment by LukeCaley** [comment]
Message from IFRC ITD: @szabolcsgajerifrc "We are using our own email sending package solution developed for .NET applications which handles the limitations (partially, but missing ones can be included with small development) and tracking/recording the email sending process and on a failure it re-sends the email X times (based on configuration).

Now a package only and used for the applications as a built in module not yet running as an Email sending API service ... IFRC IT @szabolcsgajerifrc to build an API service from it so GO could use also for mass email sending."

**Comment by GregoryHorvath** [comment]
Reopening because of automated closing happened via PR.

**Comment by GregoryHorvath** [comment]
@LukeCaley I just got the production parameters from Szabolcs earlier and tested the mail sending locally and it worked fine.

Meanwhile it's already deployed to the staging site so it could be tested. If everything works well there then we're ready to push this to production (it would include some other changes too, like the vanity URLs).
