### ISSUE TITLE
[ENH] Back end Situation report - search function

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#633]
Request for a tweak to back end screen please

https://goadmin.ifrc.org/api/situationreport/

At the moment this lists the Situation Reports but I can't search for a specific report.  On this page please add

- ability to search by name or by event/emergency
- display additional columns on the page to show Event, Type, Visibility,

**Comment by GregoryHorvath** [comment]
@nanometrenat Deployed the changes to `staging`, can be tested there.

**Comment by nanometrenat** [comment]
Thank you that's brilliant - test passed in staging (can search by emergency name or doc name, and extra columns are there).  This will be super-useful!

**Comment by nanometrenat** [comment]
Looking great in Production so closing - thanks a lot!
