### ISSUE TITLE
Allow users to choose if a change should trigger notifications

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#637]
**Is your feature request related to a problem? Please describe.**

This relates to https://github.com/IFRCGo/go-frontend/issues/1011 - breaking the part about allowing users to decide whether a change should trigger notifications into a separate ticket.

Often, users are spammed with notifications for every edit / change to something. We want users to be able to choose to not notify users on certain edits.

**Describe the solution you'd like**

When the user is editing an Emergency, they should have some option of ticking something like `Don't Notify` which, if they select, will not trigger sending of notifications.

@GregoryHorvath summed up the challenge here:

> The main issue here would be that we're not sending notifications on the go (haha pun), but checking every 5 minutes if there were any changes/new records and notifying the subscribers in a bunch. So even if one would uncheck the notify box if they're not waiting to the next 5th or 10th minute to check it back for the future or something, it wouldn't do much. This needs some brainstorming.

Let's use this issue to brainstorm and figure out how best to implement this feature where we can allow users to signify some edits as not triggering notifications.

cc @LukeCaley @GregoryHorvath

**Comment by LukeCaley** [comment]
Feature to be prioritised due to volume of documentation related to COVID, i.e. technical guidance docs.  

Ideally there would be means from the back-end to select `notify subscribers **now**` and `notify subscribers in **daily update**` depending on urgency of the update.

There may be need for further design work on the notification email output here, cc @yellowumbrella-design

**Comment by GregoryHorvath** [comment]
Had a call with @mmusori, and agreed that as a first approach we'd have a button at the top right of each Emergency/Event's page for superusers to send out a notification to the subscribers.

cc @LukeCaley

**Comment by mmusori** [comment]
Pushing  Notifications.

Additional developments requested beyond the daily update for any changes to an emergency. 
There is a need to have a functionality to allow for pushing of a notification out immediately if there is important information that needs to be communicated. Potential solutions
1.	Have a button at top of a specific emergency page which is only visible to “super users/Regional IMs”. The button will read “Send Notification now”. So, if “important” changes have taken place a super-user will go in and “click/push” the button to immediately send a notification email.
 
2.		Have an additional (4th) save button at the bottom of a specific emergency. This button would be a  “Save and notify” button. This gives the authorisation to the person who modifies the emergency to either just save changes or to save changes and send a notification of the changes.


3.	Have a button at the top of Home/Api/Emergencies page next to actions. With this button you can select multiple emergency to push notifications immediately. This functionality will only be visible to Super-user/Regional IM. 
 

**Currently the thinking is to go with option one.**  Need to confirm decision on who should be able to push unscheduled notifications.

**Comment by GregoryHorvath** [comment]
The current process of the Followed Event notifications:
* checking if the current time is between 6:54-6:59AM, and **if it is**:
  * gathering Emergencies which changed in the last day and have a timestamp in the `previous_update` from 1 day before
  * looping through the subscribers and notifying each for all changed Emergencies they're subscribed to
* **else:** checking every 5 minutes if Emergencies changed and if they did AND they **don't** have a `previous_update` from 1 day before
  * looping through the subscribers and notifying each for all changed Emergencies they're subscribed to

**Comment by GregoryHorvath** [comment]
@mmusori @teklal Since we have 3W in production, this just got deployed to staging, so ready for testing.

The button should be showing up for `superusers` at the top of the Emergencies' edit page.

**Comment by teklal** [comment]
Tested and currently works as described below:
- "Notify subscribers now" button appears on admin page of emergency
![image](https://user-images.githubusercontent.com/52411237/81163959-d3849c00-8f8f-11ea-8d1f-e7aaf09a41b2.png) 
- when clicking that, a _generic_ notification will is sent to users that have subscribed to the emergency through the frontend _and_ the user that created the field report that generated the emergency page (currently there is no way for that user to unsubscribe from these notifications)
- button only appears for superusers

Q:
- Will the users still receive the daily followup for these emergencies? @GregoryHorvath 

Things to discuss (@mmusori, @LukeCaley) :
- What should the notification email look like? Currently it is very generic and there is no information about the actual changes that were made (this is the case for the change notification emails we already send as well)
- As this is currently only a superuser thing, the pool of people being able to use this is very limited (as desired) - not even our regional IMs are superusers. Should this instead be made to be a permission that can be assigned or regional IMs be made superusers (if they are to be able to use this)?

**Comment by GregoryHorvath** [comment]
> ...
> Q:
> 
> * Will the users still receive the daily followup for these emergencies? @GregoryHorvath
> ...

@teklal Good catch! Currently the button does a 'Save' as well so it updates the `updated_at` which is used for this. I think it shouldn't do a 'Save' at all, so I missed that sorry for that. But after this is fixed it should only trigger the emails and touch nothing else.

**Comment by GregoryHorvath** [comment]
Just replying to the above comment, this got deployed to production knowing the above because after checking it shouldn't affect the daily notifications.

**Comment by mmusori** [comment]
We need a new ticket for the contents of the both the "push notification" and the modification email notification. It was part of the notification requirement which was  not built at the time. If the permissions are now working to your satisfaction @teklal we can have the push notification as a permission and have that as part of this new ticket.
