### ISSUE TITLE
Change fields' type to be Rich Text Editor types

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-api#667]
Branched out from: https://github.com/IFRCGo/go-frontend/issues/1011

@nanometrenat @teklal https://github.com/IFRCGo/go-frontend/issues/931#issuecomment-610302298
Please provide us with a list of fields which should be changed to be RTE types.

## Checklist (after backend changes)
- [ ] adjust frontend to parts too, to handle the new RTE fields' HTML
- [ ] `if` frontend RTE implementation was done before this, adjust the serializers if needed

**Comment by teklal** [comment]
- Surge alerts, the "Message" field https://prddsgocdnapi.azureedge.net/notifications/surgealert/add/ 
here the messages that are shared already most of the time have bulleted lists but they don't show on the frontend in the desired way
- in field reports people sometimes add links to the "source" field so it would be good to be able to support the sharing of links there and having them properly show as links on the frontend too
- snippets https://github.com/IFRCGo/go-api/issues/670

I'll add more when I think of other places.

**Comment by GregoryHorvath** [comment]
Duplicate of: https://github.com/IFRCGo/go-api/issues/670
