### ISSUE TITLE
Create Django admin page for maintenance of whitelisted NS domains

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#669]
At the moment adding new email domains to the list of whitelisted goes usually as follows
- there is an email by a user to the IM email to tell about problems signing up
- someone from IM team contacts a developer to add the domain(s) to the lists
- there has to be a push to prod to make the emails work for registration

To make handling these domains easier in the future and avoid having to push things to production, it would be good to have a Django admin page for superusers to maintain the domains.

xref: https://github.com/IFRCGo/go-frontend/issues/556

**Comment by teklal** [comment]
This is something that has been suggested by both Zoltan and @GregoryHorvath.

**Comment by GregoryHorvath** [comment]
Deployed to staging.

@teklal

**Comment by nanometrenat** [comment]
This was deployed to Prod just now.  Thanks!  Further tweak required please, to ensure it checks the entirety of the domain after the @ (i.e. not just a partial string compare).

e.g. asdfadsf@redcross.org.yyyyy

**Comment by nanometrenat** [comment]
@teklal will leave it to you to close when happy with the interface - apparently the issue in the above comment was pre-existing ;)

**Comment by GregoryHorvath** [comment]
> @teklal will leave it to you to close when happy with the interface - apparently the issue in the above comment was pre-existing ;)

@teklal @nanometrenat That issue should be solved with the next deployment (hopefully happening today).

**Comment by GregoryHorvath** [comment]
This is on production already, closing.

**Comment by teklal** [comment]
Was going to wait for the further tweak to be in prod before closing but all good - the major thing outlined in the ticket is already in prod and working. Thanks!

**Comment by GregoryHorvath** [comment]
> Was going to wait for the further tweak to be in prod before closing but all good - the major thing outlined in the ticket is already in prod and working. Thanks!

Oh sorry for that I missed that's in this ticket still, it should be deployed by tomorrow morning though. Reopening until that.

**Comment by teklal** [comment]
Closing as now everything mentioned in this ticket and comments is in prod. Thanks!
