### ISSUE TITLE
Better logging and notifications for 500 errors

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#672]
**Is your feature request related to a problem? Please describe.**

We have seen a few issues recently of the backend returning 500 errors in certain cases. A 500 error ALWAYS indicates a problem / uncaught error on the backend, and site admins should always be aware and notified of any 500 errors occurring.

**Describe the solution you'd like**

Ideally, I'd have any 500 errors on the production site send emails to site admins with a detailed stack trace of the error. This should be fairly easy to setup. If we get too much email, we can move it to a logfile, but make sure we check this regularly. I would definitely like to start with the email solution first.

TODO:

 - [ ] Add configuration in Django settings to email traces for 500 errors to SITE_ADMINS
 - [ ] Create a dummy URL that generates a 500 error to be able to test
 - [ ] Test that it attempts to send email locally (logs to console or so)
 - [ ] Test that actual emails are received for the 500 error on staging

@GregoryHorvath would be great if you had some bandwidth to take this on, else either @geohacker or I could look. Thanks!

cc @nanometrenat

**Comment by GregoryHorvath** [comment]
@batpad @geohacker Based on the logs it seems that only the `/api/v1/es_search=?keyword=XY` endpoint returns the `500` errors. Which is Elasticsearch.

**Comment by nanometrenat** [comment]
Hi team, as per conversation in Teams (and based on the HAR file from staging the other day) I can confirm that the 500 errors that are causing #1129 are being returned from the Event API NOT from elasticsearch e.g. https://dsgocdnapi.azureedge.net/api/event/3833/change/

**Comment by batpad** [comment]
@nanometrenat :+1: 

Let's use this ticket to resolve the larger issue of not receiving good enough and timely debugging information for 500s that occur. We really should be tracking 500s before they are reported by users.

@nanometrenat will follow up on this specific issue in #1129

**Comment by thenav56** [comment]
@batpad 

Have we consider using 3rd party services like https://sentry.io/ ([free for opensource projects](https://sentry.io/for/open-source/)). They provide event trail, grouping, context, version, etc which are highly helpful to understand and solve errors.

**Comment by batpad** [comment]
> Have we consider using 3rd party services like https://sentry.io/ (free for opensource projects).

@thenav56 did not know sentry.io is free for open source projects - a proper log management tool would be ideal - this is the approach I'm used to using - configure `gunicorn`  to just log everything to `stdout` and have some process to ship that to a 3rd party logging tool. @thenav56 is this something you've setup before with Django projects? If you're able to help here, that would be great. Happy to help evaluate 3rd party logging tools, or check if Azure has something that we can use. Let's try and estimate how much work that might be, and if it might still be worth it, in the interim, to setup the email solution if that's a lighter lift?

**Comment by thenav56** [comment]
@batpad We are using sentry.io in Deep. The setup is pretty straightforward. Start-up guide is [here](https://docs.sentry.io/platforms/python/django/).
For DRF, using a custom global exception handler is preferred like [this we are using in Deep](https://github.com/the-deep/server/blob/develop/deep/exception_handler.py#L23-L33) specifying in [settings.py](https://github.com/the-deep/server/blob/develop/deep/settings.py#L212). [More here](https://github.com/the-deep/server/search?l=Python&q=sentry).

Also, it provides email/slack integration. This one looks like Microsoft teams [integration](https://appsource.microsoft.com/en-us/product/office/WA104381566?src=office&tab=Overview) not sure though.

**Comment by batpad** [comment]
@thenav56 this looks perfect. Perhaps we can give this a go on staging early next week?

**Comment by thenav56** [comment]
> @thenav56 this looks perfect. Perhaps we can give this a go on staging early next week?

@batpad Sounds good.
But, we would need to create an account first by applying for open source here https://sentry.io/for/open-source/.

**Comment by GregoryHorvath** [comment]
@batpad @thenav56 There is a quick-and-ugly solution in the above PR for this if we want to push that for this week's release.

**Comment by nanometrenat** [comment]
Hi there just commented on https://github.com/IFRCGo/go-frontend/issues/1129 - did something appear in the logs?

**Comment by GregoryHorvath** [comment]
Having emails sent out for every 500 would be a bit of an overkill, maybe we could figure out a way to generalize and gather up all those errors at the end of every day and send them out to the IM address probably @batpad ? Should we ticket this (and that Sentry stuff) out separately and close this one.

As mentioned above I mostly just see the Elasticsearch 500s, and there are also some weird requests like, which are not "real" 500s but feels more like if a bot tried to hit some pages:
```bash
[26/Aug/2020:21:57:18 +0000] "POST /es/api/region/1/change/ HTTP/1.0" 500 27 "https://dsgocdnapi.azureedge.net/es/api/region/1/change/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
```

**Comment by batpad** [comment]
Closing in favour of https://github.com/IFRCGo/go-api/issues/1569
