### ISSUE TITLE
Return groups in user profile end-point

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#702]
To support the Resilience Dashboard and other applications that may want to interface with GO users and permissions, it would be useful to be able to query the groups a user is part of as part of their authenticated profile.

I.e. for a valid token, return, in addition to profile information, an array of groups, with group name and group id, for groups that a user is part of.

cc @GregoryHorvath @kamicut

**Comment by batpad** [comment]
@kamicut tagging you as it maybe a good first issue when we're doing backend onboarding.

**Comment by GregoryHorvath** [comment]
@batpad is this still relevant / needed?
