### ISSUE TITLE
[Staging] and probably [Production]: 3W bulk uploads

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-api#703]
I've been trying to upload the following file to Staging Environment as csv. 
[Partner_3W_COVID_Africa_BulkUpload.zip](https://github.com/IFRCGo/go-api/files/4592136/Partner_3W_COVID_Africa_BulkUpload.zip)

My current issues are
- What are the correct headers (Reporting NS? Supporting NS?)
- How do we support multiple tags if all fields are separated by commas?

Could you try to check what changes are necessary in order to get this file through to staging (and later to production).

Thanks!

**Comment by thenav56** [comment]
@lauripynnonen The correct headers are `Supporting NS`.

For the import CSV structure, we used the 3W export as a template.
For references on other headers, headers used in go-api (search for `row['`) https://github.com/IFRCGo/go-api/blob/5d6a2f7da79a1f4583602f6d18eba16ccd0dd66e/deployments/forms.py#L73-L116  This is referenced from [go-frontend](https://github.com/IFRCGo/go-frontend/blob/cafab871ef124b54ee30044546c9f1d07f31f439/app/assets/scripts/views/ThreeW/export-headers.js#L1-L86) (look for `title`).

The current issue should be related to using **semicolon** **delimiter**. Currently, it only supports comma.  Try using **comma**. If it's not feasible then we can add a **field** in the **bulk import form** for specifying delimiters. Let me know.

**Comment by lauripynnonen** [comment]
operation_type=operation_types[key_clean(row['Operation type'])], 
programme_type=programme_types[key_clean(row['Programme Type'])], 

I think my latest errors came from the Operation type vs Programme Type - the latter Type has a capital T whereas the Operation type is lower case. I changed that to my csv and now when I try to upload this (extracted) [Africa-Import-comma.zip](https://github.com/IFRCGo/go-api/files/4592654/Africa-Import-comma.zip) I get an error 
Traceback (most recent call last):
  File "/home/ifrc/go-api/deployments/forms.py", line 128, in handle_bulk_upload
    projects = self._handle_bulk_upload(request.user, file)
  File "/home/ifrc/go-api/deployments/forms.py", line 101, in _handle_bulk_upload
    status=statuses[key_clean(row['Status'])],
KeyError: '52000'

Which I assume is caused by using the comma to separate Tags and cells? This would make the Budget field leak to the Status field right? Or is the difference of cell and tag separators the Tag-comma-**space**-tag vs cell-comma-cell-comma-cell etc? Do I need to add spaces?

**Comment by lauripynnonen** [comment]
And apparently some country names have commas in the - for example "South Sudan, Rep. Of"

**Comment by thenav56** [comment]
@lauripynnonen 
You can use string delimiter like `"` to fix the breaking issue.
There is options from **LibreOffice**, there should similar options for Microsoft excel.
Also, try to use `Unicode (UTF-8)` for the character set.
![image](https://user-images.githubusercontent.com/7059255/81377313-f2686700-9124-11ea-8f8f-0b9c9ae4d9de.png)

For the names of the columns, they are replica from the go-frontend codebase. Should we make changes to them so that they are consistent with both structure and import/export format? Let me know.

Also, Most of the columns are required. And all the numerical values are Integers (so decimal numbers will throw errors).

**Comment by lauripynnonen** [comment]
@thenav56 Thanks! I think it'd be great to unify the headers (Supporting NS - Reporting NS, Operation type - Operation Type). 

I'm currently getting the following error which is quite hard to debug with this file: 
[Partner_3W_COVID_Africa_BulkUpload-edits.zip](https://github.com/IFRCGo/go-api/files/4609155/Partner_3W_COVID_Africa_BulkUpload-edits.zip)

Traceback (most recent call last):
  File "/home/ifrc/go-api/deployments/forms.py", line 128, in handle_bulk_upload
    projects = self._handle_bulk_upload(request.user, file)
  File "/home/ifrc/go-api/deployments/forms.py", line 86, in _handle_bulk_upload
    project_country = project_district.country
AttributeError: 'NoneType' object has no attribute 'country'

**Comment by thenav56** [comment]
@lauripynnonen The error is a case where the given district is unavailable/missing from the database, might be a spelling mistake or missing in the database.

For these cases either we validate from the server-side or validate before uploading (by using a template similar to the one we did in https://github.com/IFRCGo/go-frontend/issues/1197)

I can work on the server-side validation so that overall errors are provided after the import failure. Let me know if this sounds good.

**Comment by lauripynnonen** [comment]
I think server side validation and more specific errors would make this a lot more user friendly. The issue is the scope that moved from "IM admin uploading previous projects to Go" into "NS bulk uploading all their projects into Go"

**Comment by nanometrenat** [comment]
@lauripynnonen FYI when testing it's worth remembering that the country/subnational region data in Staging is not the same as the data in Prod.  xref our old friend https://github.com/IFRCGo/go-frontend/issues/938

**Comment by thenav56** [comment]
@lauripynnonen We have made some changes to reflect validations. Also added Disaster Type and renamed Supporting NS - Reporting NS, Operation type - Operation Type.
You can check them out in tc staging server https://go-api.togglecorp.com/deployments/project/.

@lauripynnonen @nanometrenat Thanks for let us know about the issue. For this we have added a `Import Template` button which will provide a template with valid values for the import. This way users can do a local validation before submitting to the go-api. The template is created according to https://github.com/IFRCGo/go-frontend/issues/1197

**Comment by thenav56** [comment]
@lauripynnonen Also empty or 'countrywide' Regions value will indicate countrywide which will assign all the district for given country to that Project.

**Comment by lauripynnonen** [comment]
@thenav56  This is so cool! Thank you! I tested with my file and it went in perfectly.

I assume the export syntax no longer matches the import right? Might have to create a feature request for that...

**Comment by nanometrenat** [comment]
@lauripynnonen I see this is in "Done" and I believe the latest change is in Production - so can this ticket be closed or is there further work to do still?  Cheers all!
