### ISSUE TITLE
[PROD] COVID FR: fields that do not appear on the frontend are required fields in the backend

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#710]
## Issue
When editing a field report through the Django admin page the system does not allow saving the edits without filling in some required fields. The problem here is that these are fields that do not appear and hence cannot be mandatory when filling the field report through the frontend.

The issue appears when a user has written text into at least one of the boxes below on the third page "Actions" of the field report:

![image](https://user-images.githubusercontent.com/52411237/81796684-143f6080-950e-11ea-946a-431d8657a499.png)

On a "normal"/epidemic field report there would be checkboxes for the user to choose actions with these fields but not with the covid report.

On the backend however the choosing of actions for these fields appears as required:

![image](https://user-images.githubusercontent.com/52411237/81797123-a6476900-950e-11ea-8164-69e30a63c8bf.png)

## Steps to reproduce
(for testing use staging envrionment) Fill a covid field report and write text in the IFRC and Movement activities boxes. Once submitted, go to the backend to edit the report and try saving it.

## Impact
There is currently a lot of "gardening" happening around field reports. In particular related to fixing what emergency the field report is linked to. Hopefully with more information and training to users this will not be as big of a problem in the future anymore and less gardening will be required.

## Is there a workaround?
Most of the edits can be done through the frontend. The problem with editing through the frontend is that there is no audit trail/history of the edits made that could be seen on the backend, and the information about the user submitting the report changes to the "gardener's" user account (the original can still be seen in the contacts as "Originator")

**Comment by nanometrenat** [comment]
For clarity (for those not involved with COVID-FR build), this issue is caused by the explicit request to allow a scenario on the front end where narrative is input but no actions are ticked - https://github.com/IFRCGo/go-frontend/issues/1160#issuecomment-623393386  Apols that we didn't realise back end would need adjustment at same time...

**Comment by GregoryHorvath** [comment]
Next release will solve this with: https://github.com/IFRCGo/go-api/pull/739/commits/a573772a309ce1368bea60bec71dc39f88c9e34f

**Comment by teklal** [comment]
This is working now!
