### ISSUE TITLE
Translation: Connect with the auto translation service

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-api#720]

**Comment by LukeCaley** [comment]
As of 27/08 IFRC ITD agreed to connect to the AWS service.  Testing parameters to be outlined here or in a Xref ticket @guipizzini @frozenhelium

**Comment by tovari** [comment]
Parent ticket about translation efforts: https://github.com/IFRCGo/go-frontend/issues/934

**Comment by tovari** [comment]
Closing it as we will have a new one about User content translations.
