### ISSUE TITLE
Translation: Modify the existing APIs to support the translation

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-api#722]
### Potential test cases

* Check if language is not provided through Accept-Language header, API fallbacks to the English for backward compatibility (i.e. the similar behaviour as before)
* Check if language is provided through Accept-Language headers, translated fields should have requested language content. Registered fields for each model are as follow: 
```
https://github.com/IFRCGo/go-api/tree/develop/api/translation.py
https://github.com/IFRCGo/go-api/tree/develop/main/translation.py
https://github.com/IFRCGo/go-api/tree/develop/notifications/translation.py
https://github.com/IFRCGo/go-api/tree/develop/deployments/translation.py
```
**Note:** Auto-translation will not work until the platform is set up with the AWS translation service. So for now, entity add/edit will not trigger auto-translation, resulting in an empty value for non-english language fields.

For current content in staging, we have mock auto-translation by adding language prefix. This will not be the behaviour for add/update actions. For eg:
For, `summary='This is a test'`
```
- summary_es='(es) This is a test'
- summary_fr='(fr) This is a test'
- summary_ar='(ar) This is a test'
```

**Comment by frozenhelium** [comment]
We've tested and verified this from our side.

**Comment by guipizzini** [comment]
Testing completed with success
