### ISSUE TITLE
Translation: Create API endpoints to load and save the language strings

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-api#726]
Note: The strings are stored in the plain object in the frontend

Endpoint suggestion
```/api/v2/lang/<locale>/```
Example:
- `/api/v2/lang/en/` for English
- `/api/v2/lang/fr/` for French

**Comment by frozenhelium** [comment]
### This should work in conjunction with https://github.com/IFRCGo/go-frontend/issues/1240

**Comment by tovari** [comment]
To save:
/api/v2/language/<language_code>/bulk-action/
 
To load:
/api/v2/language/<language_code>/
