### ISSUE TITLE
[PROD] CSV export from API endpoints sometimes result in a blank page

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-api#738]
## Issue
Trying to download a resultset to CSV from an endpoint of the API (ex. `/api/v2/field_report/`) sometimes leads to a blank page with no download. The HTTP status is still 200.
Usually when the resultset has more than 1 page it works, but in some of the cases where there's only 1 page it returns the blank page only.

## Steps to reproduce
- https://goadmin.ifrc.org/api/v2/?format=csv doesn't work
- https://goadmin.ifrc.org/api/v2/field_report/?dtype=2 does

## Dev. note
If the default csv renderer in `settings.py` is set to:
- `PaginatedCSVRenderer` it occasionally downloads 1 page of data, but multiple paged ones work
- `CSVRenderer` it never downloads multiple pages of data, only 1 page at a time

## Expected behaviour
All should work just as the JSON ones do.

## Is there a workaround?
Download it into a JSON and convert it to CSV with other tools.

**Comment by GregoryHorvath** [comment]
@thenav56 Found ([PaginatedCSVRenderer](https://github.com/mjumbewu/django-rest-framework-csv/blob/master/rest_framework_csv/renderers.py#L241-L242)) that the CSV download doesn't work if the:
- response doesn't have the 'results' array _or_
- response has an empty 'results' array
```
{
  ...
  "results": [],
  ...
}
```

@guipizzini Please share which endpoints didn't work with the CSV download?

**Comment by GregoryHorvath** [comment]
> @thenav56 Found (PaginatedCSVRenderer) that the CSV download doesn't work if the:
response doesn't have the 'results' array or
response has an empty 'results' array

@frozenhelium @thenav56 On this note. Is it sensible to just adjusting the package's code and handle this there _if needed_? Since it is used here, I don't know if there's any other (better) way to handle it: https://github.com/IFRCGo/go-api/blob/5ce0122bba707239b5de0cc433a2cde6883ce7fd/main/settings.py#L74

**Comment by thenav56** [comment]
> > @thenav56 Found (PaginatedCSVRenderer) that the CSV download doesn't work if the:
> > response doesn't have the 'results' array or
> > response has an empty 'results' array
> 
> @frozenhelium @thenav56 On this note. Is it sensible to just adjusting the package's code and handle this there _if needed_? Since it is used here, I don't know if there's any other (better) way to handle it:
> 
> https://github.com/IFRCGo/go-api/blob/5ce0122bba707239b5de0cc433a2cde6883ce7fd/main/settings.py#L74

@GregoryHorvath Yeah, we can always create a custom CSVRenderer which will process both `results` and if it's missing then the whole response. And add that to the settings.py drf configuration.
Let me know if you need any help.

**Comment by GregoryHorvath** [comment]
With the latest changes to the CSV exports and query optimizations, this shouldn't be an issue anymore. Closing for now.
