### ISSUE TITLE
[PROD] IFRC users not getting IFRC permissions

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#741]
## Issue
According to the doco on Teams, there is a regular job that runs the https://github.com/IFRCGo/go-api/blob/master/api/management/commands/revoke_staff_status.py#L68 script and assigns relevant users the "IFRC Admin" permission (based on email address and a couple of other things).

It seems that assignment is not currently happening - script stuck - so a number of active users with 
IFRC email addresses can't see documents etc. uploaded with visibility = IFRC

## Steps to reproduce
In production, when a new active user is created with ifrc.org email address they should (after a period of time, and if not a super user) be automatically assigned the "IFRC Admin"

## Related feature
xref https://github.com/IFRCGo/go-frontend/issues/889 re Improve Signup Workflow

## Impact
390 IFRC users - can't see the IFRC only docs

**Comment by teklal** [comment]
This seems to be working now!
