### ISSUE TITLE
Web Data Connector for GO - Tableau

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-api#743]
We need to build a Web Data Connector (WDC) to connect the GO API to Tableau. This should be a relatively straight forward task. In IFRC ESSN programme it took around 2 weeks to develop the WDC. Here a few links as a reference. No further specs are required on our end, we would like to have the whole API end points being pulled with the WDC.

https://github.com/tableau/webdataconnector

https://help.tableau.com/current/pro/desktop/en-us/examples_web_data_connector.htm

https://public.tableau.com/en-us/s/blog/2017/07/how-create-web-data-connector-beginners-approach

https://github.com/tableau/webdataconnector

**Comment by batpad** [comment]
@guipizzini @frozenhelium - do we know whether this is something that @frozenhelium and team will be able to work on?

**Comment by frozenhelium** [comment]
@guipizzini @batpad lets quickly discuss this sometime

**Comment by guipizzini** [comment]
This has been paused upon internal agreements and discussions so that we can wait the improvements that are occurring on the API structure.

**Comment by GregoryHorvath** [comment]
Had a discussion with @thenav56 @batpad that we could also do it totally separately as a Github site as it works for The Deep project, so it wouldn't affect the API development at all.

**Comment by nanometrenat** [comment]
This link is to the KoBo WDC btw:  https://github.com/kobotoolbox/kpi/issues/2062

**Comment by nanometrenat** [comment]
This link is to info about the KoBo WDC btw:  https://github.com/kobotoolbox/kpi/issues/2062

**Comment by guipizzini** [comment]
We've tested the WDC with @GregoryHorvath and it is working fine and pending the deployment of other tickets. cc @batpad @LukeCaley

**Comment by GregoryHorvath** [comment]
@guipizzini Deployed the GO API changes to staging. All https://ifrcgo.org/tableau-wdc/ endpoints should now be testable.

**Comment by LukeCaley** [comment]
@GregoryHorvath @batpad could you update on the  deployment plan for this and whether there are any further developments / QA required? @guipizzini

**Comment by batpad** [comment]
@LukeCaley this was deployed to staging, and was tested with the Tableau WDC "Simulator", but there seem to be some issues with actual Tableau. Hopefully this is quick to fix once @GregoryHorvath is back next week.

**Comment by guipizzini** [comment]
I fully agree - as shared on the weekly call earlier this week, that we conducted testing. This is facing issues and requires some love from @GregoryHorvath once he is back. I have a meeting already scheduled with him and @batpad for next week.

**Comment by GregoryHorvath** [comment]
Updated all of the endpoints and tested with Tableau Public for Windows. They should be working now. The target is still the **staging** GO API for testing and only gets the public (without auth) data as of now.

**Comment by LukeCaley** [comment]
@GregoryHorvath based on the GO call 31/08 is this now ready to move to Ready for UAT?  
@guipizzini could you explain the elements to be tested here and @batpad  to add any known risks associated with this being rolled into the next release?

**Comment by guipizzini** [comment]
This has moved to UAT. Testing was completed and the Tableau WDC returns expected behavior in Tableau.

What is to be tested:

1. Import the Tableau WDC into Tableau
2. Ensure all tables from the GO API return values into Tableau
3. Test that the querying of GO API values functions correctly in Tableau

Please note that all of this is working properly and it has been agreed with @GregoryHorvath and @batpad that the WDC for Tableau is a low risk component for the upcoming release and that we should proceed in pushing into production.

**Comment by batpad** [comment]
@GregoryHorvath does it make sense to make a separate issue for supporting authentication and then can you close this one?

**Comment by GregoryHorvath** [comment]
@batpad Already did https://github.com/IFRCGo/tableau-wdc/issues/1, this is closeable :slightly_smiling_face:
