### ISSUE TITLE
Document development setup for elastic search

### ISSUE THREAD

**Issue by kamicut** [IFRCGo/go-api#744]
To test certain features in the frontend that require elastic search, we must be able to have a local instance or a staging instance of elastic search. Currently there is no elastic search section in the setup documentation. 

What are the steps that are needed to have elastic search capabilities when testing the frontend? This could be resolved either through a local deployment of elastic search or an environment variable connected to a staging site.

**Comment by nanometrenat** [comment]
Noting that @GregoryHorvath has done some Elasticsearch doco in the GO Dev Teams space - great if the doco can be further enhanced and improved through additional contributions though!  Especially as I know there has been a lot of work in recent days e.g.  xref https://github.com/IFRCGo/go-frontend/issues/989 with some recent ES changes FYI  Cheers!
