### ISSUE TITLE
[PROD] 3W: searching for project by NS/country name not possible in the backend

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#756]
## Issue
When trying to search for a 3W project in the backend it only allows the user to search by project name. The name of the reporting NS appears in the list after the project name in parentheses but cannot be used in search. Neither is there a way to search by the country where the project is happening.

This makes checking things on the backend cumbersome.

## Steps to reproduce
Go to the 3W section in the backend and try searching by a country or NS name.
e.g. https://prddsgocdnapi.azureedge.net/deployments/project/?q=nepal
will not return any results although in fact there are a bunch of projects there and also reported by the Nepal RC (https://go.ifrc.org/countries/123#3w)

## Expected behaviour
Searching by NS and/or country name should be possible in the backend.

**Comment by thenav56** [comment]
@teklal Thanks for informing us know about the issue.

There is 2 approach to solve this issue.
1. Text from search field will be used to search using NS, country name and project title values.
2. Add dropdown filters on the right side for NS and country. Something like this but with NS and Countries filter.
![2020-06-03-191219](https://user-images.githubusercontent.com/7059255/83642146-2f156a00-a5ce-11ea-8aa9-aa56f57e0802.png)


Let us know which sounds good.

**Comment by thenav56** [comment]
@teklal We have pushed with side filter to staging. Let us know if you have any feedback.

https://dsgocdnapi.azureedge.net/deployments/project/
![2020-06-19-141128](https://user-images.githubusercontent.com/7059255/85113355-df25dc80-b236-11ea-9f84-c6e43878f9f9.png)

**Comment by teklal** [comment]
Thanks @thenav56! Sorry I forgot to get back to you, the side filters look good.

**Comment by nanometrenat** [comment]
@LukeCaley this was not in a project but I can see the changes for 2 above have already been released to Production - https://goadmin.ifrc.org/deployments/project/ now has the aforementioned dropdowns.

Presume part 1 still to be done - so that part will need to wait for 3W prioritisation.

**Comment by thenav56** [comment]
@nanometrenat Currently **Search field** is used to filter `Project` by name and **side filter** by `National Society` and `Country`. This way the filter is not coupled together giving more freedom to the user.
If this approach is not suitable then lets do as you suggest.

**Comment by nanometrenat** [comment]
@thenav56 thanks for the comment!  Apols that I misread the [comment](https://github.com/IFRCGo/go-api/issues/756#issuecomment-638197122) earlier - I thought the aim was to do 1 AND 2 but now see that point 2 was the intention so that's great.

@batpad this wasn't included in list of changes in release notes and wasn't on the board so was a "hanging" ticket.  However no further work to do so am closing as this is in Production now.  Cheers all
