### ISSUE TITLE
Fix permissions for private field reports on event API

### ISSUE THREAD

**Issue by kamicut** [IFRCGo/go-api#758]
https://github.com/IFRCGo/go-frontend/pull/1302 hides private field reports tied to emergencies when the user is not logged in. However, this is a style fix that does not deal with the underlying issue of permissions to the event API:

When a user is not authenticated, the event API will currently related field report data tied to the event. If a field report is marked as private, this does not affect the data returned from the API. A fix was proposed https://github.com/IFRCGo/go-api/pull/748 but rolled back because, to my understanding, it broke aggregations of the field report data displayed on the frontend.

The proper fix would be to:
1. rethink how the aggregations are calculated on the event, maybe moving them from the frontend to the backend
2. re-implement the permissions on field reports as demonstrated by @GregoryHorvath 

cc @batpad

**Comment by batpad** [comment]
Thanks @kamicut -

Currently, there are a number of values that get displayed on the frontend, that are all pulled from the "latest" field report submitted:

So, we need to:

 - enumerate what all these fields we need from the "latest" field report
 - have the backend return these fields under `latest_field_report` or so, and hide any other details about the field report, and not return information for any other field reports
 - switch the frontend to use these fields from `latest_field_report` (should be fairly straightforward)

@nanometrenat @mmusori - the business question here is - "Do we want to continue displaying these figures on the Emergency page from the 'latest' Field Report, or do we want to change the logic of how these figures are aggregated / displayed on the Emergency page?" - if it makes sense to go ahead with implementing the current logic, but have the data returned by the backend, we can go ahead with the steps outlined above, else we will need a separate ticket that defines how we want to change how we aggregate data from Field Reports onto Emergencies.

**Comment by nanometrenat** [comment]
@mmusori personally I think the above proposed approach sounds good - but obvs you would need to confirm if happy.  Also may need to check with our various external API consumers?

@batpad the page would need to of course also keep the existing logic to only show the recent FR fields if "hide attached FRs" is not ticked for that emergency!

@batpad I suspect the above proposed changes would go a long way towards solving the 3000 column issue in https://github.com/IFRCGo/go-api/issues/758#issuecomment-638637260 - so should presumably be worked on in conjunction!  Cheers
