### ISSUE TITLE
Countries API - add "type" to response (minor thing) and ideally as param

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#759]
Hi

Really sorry, I should've thought of this when logging https://github.com/IFRCGo/go-api/issues/671

At the moment when records are returned via https://goadmin.ifrc.org/api/v2/country/ we have no way of knowing whether the record is a Country or a Cluster or a Region or a Country Office etc. - this is in the dropdown on Django admin but not returned via the API.  At the moment we do a manual filter process in the country export but ideally we would just be able to filter by the Record type.

So, if you could please

1. return Record Type in the country API response (think here?? https://github.com/IFRCGo/go-api/blob/master/api/serializers.py#L51), and
2. (if not too hard/risky) please also add Record Type as a parameter in the request https://goadmin.ifrc.org/docs/#country-list
3. when we move FDRS codes from being hardcoded to being stored in the db (therefore maintained via Django admin) then these will need to be added to the response also https://github.com/IFRCGo/go-frontend/issues/940#issuecomment-592033183
4. While there, I have another question - what does the "search" param actually search, currently?  I can't get it to change the output in any way at all... it would be great if the search param searched at least country name, society name and the isos... if poss? Or add as separate params if preferred?  

Again, #1 above is the most important, and the only thing that would be great to have in the short term please.

THANKS

![image](https://user-images.githubusercontent.com/33625192/83800804-59d3f100-a6a8-11ea-91dd-87c6f5bfcb35.png)
xref https://github.com/IFRCGo/go-frontend/issues/938

**Comment by nanometrenat** [comment]
`1.` passed testing in staging - record_type now returned in both JSON and csv responses.  Noting that record_type is numeric rather than descriptive, but 1 = country-type record.

Be great to do `2.` also, but let's not delay the release for that ;)  Thanks!

**Comment by GregoryHorvath** [comment]
@nanometrenat `2.` was deployed to staging

**Comment by GregoryHorvath** [comment]
> 4. While there, I have another question - what does the "search" param actually search, currently? I can't get it to change the output in any way at all... it would be great if the search param searched at least country name, society name and the isos... if poss? Or add as separate params if preferred?

Most probably it is this you're referring to?: https://www.django-rest-framework.org/api-guide/filtering/#searchfilter
It would mean if we used the `search_fields` in the 'Views' - which are the queryable endpoints - we could specify there fields for that search param to search in.

**Comment by nanometrenat** [comment]
Closing as 1 & 2 are working well in Prod.  We can deal with 3 when FDRS data is integrated.

Separate ticket #790 logged for the "search" thing given that it's needing to be implemented wider than just this endpoint.  Thanks a lot!

**Comment by szabozoltan69** [comment]
There are two possibilities for searching.
One is on the admin web interface:
![kép](https://user-images.githubusercontent.com/6050643/141773441-da4fea36-df6a-43b7-b506-9e73ba4f5910.png)
- this one generates '/en/deployments/regionalproject/?q=something' -like api calls, and the other is the /docs -related one:
![kép](https://user-images.githubusercontent.com/6050643/141773759-2d0f77c2-9dcc-4f71-aad3-f67d68892e94.png)
 - which generates '/api/v2/regional-project/?search=o' -like api calls. I suppose this latter should be enhanced for other endpoints also.
