### ISSUE TITLE
Optimize DB queries for Events API end-point

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#763]
Relates to #708 

We should check the database queries being generated for the Events end-point, and use `.select_related` and `.prefetch_related` to reduce any excess queries.

In general, to do query profiling:

 - Ensure Django Debug Toolbar is working, I just merged https://github.com/IFRCGo/go-api/pull/682, we may need to test that it works under all local development scenarios.
 - Once Django Debug Toolbar is working, you can visit an API end-point like 
 - Click on DjDT toolbar icon on the top-right of the page, and go to the `Queries` tab.

Inspecting the queries and SQL generated should give you a good idea if any of the related object lookups are being done in a loop instead of being fetched along-with the initial query.

To optimize, we'd add `.select_related()` and `.prefetch_related` calls to the ORM call in the `get_queryset` method for the view, and then one can re-inspect the queries in the Django Debug Toolbar to verify that the number of queries and overall query times have reduced.

`get_queryset` method of the View: https://github.com/IFRCGo/go-api/blob/develop/api/drf_views.py#L251

Django docs: https://docs.djangoproject.com/en/3.0/ref/models/querysets/#select-related

**Comment by GregoryHorvath** [comment]
@batpad I think this should cover it: https://github.com/IFRCGo/go-api/pull/823 (already deployed to staging). What do you say I go around some other heavier ViewSets as well, like `FieldReport` and such, or should that be a different ticket?

**Comment by batpad** [comment]
@GregoryHorvath I had done some work on the FieldReport queryset, and that shouldn't be too terrible, though very likely can be further improved. It would be great to make separate tickets for each of the end-points.

I would very much be in favour of trying to deploy this sooner rather than later. It has no other dependencies and should just straight-up improve performance with very little risk.

Adding @karitotp as assignee to test: To Test that Export All for Emergencies works on staging, that the data returned is the same, and ideally feels "faster". If @karitotp gives a thumbs-up, let's discuss if we should deploy it during our call tomorrow.

**Comment by karitotp** [comment]
Hey @batpad, I gave a look to the exported csv of all emergencies and one for a filtered emergencies, the returned data match with the data in the staging, and I think the export is a bit faster, around 30 sec to export all emergency (3,907).

I only found one emergency https://dsgocdnapi.azureedge.net/api/event/3553/change/ that in the summary part has "éééééééééééé" but in the csv this looks weird:

![Screenshot from 2020-07-21 09-59-14](https://user-images.githubusercontent.com/11504548/88071109-096e0100-cb39-11ea-8598-bcf143aa196e.png)

**Comment by GregoryHorvath** [comment]
> Hey @batpad,...

^ I found this is actually an issue with the Rich Text Editors saving accented characters like this:
![image](https://user-images.githubusercontent.com/30079559/88791765-83863180-d19a-11ea-9d1c-3191e4b497d8.png)

As you can see it shows fine for the `name`. Looking into this.

**Comment by GregoryHorvath** [comment]
Separating the last comments into a new ticket since it's a separate issue. Thanks @karitotp nice find!

cc @batpad @nanometrenat

**Comment by tovari** [comment]
Testing passed on staging.

**Comment by tovari** [comment]
sorry, it shouldn't be closed yet.

**Comment by nanometrenat** [comment]
Released this morning I am told

**Comment by GregoryHorvath** [comment]
> Released this morning I am told

Yep, Appeals and Emergencies done. @batpad do we want to keep this one open for some possible near-future work on the other endpoints or should those be separate from this (hot)fix one?

**Comment by GregoryHorvath** [comment]
The above 3 PRs are also deployed to staging now. (the affected pages are the Django Admin ones, not the frontend)
