### ISSUE TITLE
Enable validating/activating users in the Pending users section

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#766]
It would be great to have the possibility to validate/verify/activate a user account through the pending users section in the Django admin (https://prddsgocdnapi.azureedge.net/registrations/pending/). 

Especially now as it seems the verification and validation emails are intermittently not getting through to users (#737) and a manual activation from the IM team is required in these cases, it would be good to be able to do that through the pending users overview page.

I propose adding the action of "Activate user" in the below dropdown

![image](https://user-images.githubusercontent.com/52411237/84385394-c8a4d300-abef-11ea-8100-27b95ec5581d.png)

This would then basically do the same as and tick the "Active" box under the user section on the Django admin (https://prddsgocdnapi.azureedge.net/auth/user/) i.e. activate the user account. 

At the moment when one of us manually activates an account the user will still show up on the pending users list and this makes it difficult to keep track of which users are indeed still "pending". So with the proposed feature, after activating the account, the user should not show as pending anymore.

**Comment by nanometrenat** [comment]
> At the moment when one of us manually activates an account the user will still show up on the pending users list and this makes it difficult to keep track of which users are indeed still "pending". So with the proposed feature, after activating the account, the user should not show as pending anymore.

The other option would be just to show the user's status in the pending users screen, so it's obvious if they have been activated via other routes - then the pending user could be separately deleted.

The advantage of this approach is that if admins activate the user without ever checking the screen then this would be obvious in pending users...

**Comment by GregoryHorvath** [comment]
Added the action mentioned in the ticket and a new column called "User is active" which shows "Yes" if the User is already active. Deployed to staging in the next 5-10 minutes.

**Comment by GregoryHorvath** [comment]
Closing this since this feature was released with v4.4.0, if it needs changing or further action we can reopen.
