### ISSUE TITLE
3W Project API call - long format for CSV

### ISSUE THREAD

**Issue by SimonbJohnson** [IFRCGo/go-api#768]
The current CSV export for 3W generates a file with 400 columns. This is due to it listing the admin areas in wide format. Wide format is difficult to use in mapping software where you want to join on one column.

https://goadmin.ifrc.org/api/v2/project/?format=csv

A long format means it can easily be mapped and used in tooling such as the HXL Proxy: https://proxy.hxlstandard.org/data/source

The long format currently is the standard format of 3W in the field.

Problems that will occur with repeating the project details is how to handle a single number such as reached over multiple rows.  These could be remove for simplicity.

**Comment by thenav56** [comment]
@tovari 
The changes are deployed to staging. https://dsgocdnapi.azureedge.net/api/v2/project/?format=csv

**Comment by tovari** [comment]
Thanks @thenav56, looks good!
@SimonbJohnson, would you mind to check it and let us know, how does it work for you?
Thanks!

**Comment by tovari** [comment]
The downloaded api response:
[3w-api-csv-response.txt](https://github.com/IFRCGo/go-api/files/6599345/3w-api-csv-response.txt)
