### ISSUE TITLE
[PROD] https links for images uploaded as snippets so it doesn't give a browser warning

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#771]
## Issue
Back end - On the edit Emergency page, snippets section, there's an option to upload an image so that the image can be displayed in the additional info (or other) tabs.

When I upload any image, the system gives it a URL - however the URL given by the system is an http URL rather than https - e.g. http://prddsgofilestorage.blob.core.windows.net/api/emergencies/3972/20200611_IFRC_COVID-19_Emergency_Allocations_as_at_8_June_with_annotation.png

![image](https://user-images.githubusercontent.com/33625192/84654866-31ea5600-af10-11ea-9a96-458987d285c1.png)

As noted by @batpad , this causes insecure content warnings when viewing the front end page (e.g. https://go.ifrc.org/emergencies/3972#actions)

There is no way for the user to edit the image URL to give it https - so need to either make it a https link, or omit the protocol  (e.g. //prddsgofilestorage.blob.core.windows.net/api/emergencies/3972/20200523_IFRC_COVID-19_Emergency_Allocations_as_at_15_May_manual_154.png ).  Omitting the protocol and it will use http:// or https:// based on the page it's being linked from.

You can tell if this issue is fixed because the browser will no longer show a little warning thing near the SSL lock in the browser bar.

Thanks!

**Comment by GregoryHorvath** [comment]
The possible fix is deployed to staging.
