### ISSUE TITLE
Translation: Django Admin static strings.

### ISSUE THREAD

**Issue by thenav56** [IFRCGo/go-api#774]

**Comment by nanometrenat** [comment]
Hi, is this the same ticket as https://github.com/IFRCGo/go-frontend/issues/1240 or are there differences in scope?  Many cheers!

**Comment by thenav56** [comment]
@nanometrenat Sorry for the late reply.
This ticket is focused on the strings used in `go-api` (Admin panel interface, API error messages, etc).
https://docs.djangoproject.com/en/2.2/topics/i18n/translation/
