### ISSUE TITLE
API - "search" parameter - not currently implemented on most endpoints

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#790]
## Issue
The API documentation in https://goadmin.ifrc.org/docs/ states that there is a "search" parameter for each endpoint.  However nothing that is specified in that param ever makes any difference apart from regional-project endpoint (which I don't think is used...)

This ticket is to specify which exact fields should be searched for each endpoint, so that search can then be implemented as desired.

First example is country endpoint, where it would be great if the search param searched at least country name, society name and the iso2/iso3.

More details below from a prior ticket.

> 4. While there, I have another question - what does the "search" param actually search, currently? I can't get it to change the output in any way at all... it would be great if the search param searched at least country name, society name and the isos... if poss? Or add as separate params if preferred?

Most probably it is this you're referring to?: https://www.django-rest-framework.org/api-guide/filtering/#searchfilter
It would mean if we used the `search_fields` in the 'Views' - which are the queryable endpoints - we could specify there fields for that search param to search in.

Edit: they are currently only used at 'RegionalProjectViewset' ('regional-project' endpoint):
https://github.com/IFRCGo/go-api/blob/e91b7b175ab2eca7f731f87d8a24f524e5c2ae1e/deployments/drf_views.py#L135

_Originally posted by @GregoryHorvath in https://github.com/IFRCGo/go-api/issues/759#issuecomment-647441547_

**Comment by szabozoltan69** [comment]
Done – deployed to staging.
An example:
https://dsgocdnapi.azureedge.net/docs/#api-v2-disaster_type-list
Default result:
![kép](https://user-images.githubusercontent.com/6050643/141793927-4b12eca6-c2c2-49d3-aeb4-7b89af587217.png)
Filtered result:
.../api/v2/disaster_type/?search=COld
![kép](https://user-images.githubusercontent.com/6050643/141794046-5588c34e-1b0a-475a-a3a6-ea86adb5ddaf.png)

**Comment by szabozoltan69** [comment]
I checked the admin pages for all the used searching possibilities and put them to the drf_views part, with a "# for /docs" comment.

**Comment by tovari** [comment]
List of endpoints:
/api/v2/eru/?search=a
/api/v2/personnel/?search=a
/api/v2/regional-project/?search=e
/api/v2/project/?search=a
/api/v2/disaster_type/?search=a
/api/v2/country/?search=h
/api/v2/district/?search=x
/api/v2/event/?search=y
/api/v2/situation_report_type/?search=s
/api/v2/situation_report/?search=a
/api/v2/appeal/?search=a
/api/v2/appeal_document/?search=a
/api/v2/field_report?search=S
/api/v2/main_contact?search=a
/api/v2/surge_alert?search=y
/api/v2/subscription?search=i

**Comment by szabozoltan69** [comment]
The search happens in these fields:
```
eru                ('national_society_country__name',)
personnel          ('name', 'role', 'type',)
regional-project   ('name',)
project            ('name',)
disaster_type      ('name',)
country            ('name',)
district           ('name', 'country__name',)
event              ('name', 'countries__name', 'dtype__name',)
situation_report_type ('type',)
situation_report   ('name', 'event__name',)
appeal             ('appeal__name', 'code',)
appeal_document    ('name', 'appeal__code', 'appeal__name')
field_report       ('countries__name', 'regions__name', 'summary',)
main_contact       ('name', 'email')
surge_alert        ('operation', 'message', 'event__name',)
subscription       ('user__username', 'rtype')
```

**Comment by tovari** [comment]
Thanks @szabozoltan69! 
Endpoints where search has been added:
ERUOwner
Personnel
RegionalProject
Project
DisasterType
Country
District
Event
SituationReportType
SituationReport
Appeal
AppealDocument
FieldReport
MainContact
SurgeAlert
Subscription

**Comment by szabozoltan69** [comment]
In the api_region there is a name field, which is practically the same as id.
For region names we introduced the "label" field (not to obfuscate frontend parts that relies on name as an integer).
So in this search functionality (and also the admin interface) this region__name should be changed to region__label
(see above: field_report       ('countries__name', 'regions__name', 'summary',))

**Comment by szabozoltan69** [comment]
![kép](https://user-images.githubusercontent.com/6050643/145000286-125f9b69-e834-434e-b476-804c11ca68eb.png)

**Comment by szabozoltan69** [comment]
The /api/v2/eru/?search= endpoint does not work. If I put there any country names, has no effect (collect the same quantity of records as without filtering).

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-api/pull/1244 solves the found name/label issue

**Comment by szabozoltan69** [comment]
(Deployed to staging)
