### ISSUE TITLE
3W API:  investigate/clarify 3W workflow when adding/editing etc. via API

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#804]
## Issue
NLRC would like to use the API to create / update / delete etc. 3W projects so that they can integrate their external system.

The API was thus far mostly focused on meeting the needs of the UI.

Can you please go through and investigate what the blockers might be if users wanted to manage 3Ws end to end through only the UI (and integrate external systems).

Thanks

**Comment by gulfaraz** [comment]
The report of the review is available [here](https://ifrcorg.sharepoint.com/sites/GOIVfordeveloperteam/Shared%20Documents/NLRC%20-%20API%20focus/3W_Integration.pdf).

**Comment by nanometrenat** [comment]
Assigning to Nat as need to check in with Henk

**Comment by gulfaraz** [comment]
@JonathanGarro I've closed the other issue as this is older. Moving the comments from there for convenience.

[Comment #1](https://github.com/IFRCGo/go-api/issues/1150#issue-961781793)
> _I'm creating this feature request on behalf of @JonathanGarro who sent the details via email._
> 
> A step beyond the [Excel upload](https://github.com/IFRCGo/go-api/issues/1149) would be having direct connections with teams’ existing portfolio management systems. While each NS system would be different, I’d be interested in how we can explore ways to at least set teams up to utilize a POST or PATCH method. We can use my NS’s system to test that process.

[Comment #2](https://github.com/IFRCGo/go-api/issues/1150#issuecomment-895237295)
> Documenting notes from @JonathanGarro's discussion on 2021-08-06 with @gulfaraz on this issue:
> 
> * **What we mean by sync:** This is _not_ a bi-directional sync where data is being passed from an NS IMS to GO and vice versa. This is only one direction: from NS IMS to GO _only_.
> * **Expected output:** This issue would not be building towards a single solution wherein any NS with an IMS could turn a key and sync their data. We anticipate the output here being more focused on establishing a framework to help teams with these databases understand what they have to do to get their data to sync (since each instance will have different requirements without the possibility for a "one-size-fits-all" approach).
> * **Expected scope:** This should focus on the 3W tool first with option to expand to other elements in the future, depending on how this testing goes.
> * **High-level plan moving forward:** Jonathan to build a simple example of a report from his database that maps the relevant fields on the 3W. Gulfaraz and Jonathan to test solutions for pushing that data to GO.

[Comment #3](https://github.com/IFRCGo/go-api/issues/1150#issuecomment-902748160)
> @JonathanGarro I've sent via email a python script that does a basic read-write of the 3W projects.
> 
> The script assumes a local CSV database and required manually setting an auth token.
> 
> I want to check with you if this is the right direction before continuing on it.

**Comment by nanometrenat** [comment]
I am closing this issue as know there has been a lot of work done on 3W and APIs since I logged it.
@JonathanGarro @toffehoff @tovari @szabozoltan69 @batpad feel free to re-open if in fact there is still work being tracked under this ticket after all.

Cheers!
