### ISSUE TITLE
[DEPLOYMENT] Improve / automate the deployment process

### ISSUE THREAD

**Issue by GergiH** [IFRCGo/go-api#814]
## Current deployment process - in short
1. Have all the changes on the `master` branch
2. Increase the version numbers in the `CHANGELOG.md` and `main/__init__.py`, and commit the change with a git tag of the version, ex. `git tag 1.1.286`
3. Wait for the Docker image being built from `master` with the tag number
4. Increase the version number in my local `.env` file (which contains most env vars needed for both the deployment and for the application)
5. Log into Azure via the Azure CLI and set "Azure env vars" (`login.sh` script locally)
6. Get `.key` file for the relevant (staging / production) container from Azure (`getkey.sh` script locally)
7. (`init-api.sh` script locally)
    - Get `.key` and `.crt` files for the relevant (staging / production) container from Azure
    - IP address and other vars for the deployment
    - `echo` the needed env vars into a temporary `env` file and `scp` it along with the previous `.key` and `.crt` files into the VM in Azure
    - `ssh` into the VM and do:
        - `docker stop \$(docker ps -q)`
        - `docker rm \$(docker ps -a -q)`
        - `docker pull ${API_DOCKER_IMAGE}`
        - `docker run -v \$(pwd)/.ifrcgoapi.crt:/etc/ssl/server.pem -v \$(pwd)/.ifrcgoapi.key:/etc/ssl/serverkey.pem -v \$(pwd)/go-logs:/home/ifrc/logs -p 80:80 -p 443:443 --env-file .env --entrypoint /usr/local/bin/runserver.sh -t -d ${API_DOCKER_IMAGE}`
    - Remove the temporary files from your local system

**Comment by nanometrenat** [comment]
xref existing open ticket "Back end deployment process improvement", which also has documentation around prior deployment process.  Suggest picking one of these tickets to stay open and closing the other one:  https://github.com/IFRCGo/go-frontend/issues/933
