### ISSUE TITLE
[PROD] Change wording of tickbox for hiding field report figures on emergency page

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#820]
## Issue
On emergency pages with field reports linked to them, there is the possibility on the Django admin to hide the numeric details (called Emergency overview on the emergency page frontend). 

section in question on field report page
![image](https://user-images.githubusercontent.com/52411237/87546345-b3690b80-c6a9-11ea-9e0c-637a4746d7df.png)
on emergency page
![image](https://user-images.githubusercontent.com/52411237/87546382-c380eb00-c6a9-11ea-8334-8cea2fdc9c9f.png)

This tickbox currently says "Hide attached field reports?" which may be misleading as the only thing it actually hides is the aforementioned numeric details. The field report itself, situation overview, map and contacts that are pulled from the linekd field report will still show on the page even when this box is ticked.

![image](https://user-images.githubusercontent.com/52411237/87546230-8157a980-c6a9-11ea-9fbc-ad76682f2d0a.png)

## Expected behaviour
The tickbox in the backend to say "Hide field report numeric details" or something along those lines.

## Related feature
https://github.com/IFRCGo/go-frontend/issues/1397

**Comment by nanometrenat** [comment]
@batpad  is this ready for QA?

**Comment by batpad** [comment]
Sorry, this did not fully get through in 4.3. Moving to 4.4.

**Comment by karitotp** [comment]
The tickbox was changed and now it is "Hide field report numeric details". Also, it is working as is expected. cc. @batpad
