### ISSUE TITLE
[Local] Global File Storage configuration.

### ISSUE THREAD

**Issue by thenav56** [IFRCGo/go-api#825]
# Issue
Right now custom `AzureStorage` module is passed to each `FileField` for storing to azure storage. We need to implement global configuration so that `AzureStorage` is only used when credentials are passed to the application. If not, the files should be stored be in the local disk and also served from local disk.

Error when uploading in local.
![image](https://user-images.githubusercontent.com/7059255/88142359-18c27c80-cc15-11ea-9ec1-90c8c2e2c412.png)

# Solution
- Use [default file storage configuration](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-DEFAULT_FILE_STORAGE) in Django. Only use `AzureStorage` if credentials are provided.
- Use sub directory to store media files locally `media/`
- Use Django storage plugin like [django-storages](https://django-storages.readthedocs.io/en/latest/backends/azure.html).

https://github.com/IFRCGo/go-api/blob/2a28e704c762e911d3e52fb9f5a149378696ced8/api/storage.py#L13-L217

# Checklist
- [ ] Don't define `storage=` argument in **FileField**.
- [ ] For **FileStorage**, use nested folder (using `MEDIA_ROOT`. https://docs.djangoproject.com/en/2.2/ref/settings/#media-root)
- [ ] Only use **AzureStorage** (django-storages) when credentials are provided. (Something like this https://github.com/the-deep/server/blob/develop/deep/settings.py#L274-L308.)

**Comment by batpad** [comment]
@thenav56 this is turning out to be a blocker to the Snapshot testing PR: https://github.com/IFRCGo/go-api/pull/829 - the problem being that some of the models we are creating Factories for, have fields that have an AzureStorage class, and that's generating errors locally.

@thenav56 The solution you've outlined above seems to make sense - @gulfaraz do you think you maybe able to take a look ?  @thenav56 would you be able to provide some more guidance on "Use default file storage configuration in Django. Only use AzureStorage if credentials are provided."?

**Comment by thenav56** [comment]
@batpad @gulfaraz 
This is the config used by the `AzureStorage` module in go-api.
https://github.com/IFRCGo/go-api/blob/edf4158d4386e7da87617a2d74fd8ed57cdebaa5/main/settings.py#L96-L101

Basically, if this config is not provided from environment variables then we use local storage. We can also add another env variable like `USE_AZURE_STORAGE` and use its value to switch between storage.
[django-storage](https://django-storages.readthedocs.io/en/latest/backends/azure.html) and [django file storage](https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-DEFAULT_FILE_STORAGE) should have required documention.

**Comment by gulfaraz** [comment]
@batpad I'll give it a shot.

@thenav56 Thank you for the solution and the references.

**Comment by gulfaraz** [comment]
I've created a PR #849 which I think resolves this issue. Please test and confirm if these changes are sufficient.

**Comment by GregoryHorvath** [comment]
Didn't mean to close the issue, it autoclosed by the relation on the PR.

**Comment by GregoryHorvath** [comment]
https://github.com/IFRCGo/go-api/pull/849 is now deployed to staging.

**Comment by LukeCaley** [comment]
@batpad  @gulfaraz should this be moved to Ready for QA?  If so, could either of you clearly articulate the testing params for @karitotp & @nanometrenat to confirm if OK?  Thanks!

**Comment by batpad** [comment]
For testers:

For all places in the backend where there are file uploads - eg. Response Documents - file uploads should continue working as before. @LukeCaley or @nanometrenat it maybe helpful to have an enumeration of all places in the Admin where users can upload files.

For developers:

For all places in the backend where there are file uploads, backend should not crash when developing locally.
