### ISSUE TITLE
typo dgacs vs gdacs in cronjob

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#826]
Today we had a new thing appear in the cronjob logs in both staging and Prod - **ingest_dgacs** (i.e. typo from gdacs) was logging as erroneous

Think the problem is here:  https://github.com/IFRCGo/go-api/blob/master/api/management/commands/ingest_gdacs.py#L24 - can you please fix?  Thanks

**Comment by GregoryHorvath** [comment]
@nanometrenat the fix is deployed to staging.

**Comment by nanometrenat** [comment]
Closing as can see the change has been made (pending release)) and we cannot force this test.

**Comment by nanometrenat** [comment]
Released this morning I am told
