### ISSUE TITLE
API Status page (potentially site also) and dashboard

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#831]
**Is your feature request related to a problem? Please describe.**
Proposed by @gulfaraz and @batpad but presumably useful to all - cc @GregoryHorvath 

Proposal is to get a better handle on API usage and status:

- Track usage and auto-generate analytics reports. The only reliable metric for API projects
- Server status page with coverage and test badge

Noting that in the logs it can be difficult to differentiate between API calls from the application/website vs direct-access API calls - however this ticket is to track discussions around what is feasible/possible to be able to monitor GO API usage and availability.

Nothing that previous requests for logs/usage tracking/exception tracking include:
- https://github.com/IFRCGo/go-api/issues/572#issue-546247724 Audit trail improvements requirements
- https://github.com/IFRCGo/go-api/issues/672 Better logging and notifications for 500 errors (includes mention of the sentry.io tool)

**Comment by gulfaraz** [comment]
For server status, I'll look at https://uptimerobot.com/ and other options.

**Comment by gulfaraz** [comment]
In the GO Sprint planning - March meeting, the team agreed that a simple indicator to check if the go-api is up. Any changes to the scope can be discussed here.

**Comment by gulfaraz** [comment]
@tovari I need access to an account in https://uptimerobot.com/ for this item.
I intend to add monitors for,
1. Production frontend
2. Production backend
3. Stage frontend
4. Stage backend

[The free plan only monitors in intervals of 5 mins.](https://uptimerobot.com/pricing/)

The final status page will look like [this one](https://stats.uptimerobot.com/RjRrnFrlvQ). The registered email will receive a mail alert when there is a change in status from any monitor.

**Comment by nanometrenat** [comment]
I have uptimerobot monitoring of GO already (production+staging front end, + Prod API) - but be delighted to turn it off, let me know when the official one is in place :)

**Comment by gulfaraz** [comment]
We've decided to use Azure Monitor instead of UptimeRobot as it has the features required for this item.

@szabozoltan69 here is the list of URLs that need to be monitored,
1. Production frontend - https://go.ifrc.org/
2. Production backend - https://api.go.ifrc.org/api/v2/
3. Stage frontend - https://dsgoproxyapp.azurewebsites.net/
4. Stage backend - https://dsgocdnapi.azureedge.net/api/v2/

@tovari  please give @szabozoltan69 the email list to receive alerts. Please include @nanometrenat in the list.

**Comment by szabozoltan69** [comment]
Do you think that on Azure side I have more permissions than you? :-)
If so, I'll do my best.
If this is to be set up on go-api side, it should be done via settings.py (or .env file).
@gulfaraz  I need some clarification about this, possibly in dm.

**Comment by gulfaraz** [comment]
@szabozoltan69 Apologies for the confusion, my intention was to tag Zoltan Levai but I tagged you instead.

@tovari I can't seem to find Zoltan Levai on GitHub to be tagged here.

**Comment by gulfaraz** [comment]
The monitoring has been set up and tested using Azure Monitor. Please feel free to close this issue if the required access and function is working as desired.
