### ISSUE TITLE
[PROD] Rich Text Editor fields replace accented characters

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-api#837]
## Issue
Rich Text Editor fields replace accented characters like: 'é' -> '&eacute'

Ref.: https://github.com/IFRCGo/go-api/issues/763#issuecomment-661917862, https://github.com/IFRCGo/go-api/issues/763#issuecomment-665594668

## Findings so far
Adding `'entity_encoding': 'raw',` to the TinyMCE config in `settings.py` helps with this, but also stucks some of the frontend pages in forever loading state.

**Comment by GregoryHorvath** [comment]
This was deployed to staging some time ago.

@karitotp @batpad If you now save any Rich Text Editor field with special characters is in it, it shouldn't convert those character into the ones mentioned in the ticket. _If you try to re-save an already existing one I believe you need to change something in it (add a space, or anything) for the save to also change those characters._
This can be tested with a CSV export (Emergencies for ex.), since the frontend pages would show ex. '&eacute' as 'é' anyway.

**Comment by karitotp** [comment]
>  If you now save any Rich Text Editor field with special characters is in it, it shouldn't convert those character into the ones mentioned in the ticket

Work good with accented characters but there are some other special charaters like `#` and `&` that is displayed weird in the csv.

 I added this text in https://dsgocdnapi.azureedge.net/en/api/event/4070/change/

```
testing rich text accented characters
á é í ó ú ẃśá. = # &
special characters = = % # / *
break line
```
But in the csv is displayed as: `testing rich text accented characters<br />á é í ó ú ẃśá. = ¤ &amp`. And this does not update even when I edited adding other text.

> If you try to re-save an already existing one I believe you need to change something in it (add a space, or anything) for the save to also change those characters.

This is working as you mentioned, I edited the previous one and the issue with accented characters was fixed.

cc. @GregoryHorvath

**Comment by tovari** [comment]
This has been resolved.
