### ISSUE TITLE
FDRS authentication method change

### ISSUE THREAD

**Issue by GergiH** [IFRCGo/go-api#851]
# Reason
FDRS API will change its authentication method to require an API Key.

# To Do
- [x] Change backend for testing to use the new method
- [x] Update the production ENV vars to include the production FDRS API key
- [x] Change backend for production, branching off from `master` as a hotfix (in URL, .info -> .org)
- [ ] (Optional) Change frontend [query-external.js](https://github.com/IFRCGo/go-frontend/blob/7103407449b779352de5ec7f635c229501499701/src/root/actions/query-external.js#L46) if the part [countries.js](https://github.com/IFRCGo/go-frontend/blob/7103407449b779352de5ec7f635c229501499701/src/root/views/countries.js#L457-L564) will be needed

**Comment by GregoryHorvath** [comment]
The backend changes were deployed. @batpad should we keep this open for the frontend changes of this, or can we close this? All relevant parts on the frontend are commented out atm, I don't know the reason for it though.
