### ISSUE TITLE
API changes coming as part of the pre-work for Translations release

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#855]
Aware that there is no ticket for the PR where this is discussed, so hereby creating a ticket in order to xref to https://github.com/IFRCGo/go-api/pull/850#issuecomment-678165230 so it appears on the board.

This PR will change both the structure and the content of responses returned to API users so will need to be clearly communicated.

**Additional context**

**Comment by nanometrenat** [comment]
@JonathanGarro FYI

**Comment by nanometrenat** [comment]
Hi, I just put a question in https://github.com/IFRCGo/go-api/pull/850#issuecomment-689186547 to be sure that all the display labels that we need will come through (as going through country data with Ana Maria just now)

@thenav56 I can see that these API changes don't seem to be in staging right now, what is the timeframe for them coming in to a place we can see them?  Thanks
cc @batpad @LukeCaley @guipizzini @anamariaescobar @JonathanGarro @jhenshall

**Comment by thenav56** [comment]
@nanometrenat The PR is ready for review. It's ready to be deployed to the staging. cc: @GregoryHorvath @batpad

**Comment by guipizzini** [comment]
This is completed, and has been successfully tested
