### ISSUE TITLE
Translation: Generate export for fixed model fields

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-api#888]
Since we're not doing automated translation, we'll need following models translated to all the language manually. It'll be a lot of work for user to do it through the Admin panel. So, we can do export for these fields and get users to add translations through CSV or excel (whichever is easier) and import back with translated texts.
- Actions
- Country
  - Name
  - Society name
  - Country contacts
    - Type
    - Name
    - Title
- Disaster type
- District
- Region

Alternatively, we can do a one time translate for only these models using the AWS translate (we'll require the access to the service)

@thenav56 need to make country contacts and district name translatable.

@GregoryHorvath @batpad let's discuss this and if feasible takeover on this one.
CC: @thenav56 

@guipizzini @nanometrenat Any thoughts or more fields that needs to be added?

Edit: Addressing @nanometrenat new models
- Actions
- Country
- Disaster type
- Region
- Situation report types

**Comment by nanometrenat** [comment]
Thanks for this!

Yes we will definitely need `Actions ` to be manually translated, this is key for all Field Report types not just COVID.  Suspect they will need to be translated manually as the wording of the English versions was quite carefully considered ;)  Same for `Disaster type` @mmusori @guipizzini will have ideas re best way to approach these.

Re `Countries` - these translations are already available for @guipizzini to give you (\08_Processes\0803_National Society list folder on Sharepoint)

Re `Society Name` I am not sure of approach to this, over to Guido, perhaps they all stay as English for the moment?

`Districts` will be the problematic thing - again perhaps they all stay as English for now? cc @jhenshall 

`Country Contacts` - these may not need to be translated at all, Guido to confirm

`Situation Report types` (i.e. the headings of the document section) will also need to be translated

THANKS
