### ISSUE TITLE
Create an endpoint for all the ENUM fields

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-api#889]
As we have the values of the ENUM constant fields separately maintained in the frontend and backend, which is not a good practice. So to keep only one source of truth, all those constants should be loaded from the API.

CC: @batpad @geohacker @GregoryHorvath @thenav56

**Comment by szabozoltan69** [comment]
Duplicate of https://github.com/IFRCGo/go-api/issues/1552
