### ISSUE TITLE
[PROD] 'iso' and 'iso3' fields are missing from CSV

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-api#916]
## Issue
`iso` and `iso3` fields for Countries are missing from the CSV versions of the Field Reports and Emergencies endpoints

## Steps to reproduce
- Get the CSV from https://goadmin.ifrc.org/api/v2/field_reports/?format=csv

## Expected behaviour
`iso` and `iso3` should be included

## Impact
Anyone who uses the CSV exports instead of the JSON ones and wants to reference the `iso` and `iso3` fields

## Severity
Low-Medium

## Is there a workaround?
No

**Comment by GregoryHorvath** [comment]
@anamariaescobar Please confirm that this was looking good on staging.

**Comment by anamariaescobar** [comment]
The .csv extracted from staging now included iso and iso3.
